import uuid
import operator
from typing import Dict, Any, List, TypedDict, Optional, Annotated


# Generated by GitHub Copilot
class AgentState(TypedDict):
    """Shared state passed between LangGraph nodes during an agent flow execution."""
    article_id: uuid.UUID
    author_id: uuid.UUID
    title: str
    keywords: List[str]
    research_data: str
    sources: List[Dict[str, Any]]
    draft_text: str
    feedback: Annotated[List[str], operator.add]
    approval_score: float
    formatted_text: str
    scientific_format: str
    published_url: str
    metadata: Dict[str, Any]
    flow_sequence: List[str]
    current_step_index: int
    loop_count: int
    # Per-agent model overrides: {"redactor": {"model": "mistral:7b"}, ...}
    agent_settings: Dict[str, Dict[str, Any]]
    # Optional context/focus description provided by the user when launching the pipeline
    context_description: str
