"""Cadena de suministro: dependencias pineadas y escaneadas (SPEC-020 / T6.2-T6.3).

AC2: la CI escanea dependencias (`pip-audit` + `npm audit`) y Dependabot cubre
backend, frontend y GitHub Actions.
AC3: las dependencias están pineadas con lockfile/hashes y **la CI instala desde el
lock, no desde rangos**.

Un lock solo sirve si nada lo puentea, así que estos tests miran las tres cosas a la
vez: que el lock esté completo, que el fichero fuente y el lock no hayan divergido, y
que el workflow siga instalando con verificación de hashes. Cualquiera de las tres
puede romperse sola y dejar el pineado como decoración.
"""
import re
import sys
from pathlib import Path

import pytest
import yaml

ROOT_DIR = Path(__file__).resolve().parents[1]
REPO_DIR = ROOT_DIR.parent
sys.path.insert(0, str(ROOT_DIR))

REQUIREMENTS_IN = ROOT_DIR / "requirements.in"
REQUIREMENTS_LOCK = ROOT_DIR / "requirements.txt"
CI_WORKFLOW = REPO_DIR / ".github" / "workflows" / "ci.yml"
DEPENDABOT = REPO_DIR / ".github" / "dependabot.yml"

# "nombre==version" al principio de línea; el resto son hashes y comentarios.
PINNED_RE = re.compile(r"^(?P<name>[A-Za-z0-9._-]+)(?P<extras>\[[^\]]+\])?==(?P<version>[^\s\\]+)")


def _lock_lines() -> list[str]:
    return REQUIREMENTS_LOCK.read_text(encoding="utf-8").splitlines()


def _locked_packages() -> dict[str, str]:
    packages = {}
    for line in _lock_lines():
        match = PINNED_RE.match(line)
        if match:
            packages[match.group("name").lower().replace("_", "-")] = match.group("version")
    return packages


def _source_requirements() -> list[str]:
    names = []
    for line in REQUIREMENTS_IN.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = re.split(r"[<>=!~\[;]", line)[0].strip()
        if name:
            names.append(name.lower().replace("_", "-"))
    return names


# --------------------------------------------------------------------------- #
# AC3 — el lock existe, está completo y tiene hashes
# --------------------------------------------------------------------------- #

def test_source_and_lock_are_separate_files():
    """`requirements.in` es lo que se edita; `requirements.txt` es lo que se instala."""
    assert REQUIREMENTS_IN.exists(), "falta requirements.in (la fuente de rangos)"
    assert REQUIREMENTS_LOCK.exists(), "falta requirements.txt (el lock)"


def test_lock_is_generated_not_hand_written():
    header = "\n".join(_lock_lines()[:6])
    assert "autogenerated by pip-compile" in header, (
        "requirements.txt no parece compilado: ¿se editó a mano?"
    )


def test_every_locked_package_has_an_exact_version():
    """Ni un solo rango: con `>=` la reconstrucción de mañana trae otra cosa."""
    lines = [
        line for line in _lock_lines()
        if line and not line.startswith((" ", "#", "-")) and "==" not in line
    ]
    assert not lines, f"requisitos sin versión exacta en el lock: {lines}"


def test_every_locked_package_carries_hashes():
    """Sin hash, el pineado solo dice *qué versión*, no *qué artefacto*."""
    content = REQUIREMENTS_LOCK.read_text(encoding="utf-8")
    blocks = [b for b in re.split(r"\n(?=[A-Za-z0-9])", content) if PINNED_RE.match(b)]
    assert blocks, "no se reconoció ningún paquete en el lock"
    sin_hash = [b.splitlines()[0] for b in blocks if "--hash=sha256:" not in b]
    assert not sin_hash, f"paquetes sin hash: {sin_hash}"


def test_lock_covers_every_declared_requirement():
    """Si alguien añade a `.in` y no recompila, el lock se queda corto en silencio."""
    locked = _locked_packages()
    faltan = [name for name in _source_requirements() if name not in locked]
    assert not faltan, f"declarados en requirements.in pero ausentes del lock: {faltan}"


def test_lock_includes_transitive_dependencies():
    """`--require-hashes` exige que TODA la cadena esté en el fichero, no solo la raíz."""
    locked = _locked_packages()
    directas = set(_source_requirements())
    transitivas = set(locked) - directas
    assert len(transitivas) > len(directas) // 2, (
        "el lock apenas trae dependencias transitivas; ¿se generó sin resolver?"
    )


# --------------------------------------------------------------------------- #
# AC3 — y la CI instala desde ahí
# --------------------------------------------------------------------------- #

def _ci() -> dict:
    return yaml.safe_load(CI_WORKFLOW.read_text(encoding="utf-8"))


def _steps(job: str) -> list[dict]:
    return _ci()["jobs"][job]["steps"]


def test_ci_installs_the_backend_with_hash_checking():
    runs = " ".join(step.get("run", "") for step in _steps("backend-tests"))
    assert "--require-hashes" in runs, "la CI instala sin verificar hashes"
    assert "requirements.in" not in runs, "la CI instala desde la fuente, no desde el lock"


def test_ci_installs_the_frontend_from_its_lockfile():
    """`npm ci` respeta package-lock.json; `npm install` puede moverlo."""
    runs = " ".join(step.get("run", "") for step in _steps("frontend-build"))
    assert "npm ci" in runs
    assert "npm install" not in runs


# --------------------------------------------------------------------------- #
# AC2 — escaneo en CI y Dependabot
# --------------------------------------------------------------------------- #

def test_ci_has_a_dependency_audit_job():
    assert "deps-audit" in _ci()["jobs"], "no hay job de auditoría de dependencias"


def test_the_audit_job_runs_both_scanners():
    runs = " ".join(step.get("run", "") for step in _steps("deps-audit"))
    assert "pip-audit" in runs
    assert "npm audit" in runs


def test_the_backend_audit_is_blocking():
    """Un escaneo que nunca falla no es un gate. Aquí no puede llevar `|| true`."""
    for step in _steps("deps-audit"):
        run = step.get("run", "")
        if "pip-audit" in run and "pip install" not in run:
            assert "|| true" not in run, "pip-audit no bloquea"
            assert not step.get("continue-on-error"), "pip-audit no bloquea"
            return
    pytest.fail("no se encontró el paso de pip-audit")


def test_ignored_vulnerabilities_are_justified_in_place():
    """Una excepción sin motivo escrito al lado es una excepción que nadie revisa."""
    text = CI_WORKFLOW.read_text(encoding="utf-8")
    for ignored in re.findall(r"--ignore-vuln\s+(\S+)", text):
        assert ignored in text.split("run:")[0] or text.count(ignored) >= 2, (
            f"{ignored} se ignora sin explicación en el propio workflow"
        )


def test_dependabot_covers_the_three_ecosystems():
    """Las Actions también traen código de terceros, y son las que más se olvidan."""
    config = yaml.safe_load(DEPENDABOT.read_text(encoding="utf-8"))
    ecosistemas = {u["package-ecosystem"] for u in config["updates"]}
    assert {"pip", "npm", "github-actions"} <= ecosistemas, f"faltan: {ecosistemas}"


def test_dependabot_points_at_the_real_directories():
    config = yaml.safe_load(DEPENDABOT.read_text(encoding="utf-8"))
    directorios = {u["package-ecosystem"]: u["directory"] for u in config["updates"]}
    assert directorios["pip"] == "/backend"
    assert directorios["npm"] == "/frontend"
    assert (REPO_DIR / "backend" / "requirements.in").exists()
    assert (REPO_DIR / "frontend" / "package.json").exists()


@pytest.mark.parametrize("ecosystem", ["pip", "npm", "github-actions"])
def test_dependabot_runs_on_a_schedule(ecosystem):
    config = yaml.safe_load(DEPENDABOT.read_text(encoding="utf-8"))
    update = next(u for u in config["updates"] if u["package-ecosystem"] == ecosystem)
    assert update["schedule"]["interval"] in {"daily", "weekly", "monthly"}
