from abc import ABC, abstractmethod
from typing import Dict, Any

from app.modules.agents.domain.entities import AgentState


# Generated by GitHub Copilot
class IAgentRunner(ABC):
    """Port defining the contract for any agent runner node."""

    @abstractmethod
    async def run(self, state: AgentState) -> Dict[str, Any]:
        """Execute the agent logic and return a partial state update."""
        ...
