import asyncio
import logging
import datetime
import re
import uuid
from pathlib import Path
from typing import Dict, Any, List

from sqlalchemy import select
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import InMemorySaver

from app.shared.database import AsyncSessionLocal
from app.shared.llm import TransientLLMError
from app.models import AgentRunModel
from app.modules.agents.domain.entities import AgentState
from app.modules.agents.adapters.investigador import run_investigador
from app.modules.agents.adapters.redactor import run_redactor
from app.modules.agents.adapters.revisor import run_revisor
from app.modules.agents.adapters.formateador import run_formateador
from app.modules.agents.adapters.publicador import run_publicador
from app.modules.agents.adapters.generic import run_generic_agent, load_agent_profile

logger = logging.getLogger(__name__)

# Global registry for active SSE streams: article_id -> list of asyncio.Queue
active_streams: Dict[uuid.UUID, list] = {}

# Global registry for active pipeline tasks: article_id -> asyncio.Task
active_tasks: Dict[uuid.UUID, asyncio.Task] = {}

# LangGraph checkpointer: persists the graph state after every completed node so a
# failed pipeline can be resumed from the last successful step instead of restarting.
# Keyed by thread_id == str(article_id). In-memory: survives transient agent errors
# (e.g. Ollama momentarily unreachable) while the backend process keeps running.
_pipeline_checkpointer = InMemorySaver()


def _thread_config(article_id: uuid.UUID) -> Dict[str, Any]:
    """Build the LangGraph config that scopes checkpoints to a single article run."""
    return {"configurable": {"thread_id": str(article_id)}}


async def has_pipeline_checkpoint(article_id: uuid.UUID) -> bool:
    """Return True if a resumable checkpoint exists for this article's pipeline."""
    try:
        tuple_ = await _pipeline_checkpointer.aget_tuple(_thread_config(article_id))
        return tuple_ is not None
    except Exception:
        return False

# Pending human-in-the-loop decisions: article_id -> Future resolved by the user
pending_decisions: Dict[uuid.UUID, "asyncio.Future[str]"] = {}

# Default decision when the user does not respond in time (avoid hanging forever)
_DECISION_TIMEOUT = 900.0  # 15 minutes


async def request_user_decision(article_id: uuid.UUID, payload: Dict[str, Any]) -> str:
    """Pause the pipeline and ask the user for a decision.

    Emits an ``await_decision`` SSE event and blocks until the user responds via
    ``submit_user_decision`` or the timeout elapses (defaulting to "continue").
    """
    loop = asyncio.get_event_loop()
    future: "asyncio.Future[str]" = loop.create_future()
    pending_decisions[article_id] = future

    publish_event(article_id, {"type": "await_decision", **payload})
    try:
        return await asyncio.wait_for(future, timeout=_DECISION_TIMEOUT)
    except asyncio.TimeoutError:
        logger.info("User decision timed out for article %s — defaulting to 'continue'", article_id)
        publish_event(article_id, {"type": "decision_resolved", "decision": "continue", "timed_out": True})
        return "continue"
    finally:
        pending_decisions.pop(article_id, None)


def submit_user_decision(article_id: uuid.UUID, decision: str) -> bool:
    """Resolve a pending decision for an article. Returns True if one was waiting."""
    future = pending_decisions.get(article_id)
    if future is not None and not future.done():
        future.set_result(decision)
        publish_event(article_id, {"type": "decision_resolved", "decision": decision})
        return True
    return False

# In-memory log buffer: article_id -> list of formatted log lines
_log_buffers: Dict[uuid.UUID, List[str]] = {}

# Logs output directory (relative to CWD, i.e. backend/)
_LOGS_DIR = Path("logs")


def _sanitize_filename(text: str) -> str:
    """Convert arbitrary text to a safe filename component."""
    text = text.strip()
    # Replace spaces and separators with underscores
    text = re.sub(r"[\s/\\:*?\"<>|]+", "_", text)
    # Keep only alphanumeric, underscores, and hyphens
    text = re.sub(r"[^\w\-]", "", text)
    return text[:60] or "pipeline"


def _flush_log_file(article_id: uuid.UUID, title: str) -> None:
    """Write the accumulated log buffer for an article to a file in the logs/ directory."""
    lines = _log_buffers.pop(article_id, [])
    if not lines:
        return
    try:
        _LOGS_DIR.mkdir(parents=True, exist_ok=True)
        date_str = datetime.datetime.now().strftime("%Y-%m-%d_%H%M%S")
        safe_title = _sanitize_filename(title)
        filename = _LOGS_DIR / f"log_{safe_title}_{date_str}.txt"
        content = "\n".join(lines)
        filename.write_text(content, encoding="utf-8")
        logger.info("Pipeline log saved to %s", filename)
    except Exception as exc:
        logger.warning("Could not write pipeline log file: %s", exc)


# Generated by GitHub Copilot
def publish_event(article_id: uuid.UUID, event: dict) -> None:
    """Push an SSE event dict to all queues subscribed to the given article_id.
    Log-type events are also appended to the in-memory buffer for file persistence.
    """
    # Buffer log lines for file output
    ev_type = event.get("type")
    if ev_type == "log":
        ts = datetime.datetime.now().strftime("%H:%M:%S")
        agent = event.get("agent", "pipeline")
        msg = event.get("message", "")
        level = (event.get("level") or "info").upper()
        _log_buffers.setdefault(article_id, []).append(
            f"[{ts}] [{level}] [{agent}] {msg}"
        )
    elif ev_type == "agent_error":
        ts = datetime.datetime.now().strftime("%H:%M:%S")
        agent = event.get("agent", "?")
        err = event.get("error", "")
        _log_buffers.setdefault(article_id, []).append(
            f"[{ts}] [ERROR] [{agent}] ✗ {err}"
        )

    if article_id in active_streams:
        for q in active_streams[article_id]:
            try:
                q.put_nowait(event)
            except Exception:
                pass


async def log_run_start(
    agent_name: str,
    article_id: uuid.UUID,
    author_id: uuid.UUID,
    input_payload: dict,
) -> uuid.UUID:
    """Persist an AgentRun record with status 'running' and return its run_id."""
    try:
        async with AsyncSessionLocal() as session:
            run = AgentRunModel(
                agent_name=agent_name,
                article_id=article_id,
                author_id=author_id,
                status="running",
                input_payload=input_payload,
                started_at=datetime.datetime.now(datetime.timezone.utc),
            )
            session.add(run)
            await session.commit()
            await session.refresh(run)
            return run.run_id
    except Exception as e:
        logger.error(f"Error logging run start for {agent_name}: {str(e)}")
        return uuid.uuid4()


async def log_run_end(
    run_id: uuid.UUID,
    output_payload: dict,
    status: str,
    error_message: str = None,
) -> None:
    """Update an existing AgentRun record with the final status and output."""
    try:
        async with AsyncSessionLocal() as session:
            stmt = select(AgentRunModel).where(AgentRunModel.run_id == run_id)
            res = await session.execute(stmt)
            run = res.scalars().first()
            if run:
                run.output_payload = output_payload or {}
                run.status = status
                run.error_message = error_message
                run.finished_at = datetime.datetime.now(datetime.timezone.utc)
                session.add(run)
                await session.commit()
    except Exception as e:
        logger.error(f"Error logging run end for run {run_id}: {str(e)}")


def make_node_wrapper(agent_name: str, run_fn):
    """
    Return an async LangGraph node function that wraps run_fn with logging,
    SSE event emission, and step-index tracking.
    """
    async def wrapper(state: AgentState) -> Dict[str, Any]:
        article_id = state.get("article_id")
        author_id = state.get("author_id")

        input_data = {
            "title": state.get("title"),
            "keywords": state.get("keywords"),
            "scientific_format": state.get("scientific_format"),
            "current_step_index": state.get("current_step_index", 0),
            "loop_count": state.get("loop_count", 0),
        }

        def log_fn(message: str, level: str = "info") -> None:
            """Emit a detailed SSE log event for this agent's execution."""
            publish_event(article_id, {"type": "log", "agent": agent_name, "message": message, "level": level})

        def emit_token_fn(token: str) -> None:
            """Emit a word-by-word token SSE event for visual typing."""
            publish_event(article_id, {"type": "token", "agent": agent_name, "token": token})

        async def request_decision_fn(payload: Dict[str, Any]) -> str:
            """Pause this node and await a user decision (human-in-the-loop)."""
            return await request_user_decision(article_id, payload)

        publish_event(article_id, {"type": "agent_start", "agent": agent_name})

        run_id = await log_run_start(agent_name, article_id, author_id, input_data)

        # Inject log_fn, emit_token_fn and request_decision_fn into state so
        # adapters can emit SSE events and pause for user input.
        enriched_state = dict(state)
        enriched_state["_log"] = log_fn
        enriched_state["_emit_token"] = emit_token_fn
        enriched_state["_request_decision"] = request_decision_fn

        try:
            res = await run_fn(enriched_state)
            await log_run_end(run_id, res, "completed")

            end_event: Dict[str, Any] = {"type": "agent_end", "agent": agent_name, "output": res}
            if res.get("draft_text"):
                end_event["draft_text"] = res["draft_text"]
            if res.get("formatted_text"):
                end_event["formatted_text"] = res["formatted_text"]

            publish_event(article_id, end_event)

            res["current_step_index"] = state.get("current_step_index", 0) + 1
            return res
        except Exception as e:
            logger.error(f"Error executing agent {agent_name}: {str(e)}")
            await log_run_end(run_id, {}, "failed", error_message=str(e))
            publish_event(article_id, {"type": "agent_error", "agent": agent_name, "error": str(e)})
            publish_event(article_id, {"type": "log", "agent": agent_name, "message": f"✗ {agent_name} falló: {str(e)}", "level": "error"})
            raise

    return wrapper


MAX_REVIEW_LOOPS = 3


def _next_after_revisor(flow: List[str]) -> str:
    """Return the node that follows 'revisor' in the flow, or END."""
    try:
        revisor_idx = flow.index("revisor")
        if revisor_idx + 1 < len(flow):
            return flow[revisor_idx + 1]
    except ValueError:
        pass
    return "__end__"


def route_after_revisor(state: AgentState) -> str:
    """
    Conditional edge after the revisor node.

    - user chose "add_source"  →  re-run from investigador (or redactor) with the
      newly uploaded document so it feeds research and citations.
    - user chose "continue"    →  advance to the next node regardless of score.
    - no explicit decision (headless / coherent draft):
        - score < 80 AND loop_count < MAX  →  automatic redraft loop to redactor
        - otherwise                        →  next node in flow (or END)
    """
    flow = state.get("flow_sequence", [])
    user_decision = state.get("user_decision")

    if user_decision == "add_source":
        for candidate in ("investigador", "redactor"):
            if candidate in flow:
                logger.info("User added a source — re-running from '%s'.", candidate)
                return candidate
        return _next_after_revisor(flow)

    if user_decision == "continue":
        logger.info("User chose to continue with the current draft.")
        return _next_after_revisor(flow)

    # No human decision recorded — fall back to automatic score-based looping.
    approval_score = state.get("approval_score", 100)
    loop_count = state.get("loop_count", 0)
    if approval_score < 80 and loop_count < MAX_REVIEW_LOOPS:
        logger.info(
            f"Revisor scored {approval_score} (loop {loop_count}/{MAX_REVIEW_LOOPS}). "
            "Looping back to redactor."
        )
        return "redactor"

    next_node = _next_after_revisor(flow)
    logger.info(f"Revisor scored {approval_score}. Advancing to '{next_node}'.")
    return next_node


class Orchestrator:
    """Dynamically compiles and executes a LangGraph flow for article generation."""

    @staticmethod
    def compile_graph(flow_sequence: List[str]) -> Any:
        """Build and compile a StateGraph from the requested flow_sequence."""
        if not flow_sequence:
            raise ValueError("flow_sequence cannot be empty")

        workflow = StateGraph(AgentState)

        agents_map = {
            "investigador": make_node_wrapper("investigador", run_investigador),
            "redactor": make_node_wrapper("redactor", run_redactor),
            "revisor": make_node_wrapper("revisor", run_revisor),
            "formateador": make_node_wrapper("formateador", run_formateador),
            "publicador": make_node_wrapper("publicador", run_publicador),
        }

        nodes_to_add = set(flow_sequence)
        if "revisor" in nodes_to_add:
            nodes_to_add.add("redactor")

        for node_name in nodes_to_add:
            if node_name in agents_map:
                workflow.add_node(node_name, agents_map[node_name])
            else:
                # Dynamic lookup: check for a custom .agent.md profile
                profile = load_agent_profile(node_name)
                if profile is None:
                    raise ValueError(
                        f"Unknown agent '{node_name}': no built-in implementation "
                        f"and no .agent.md profile found."
                    )
                logger.info(f"Registering custom agent '{node_name}' from .agent.md profile")
                runner = lambda s, _name=node_name: run_generic_agent(_name, s)
                workflow.add_node(node_name, make_node_wrapper(node_name, runner))

        workflow.add_edge(START, flow_sequence[0])

        for i, node_name in enumerate(flow_sequence):
            is_last = i == len(flow_sequence) - 1

            if node_name == "revisor":
                path_map = {"redactor": "redactor", "__end__": END}
                for n in flow_sequence:
                    path_map[n] = n
                workflow.add_conditional_edges("revisor", route_after_revisor, path_map)
            elif is_last:
                workflow.add_edge(node_name, END)
            else:
                workflow.add_edge(node_name, flow_sequence[i + 1])

        # Compile with the shared checkpointer so each completed node is persisted and
        # the run can be resumed from the last successful step after a failure.
        return workflow.compile(checkpointer=_pipeline_checkpointer)

    @classmethod
    async def run(
        cls,
        article_id: uuid.UUID,
        author_id: uuid.UUID,
        title: str,
        keywords: List[str],
        scientific_format: str,
        flow_sequence: List[str],
        agent_settings: Dict[str, Any] = None,
        context_description: str = "",
        initial_draft_text: str = "",
        article_outline: str = "",
        resume: bool = False,
    ) -> Dict[str, Any]:
        """Execute the compiled LangGraph flow and return the final state.

        When ``resume`` is True, re-invoke the graph from the last persisted
        checkpoint (the node that previously failed) instead of starting over, so
        the work already done by completed agents is preserved.
        """
        compiled_graph = cls.compile_graph(flow_sequence)
        config = _thread_config(article_id)

        # Resume only makes sense if a checkpoint actually exists; otherwise fall
        # back to a clean run so we never hang waiting for non-existent state.
        if resume and not await has_pipeline_checkpoint(article_id):
            logger.warning(
                "Resume requested for article %s but no checkpoint found — starting fresh.",
                article_id,
            )
            resume = False

        if not resume:
            # Clear any stale checkpoint from a previous attempt so a fresh run
            # starts from START instead of resuming an old thread.
            try:
                await _pipeline_checkpointer.adelete_thread(str(article_id))
            except Exception:
                pass

        initial_state = AgentState(
            article_id=article_id,
            author_id=author_id,
            title=title,
            keywords=keywords,
            research_data="",
            sources=[],
            draft_text=initial_draft_text,
            feedback=[],
            approval_score=100.0,
            formatted_text="",
            scientific_format=scientific_format,
            published_url="",
            metadata={},
            flow_sequence=flow_sequence,
            current_step_index=0,
            loop_count=0,
            agent_settings=agent_settings or {},
            context_description=context_description,
            article_outline=article_outline,
        )

        verb = "Resuming" if resume else "Starting"
        logger.info(f"{verb} LangGraph run for article {article_id} with sequence {flow_sequence}")

        # Register this coroutine as a cancellable task
        current_task = asyncio.current_task()
        if current_task is not None:
            active_tasks[article_id] = current_task

        # Open log buffer for this run
        _log_buffers[article_id] = []
        ts_start = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        header_title = "PIPELINE LOG (REANUDADO)" if resume else "PIPELINE LOG"
        _log_buffers[article_id].append(
            f"{'='*60}\n"
            f"{header_title} — {title}\n"
            f"Artículo ID : {article_id}\n"
            f"Inicio      : {ts_start}\n"
            f"Agentes     : {' → '.join(flow_sequence)}\n"
            f"{'='*60}"
        )
        if resume:
            publish_event(article_id, {
                "type": "log", "agent": "pipeline",
                "message": "↻ Reanudando pipeline desde el último checkpoint", "level": "info",
            })

        try:
            # On resume, pass None so LangGraph continues from the checkpoint
            # (re-running the node that failed) rather than re-seeding from START.
            # A transient failure (e.g. Ollama briefly unreachable) that survives the
            # LLM-layer retries is auto-resumed from the last checkpoint a few times
            # before we surface the error for a manual retry.
            from app.core.config import settings
            max_auto = int(getattr(settings, "PIPELINE_AUTO_RESUME_ATTEMPTS", 2) or 0)
            auto_delay = float(getattr(settings, "PIPELINE_AUTO_RESUME_DELAY", 3.0) or 0.0)

            local_resume = resume
            auto_attempt = 0
            while True:
                try:
                    graph_input = None if local_resume else initial_state
                    final_state = await compiled_graph.ainvoke(graph_input, config=config)
                    break
                except asyncio.CancelledError:
                    raise
                except TransientLLMError as exc:
                    can_auto = (
                        auto_attempt < max_auto
                        and await has_pipeline_checkpoint(article_id)
                    )
                    if not can_auto:
                        raise
                    auto_attempt += 1
                    publish_event(article_id, {
                        "type": "log", "agent": "pipeline", "level": "warn",
                        "message": (
                            f"↻ Error transitorio; reanudando automáticamente desde el "
                            f"checkpoint (intento {auto_attempt}/{max_auto}) en {auto_delay:.0f}s…"
                        ),
                    })
                    logger.warning(
                        "Auto-resuming article %s after transient error (attempt %d/%d): %s",
                        article_id, auto_attempt, max_auto, exc,
                    )
                    await asyncio.sleep(auto_delay)
                    local_resume = True  # subsequent attempts continue from checkpoint
            ts_end = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            _log_buffers.setdefault(article_id, []).append(
                f"\n{'='*60}\nFIN — {ts_end} — Pipeline completado con éxito\n{'='*60}"
            )
            publish_event(article_id, {"type": "done"})
            logger.info(f"Completed LangGraph run for article {article_id}")
            _flush_log_file(article_id, title)
            # Run finished cleanly — drop the checkpoint to free memory.
            try:
                await _pipeline_checkpointer.adelete_thread(str(article_id))
            except Exception:
                pass
            return final_state
        except asyncio.CancelledError:
            ts_end = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            _log_buffers.setdefault(article_id, []).append(
                f"\n{'='*60}\nCANCELADO — {ts_end} — Pipeline detenido por el usuario\n{'='*60}"
            )
            publish_event(article_id, {"type": "cancelled"})
            logger.info(f"Pipeline cancelled for article {article_id}")
            _flush_log_file(article_id, title)
            # Leave article in DRAFT — no further DB writes needed
            raise
        except Exception as exc:
            ts_end = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            _log_buffers.setdefault(article_id, []).append(
                f"\n{'='*60}\nERROR — {ts_end} — {exc}\n{'='*60}"
            )
            # A checkpoint of the last successful node remains, so the run can be
            # resumed from where it broke. Tell the client it may offer "resume".
            can_resume = await has_pipeline_checkpoint(article_id)
            publish_event(article_id, {
                "type": "done_error", "error": str(exc), "can_resume": can_resume,
            })
            logger.error(f"LangGraph run failed for article {article_id}: {exc}")
            _flush_log_file(article_id, title)
            raise
        finally:
            active_tasks.pop(article_id, None)
