"""Tool registry and executor for agentic tool calling.

Tools are exposed to the LLM as callable functions. The agent can invoke them
during a multi-turn tool-call loop before producing its final response.

Supported by both providers:
  * Ollama  — /api/chat with ``tools`` field (llama3.2, mistral, etc.)
  * OpenAI  — chat.completions.create() with ``tools`` field
"""

# Generated by GitHub Copilot

import logging
import re
from typing import Any, Dict, List
from urllib.parse import parse_qs, urlparse, unquote

# Sin cliente HTTP propio: todo el fetch saliente de este módulo sale por la guarda
# de egress (SPEC-024/AC4). Un `httpx.AsyncClient` aquí volvería a esquivarla, y hay
# un test estructural que lo impide.
from app.platform.egress import EgressBlocked, safe_get

logger = logging.getLogger(__name__)

# ── Catalog ───────────────────────────────────────────────────────────────────
# Each entry contains the metadata shown in the UI plus the JSON-Schema used
# when building the tool definition sent to the LLM.

TOOL_CATALOG: List[Dict[str, Any]] = [
    {
        "name": "web_search",
        "label": "Búsqueda web",
        "description": (
            "Busca información actualizada en la web sobre un tema y devuelve "
            "un resumen con fuentes."
        ),
        "icon": "Search",
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "La consulta de búsqueda en lenguaje natural",
                }
            },
            "required": ["query"],
        },
    },
    {
        "name": "fetch_url",
        "label": "Leer URL",
        "description": (
            "Descarga y extrae el texto principal de una página web dado su URL."
        ),
        "icon": "Globe",
        "parameters": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "description": "URL completa de la página (debe empezar por https://)",
                }
            },
            "required": ["url"],
        },
    },
    {
        "name": "word_count",
        "label": "Contar palabras",
        "description": "Cuenta el número de palabras en un texto dado.",
        "icon": "Hash",
        "parameters": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "El texto cuyas palabras se contarán",
                }
            },
            "required": ["text"],
        },
    },
    {
        "name": "get_current_date",
        "label": "Fecha actual",
        "description": "Devuelve la fecha y hora actuales en español.",
        "icon": "Calendar",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
]

_CATALOG_BY_NAME: Dict[str, Dict[str, Any]] = {t["name"]: t for t in TOOL_CATALOG}


def get_tool_schemas(tool_names: List[str]) -> List[Dict[str, Any]]:
    """Return OpenAI/Ollama-compatible tool definitions for the requested names."""
    return [
        {
            "type": "function",
            "function": {
                "name": t["name"],
                "description": t["description"],
                "parameters": t["parameters"],
            },
        }
        for name in tool_names
        if (t := _CATALOG_BY_NAME.get(name))
    ]


# ── Executor ─────────────────────────────────────────────────────────────────

async def execute_tool(name: str, arguments: Dict[str, Any]) -> str:
    """Dispatch a tool call by name and return the result as a plain string."""
    try:
        if name == "web_search":
            return await _web_search(arguments.get("query", ""))
        if name == "fetch_url":
            return await _fetch_url(arguments.get("url", ""))
        if name == "word_count":
            text = arguments.get("text", "")
            count = len(text.split())
            return f"El texto tiene {count} palabras."
        if name == "get_current_date":
            import datetime
            now = datetime.datetime.now()
            return now.strftime("Fecha actual: %A, %d de %B de %Y. Hora: %H:%M.")
        return f"Herramienta desconocida: '{name}'"
    except Exception as exc:
        logger.error("Tool '%s' failed: %s", name, exc)
        return f"Error al ejecutar '{name}': {exc}"


# ── Tool implementations ──────────────────────────────────────────────────────

async def _web_search(query: str) -> str:
    """Search for academic content using arXiv + Wikipedia APIs.

    DuckDuckGo is blocked in corporate environments.  arXiv provides
    quality academic papers; Wikipedia covers broader knowledge.
    Returns a formatted text with titles, URLs and snippets.
    """
    if not query.strip():
        return "No se proporcionó una consulta."

    try:
        results = await ddg_search_with_urls(query, max_results=5)
        if not results:
            return f"Sin resultados académicos para: '{query}'"
        parts: List[str] = []
        for r in results:
            parts.append(
                f"• {r.get('title', 'Sin título')}\n"
                f"  URL: {r.get('url', '')}\n"
                f"  {r.get('snippet', '')[:300]}"
            )
        return "\n\n".join(parts)
    except Exception as exc:
        return f"Error de búsqueda: {exc}"


async def _fetch_url(url: str) -> str:
    """Fetch a URL and return plain text (HTML stripped, max 8000 chars).

    La URL la elige **el modelo**, y lo descargado vuelve a su contexto. Sin la
    guarda de egress (SPEC-024) esto alcanza el endpoint de metadatos de la nube,
    la propia API en `localhost` o Qdrant, y devuelve lo leído: no es un SSRF
    ciego, es exfiltración. La comprobación del esquema la hace también la guarda;
    aquí no se repite para que haya **un** sitio que decide.
    """
    try:
        headers = {"User-Agent": "Mozilla/5.0 (compatible; AlejandrIA/1.0; +research)"}
        resp = await safe_get(url, quien="fetch_url", headers=headers, timeout=15.0)
        if resp.status_code != 200:
            return f"No se pudo obtener la URL (HTTP {resp.status_code})."
        ct = resp.headers.get("content-type", "")
        if "text/html" not in ct and "text/plain" not in ct:
            return f"Tipo de contenido no soportado: {ct}"
        text = re.sub(r"<script[^>]*>.*?</script>", "", resp.text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"<style[^>]*>.*?</style>", "", text, flags=re.DOTALL | re.IGNORECASE)
        text = re.sub(r"<[^>]+>", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        if len(text) > 8000:
            text = text[:8000] + "… [truncado]"
        return text or "No se pudo extraer texto."
    except EgressBlocked as exc:
        # Al modelo se le dice que se ha bloqueado, no por qué: el motivo describe
        # la red interna y su respuesta acaba en el contexto. El detalle queda en
        # el log, que es donde lo necesita quien lo diagnostique.
        logger.warning("fetch_url bloqueado: %s — %s", url, exc)
        return "Destino no permitido por la política de egress."
    except Exception as exc:
        return f"Error al obtener URL: {exc}"


# ── Deterministic web search with real URL extraction ─────────────────────────

async def ddg_search_with_urls(query: str, max_results: int = 5) -> List[Dict[str, str]]:
    """
    Multi-source academic search: arXiv API + Wikipedia API.

    DuckDuckGo HTML is unreliable in automated/corporate environments (returns
    a 202 redirect to the homepage instead of results).  arXiv and Wikipedia
    both provide stable, free, key-less JSON/Atom APIs that return quality
    content for scientific and general knowledge queries.

    Returns list of {"title": str, "url": str, "snippet": str}.
    """
    results: List[Dict[str, str]] = []
    if not query.strip():
        return results

    # ── arXiv API (academic papers) ───────────────────────────────────────────
    try:
        import xml.etree.ElementTree as ET
        arxiv_url = "https://export.arxiv.org/api/query"
        arxiv_params = {
            "search_query": f"all:{query}",
            "max_results": max(2, max_results // 2 + 1),
            "sortBy": "relevance",
        }
        # Sin `verify=False`: un proxy con inspección TLS se arregla instalando su
        # CA en el sistema (o `SSL_CERT_FILE`), no apagando la verificación para
        # todo el mundo y para siempre.
        r = await safe_get(arxiv_url, quien="arxiv", params=arxiv_params, timeout=8.0)
        if r.status_code == 200:
            ns = {"atom": "http://www.w3.org/2005/Atom"}
            root = ET.fromstring(r.text)
            for entry in root.findall("atom:entry", ns):
                if len(results) >= max_results:
                    break
                title_el = entry.find("atom:title", ns)
                summary_el = entry.find("atom:summary", ns)
                link_el = entry.find("atom:id", ns)
                title = (title_el.text or "").strip().replace("\n", " ")
                snippet = (summary_el.text or "").strip().replace("\n", " ")[:300]
                url = (link_el.text or "").strip()
                if url and title:
                    results.append({"title": title, "url": url, "snippet": snippet})
        else:
            logger.warning("arXiv returned HTTP %s", r.status_code)
    except Exception as exc:
        logger.warning("arXiv search failed for '%s': %s — %s", query, type(exc).__name__, exc)

    # ── Wikipedia API (encyclopedic context) ─────────────────────────────────
    if len(results) < max_results:
        try:
            wiki_url = "https://en.wikipedia.org/w/api.php"
            wiki_params = {
                "action": "query",
                "list": "search",
                "srsearch": query,
                "format": "json",
                "srlimit": max_results - len(results),
                "srprop": "snippet",
            }
            # Wikipedia ToS requires a descriptive User-Agent with contact info
            wiki_headers = {
                "User-Agent": "AlejandrIA-Magazine/0.1 (scientific article generation; contact@alejandria.local)"
            }
            r = await safe_get(
                wiki_url, quien="wikipedia", params=wiki_params,
                headers=wiki_headers, timeout=8.0,
            )
            if r.status_code == 200:
                data = r.json()
                for item in data.get("query", {}).get("search", []):
                    if len(results) >= max_results:
                        break
                    title = item.get("title", "")
                    snippet = re.sub(r"<[^>]+>", "", item.get("snippet", "")).strip()
                    page_url = f"https://en.wikipedia.org/wiki/{title.replace(' ', '_')}"
                    results.append({"title": title, "url": page_url, "snippet": snippet})
            else:
                logger.warning("Wikipedia search returned HTTP %s", r.status_code)
        except Exception as exc:
            logger.warning("Wikipedia search failed for '%s': %s — %s", query, type(exc).__name__, exc)

    return results

