// Generated by GitHub Copilot
import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { projectsApi } from '../api/projects';

export const useProjectStore = create(
  persist(
    (set, get) => ({
      /** Currently active project (full object) */
      activeProject: null,
      /** All accessible projects */
      projects: [],
      isLoading: false,
      error: null,

      /** Fetch all projects from the server. */
      fetchProjects: async () => {
        set({ isLoading: true, error: null });
        try {
          const projects = await projectsApi.list();
          set({ projects, isLoading: false });
        } catch (err) {
          set({ isLoading: false, error: err?.response?.data?.detail || 'Error al cargar proyectos' });
        }
      },

      /** Create a new project and add it to the list. */
      createProject: async (name, description, use_case_type) => {
        set({ isLoading: true, error: null });
        try {
          const project = await projectsApi.create({ name, description, use_case_type });
          set(state => ({ projects: [...state.projects, project], isLoading: false }));
          return { ok: true, project };
        } catch (err) {
          const msg = err?.response?.data?.detail || 'Error al crear proyecto';
          set({ isLoading: false, error: msg });
          return { ok: false, error: msg };
        }
      },

      /** Set the active project. */
      selectProject: (project) => set({ activeProject: project }),

      /** Remove a project from the list. */
      deleteProject: async (id) => {
        try {
          await projectsApi.remove(id);
          set(state => ({
            projects: state.projects.filter(p => p.id !== id),
            activeProject: state.activeProject?.id === id ? null : state.activeProject,
          }));
          return { ok: true };
        } catch (err) {
          return { ok: false, error: err?.response?.data?.detail || 'Error al eliminar proyecto' };
        }
      },

      /** Clear project state on logout. */
      clearProjects: () => set({ activeProject: null, projects: [], error: null }),
    }),
    {
      name: 'project-store',
      partialize: (state) => ({ activeProject: state.activeProject }),
    }
  )
);
