// Generated by GitHub Copilot
import api from './client';

export const projectsApi = {
  /** List all accessible projects (system + user-owned). */
  list: () => api.get('/api/v1/projects').then(r => r.data),

  /** Create a new user project. */
  create: (data) => api.post('/api/v1/projects', data).then(r => r.data),

  /** Get a single project by ID. */
  get: (id) => api.get(`/api/v1/projects/${id}`).then(r => r.data),

  /** Delete a user-owned project. */
  remove: (id) => api.delete(`/api/v1/projects/${id}`).then(r => r.data),
};
