// Generated by GitHub Copilot
import React, { useEffect, useState, useCallback, useRef } from 'react';
import { AsyncState, EmptyState } from '../../../platform/components/ui/states';
import { mensajeDeCarga } from '../../../platform/api/errors';
import { useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import { ChevronLeft, ChevronRight, BookOpen, Loader, Bell, LogOut, Shield } from 'lucide-react';
import { useAuthStore } from '../../../platform/store/authStore';
import api from '../../../platform/api/client';
import toast from 'react-hot-toast';

/**
 * Reader page for authenticated lector users.
 * Shows published articles as a full-screen slideshow with notification bell.
 */
export default function LectorPage() {
  const { user, logout } = useAuthStore();
  const navigate = useNavigate();

  const [articles, setArticles] = useState([]);
  const [current, setCurrent] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Notifications
  const [notifications, setNotifications] = useState([]);
  const [showNotifs, setShowNotifs] = useState(false);
  const notifRef = useRef(null);

  const fetchNotifications = useCallback(async () => {
    try {
      const { data } = await api.get('/api/v1/notifications');
      setNotifications(data);
    // mejor-esfuerzo: esto se reintenta cada 30 s; avisar en cada vuelta
    // sería peor que el propio fallo.
    } catch { /* ignore */ }
  }, []);

  useEffect(() => {
    if (user?.role === 'publico') return;
    fetchNotifications();
    const id = setInterval(fetchNotifications, 30000);
    return () => clearInterval(id);
  }, [fetchNotifications, user?.role]);

  useEffect(() => {
    const handler = (e) => {
      if (notifRef.current && !notifRef.current.contains(e.target)) setShowNotifs(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const unread = notifications.filter(n => !n.read).length;

  // Fetch published articles (authenticated, scoped to assigned project if any)
  const cargarArticulos = useCallback(() => {
    setLoading(true);
    setError(null);
    const fallo = (err) => setError(mensajeDeCarga(err, 'No se pudieron cargar los artículos'));
    if (user?.role === 'publico') {
      api.get('/api/v1/magazine')
        .then(r => setArticles(r.data ?? []))
        .catch(fallo)
        .finally(() => setLoading(false));
    } else {
      const params = user?.assigned_project_id ? { project_id: user.assigned_project_id } : {};
      api.get('/api/v1/articles', { params })
        .then(r => setArticles(r.data?.items ?? []))
        .catch(fallo)
        .finally(() => setLoading(false));
    }
  }, [user]);

  useEffect(() => { cargarArticulos(); }, [cargarArticulos]);

  const prev = useCallback(() => setCurrent(c => (c - 1 + articles.length) % articles.length), [articles.length]);
  const next = useCallback(() => setCurrent(c => (c + 1) % articles.length), [articles.length]);

  useEffect(() => {
    const handleKey = (e) => {
      if (e.key === 'ArrowRight') next();
      if (e.key === 'ArrowLeft') prev();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [next, prev]);

  const handleLogout = () => {
    logout();
    toast.success('Sesión cerrada');
    navigate('/auth');
  };

  const article = articles[current];
  const initials = user?.full_name?.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase() || 'U';

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-base)', display: 'flex', flexDirection: 'column' }}>
      {/* Topbar */}
      <header style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '12px 28px',
        borderBottom: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)',
        flexShrink: 0,
      }}>
        {/* Brand */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <BookOpen size={20} style={{ color: 'var(--brand-primary)' }} />
          <span style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)' }}>
            Alej<span style={{ color: 'var(--brand-primary)' }}>andrIA</span> Magazine
          </span>
        </div>

        {/* Pagination count */}
        {!loading && articles.length > 0 && (
          <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
            {current + 1} / {articles.length}
          </span>
        )}

        {/* User actions */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          {/* Bell */}
          {user?.role !== 'publico' && (
            <div style={{ position: 'relative' }} ref={notifRef}>
              <button
                className="btn btn-ghost btn-icon"
                style={{ position: 'relative' }}
                onClick={() => setShowNotifs(v => !v)}
                aria-label={`Notificaciones${unread ? ` (${unread} sin leer)` : ''}`}
              >
                <Bell size={18} />
                {unread > 0 && (
                  <span style={{
                    position: 'absolute', top: 3, right: 3,
                    background: 'var(--error)', color: 'var(--neutral-00)',
                    borderRadius: '50%', width: 16, height: 16,
                    fontSize: 10, fontWeight: 700,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                  }}>{unread > 9 ? '9+' : unread}</span>
                )}
              </button>
              {showNotifs && (
                <div style={{
                  position: 'absolute', right: 0, top: 'calc(100% + 8px)',
                  width: 300, background: 'var(--bg-elevated)',
                  border: '1px solid var(--border-default)', borderRadius: 'var(--radius-lg)',
                  boxShadow: '0 8px 24px rgba(0,0,0,0.4)', zIndex: 200, overflow: 'hidden',
                }}>
                  <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border-default)', fontWeight: 600, fontSize: 'var(--font-size-sm)' }}>
                    Notificaciones {unread > 0 && <span style={{ color: 'var(--error)' }}>({unread} nuevas)</span>}
                  </div>
                  <div style={{ maxHeight: 320, overflowY: 'auto' }}>
                    {notifications.length === 0 ? (
                      <div style={{ padding: '24px 16px', textAlign: 'center', color: 'var(--text-muted)', fontSize: 'var(--font-size-sm)' }}>
                        Sin notificaciones
                      </div>
                    ) : notifications.map(n => (
                      <div key={n.id} style={{
                        padding: '12px 16px',
                        background: n.read ? 'transparent' : 'rgba(99,102,241,0.08)',
                        borderBottom: '1px solid var(--border-default)',
                      }}>
                        <div style={{ fontWeight: n.read ? 400 : 600, fontSize: 'var(--font-size-sm)', marginBottom: 2 }}>
                          {!n.read && <span style={{ display: 'inline-block', width: 7, height: 7, borderRadius: '50%', background: 'var(--brand)', marginRight: 6, verticalAlign: 'middle' }} />}
                          {n.title}
                        </div>
                        <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>{n.message}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* User info */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <div className="avatar">{initials}</div>
            <div style={{ lineHeight: 1.3 }}>
              <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 600 }}>{user?.full_name}</div>
              <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>{user?.role}</div>
            </div>
          </div>

          {/* Logout */}
          <button className="btn btn-ghost btn-icon" onClick={handleLogout} title="Cerrar sesión" aria-label="Cerrar sesión">
            <LogOut size={17} />
          </button>
        </div>
      </header>

      {/* Slideshow */}
      <div style={{ flex: 1, display: 'flex', alignItems: 'stretch', position: 'relative', overflow: 'hidden' }}>
        {articles.length > 1 && (
          <button onClick={prev} aria-label="Artículo anterior" style={{
            position: 'absolute', left: 16, top: '50%', transform: 'translateY(-50%)',
            zIndex: 10, background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
            borderRadius: '50%', width: 40, height: 40, display: 'flex', alignItems: 'center',
            justifyContent: 'center', cursor: 'pointer', color: 'var(--text-primary)',
          }}>
            <ChevronLeft size={20} />
          </button>
        )}

        <div style={{ flex: 1, display: 'flex', justifyContent: 'center', padding: '40px 80px', overflowY: 'auto' }}>
          <AsyncState
            loading={loading}
            error={error}
            isEmpty={articles.length === 0}
            onRetry={cargarArticulos}
            loadingLabel="Cargando artículos…"
            empty={(
              <EmptyState
                icon={<BookOpen size={28} />}
                title="No hay artículos publicados aún"
                description="Aquí aparecerán los artículos en cuanto se publiquen."
              />
            )}
          >
            {(
            <article style={{ maxWidth: 780, width: '100%' }}>
              <div style={{ marginBottom: 32, paddingBottom: 24, borderBottom: '1px solid var(--border-subtle)' }}>
                {article.scientific_format && article.scientific_format !== 'none' && (
                  <span className="badge badge-approved" style={{ marginBottom: 12, display: 'inline-flex' }}>
                    {article.scientific_format.toUpperCase()}
                  </span>
                )}
                <h1 style={{ fontSize: '1.8rem', fontWeight: 700, color: 'var(--text-primary)', lineHeight: 1.3, margin: '8px 0 12px' }}>
                  {article.title}
                </h1>
                <div style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>
                  Publicado el {new Date(article.published_at || article.created_at).toLocaleDateString('es-ES', { day: '2-digit', month: 'long', year: 'numeric' })}
                  {article.author_name && <span style={{ marginLeft: 12 }}>· {article.author_name}</span>}
                </div>
              </div>
              <div className="markdown-body">
                <ReactMarkdown>{article.body}</ReactMarkdown>
              </div>
            </article>
            )}
          </AsyncState>
        </div>

        {articles.length > 1 && (
          <button onClick={next} aria-label="Artículo siguiente" style={{
            position: 'absolute', right: 16, top: '50%', transform: 'translateY(-50%)',
            zIndex: 10, background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
            borderRadius: '50%', width: 40, height: 40, display: 'flex', alignItems: 'center',
            justifyContent: 'center', cursor: 'pointer', color: 'var(--text-primary)',
          }}>
            <ChevronRight size={20} />
          </button>
        )}
      </div>

      {/* Dot pagination */}
      {articles.length > 1 && (
        <div style={{ display: 'flex', justifyContent: 'center', gap: 8, padding: '16px 0', background: 'var(--bg-surface)', borderTop: '1px solid var(--border-subtle)' }}>
          {articles.map((_, i) => (
            <button key={i} onClick={() => setCurrent(i)} aria-label={`Ir al artículo ${i + 1}`} style={{
              width: i === current ? 20 : 8, height: 8, borderRadius: 4,
              background: i === current ? 'var(--brand-primary)' : 'var(--border-default)',
              border: 'none', cursor: 'pointer', padding: 0,
              transition: 'width 0.2s, background 0.2s',
            }} />
          ))}
        </div>
      )}
    </div>
  );
}
