"""agent_run_steps: traza de explicabilidad por paso (SPEC-014 / T9.1 / AC1)

Una fila por paso de agente de cada ejecución, con lo que hace falta para
explicar **por qué** salió lo que salió: modelo y parámetros, resumen de entrada
y salida, las fuentes RAG que se recuperaron de verdad (con `doc_id`,
`chunk_ids` y score), tokens, latencia y la decisión con su motivo.

Dos detalles de las claves ajenas, ambos deliberados:

* `run_id` es `SET NULL` — si la retención purga un `agent_run`, la traza del
  paso sigue explicando lo que pasó hasta que le toque a ella.
* `article_id` es `CASCADE` — borrar el artículo sí se lleva su traza: sin el
  artículo, la explicación de cómo se generó no describe nada.

Revision ID: 0004_agent_run_steps
Revises: 0003_audit_log
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_agent_run_steps'
down_revision: Union[str, Sequence[str], None] = '0003_audit_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('input_digest', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('rag_sources', sa.JSON(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_steps_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_agent_run_steps_article_step', ['article_id', 'step_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_steps_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_steps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_steps_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_steps_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_run_steps_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_status'))
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_correlation_id'))
        batch_op.drop_index('ix_agent_run_steps_article_step')
        batch_op.drop_index(batch_op.f('ix_agent_run_steps_article_id'))

    op.drop_table('agent_run_steps')
    # ### end Alembic commands ###
