"""Unified LLM dispatcher.

Routes generation calls to the configured provider based on settings.LLM_PROVIDER.
All agent adapters and routers should use call_llm() / get_default_model()
instead of talking to a provider directly.

Supported providers
-------------------
* ``anthropic`` — Claude via the official ``anthropic`` SDK (AsyncAnthropic).
* ``ollama``    — on-prem via Ollama HTTP API.
* ``openai``    — OpenAI Python SDK; also works with any OpenAI-compatible server
                 (Azure OpenAI, vLLM, Groq, LM Studio, etc.) via OPENAI_BASE_URL.
"""

# Generated by GitHub Copilot

import asyncio
import logging
import time
import random
from pathlib import Path
from typing import Optional, AsyncGenerator, Awaitable, Callable, TypeVar

import httpx

logger = logging.getLogger(__name__)

T = TypeVar("T")


class TransientLLMError(RuntimeError):
    """A retryable LLM failure: connection refused, timeout, 5xx, empty response.

    Distinguished from a plain ``RuntimeError`` (permanent: auth failure, unknown
    model, bad request) so the retry layer knows whether another attempt is worth it.
    """


def _retry_params() -> tuple[int, float, float]:
    """Read retry tuning from settings, tolerating older configs without the keys."""
    from app.core.config import settings
    max_retries = int(getattr(settings, "LLM_MAX_RETRIES", 3) or 0)
    base_delay = float(getattr(settings, "LLM_RETRY_BASE_DELAY", 1.0) or 0.0)
    max_delay = float(getattr(settings, "LLM_RETRY_MAX_DELAY", 10.0) or 0.0)
    return max_retries, base_delay, max_delay


def _is_retryable_status(status_code) -> bool:
    """True for HTTP statuses worth retrying: 429 (rate limit) and 5xx (server)."""
    try:
        code = int(status_code)
    except (TypeError, ValueError):
        return False
    return code == 429 or code >= 500


def _backoff_delay(attempt: int, base_delay: float, max_delay: float) -> float:
    """Exponential backoff with full jitter for retry ``attempt`` (0-indexed)."""
    raw = min(base_delay * (2 ** attempt), max_delay)
    # Full jitter avoids thundering-herd retries when several agents fail at once.
    return random.uniform(0.0, raw)


async def _retry_async(factory: Callable[[], Awaitable[T]], *, what: str) -> T:
    """Run an async LLM call, retrying transient failures with backoff.

    ``factory`` must return a *fresh* awaitable on each call (so each attempt is a
    new request). Permanent errors (non-``TransientLLMError``) propagate immediately.
    """
    max_retries, base_delay, max_delay = _retry_params()
    attempt = 0
    while True:
        try:
            return await factory()
        except TransientLLMError as exc:
            if attempt >= max_retries:
                logger.error("%s failed after %d attempt(s): %s", what, attempt + 1, exc)
                raise
            delay = _backoff_delay(attempt, base_delay, max_delay)
            logger.warning(
                "%s transient error (attempt %d/%d): %s — retrying in %.1fs",
                what, attempt + 1, max_retries + 1, exc, delay,
            )
            await asyncio.sleep(delay)
            attempt += 1


async def _retry_stream(
    factory: Callable[[], AsyncGenerator[str, None]], *, what: str
) -> AsyncGenerator[str, None]:
    """Retry a streaming LLM call, but only while no token has been emitted yet.

    Connection-level failures (the common "all connection attempts failed") happen
    before any token, so retrying is safe. Once tokens have started flowing we must
    NOT restart — that would duplicate already-streamed content — so a mid-stream
    error propagates unchanged.
    """
    max_retries, base_delay, max_delay = _retry_params()
    attempt = 0
    while True:
        produced = False
        try:
            async for token in factory():
                produced = True
                yield token
            return
        except TransientLLMError as exc:
            if produced or attempt >= max_retries:
                if produced:
                    logger.error("%s broke mid-stream — not retrying to avoid duplication: %s", what, exc)
                else:
                    logger.error("%s failed after %d attempt(s): %s", what, attempt + 1, exc)
                raise
            delay = _backoff_delay(attempt, base_delay, max_delay)
            logger.warning(
                "%s transient error (attempt %d/%d): %s — retrying in %.1fs",
                what, attempt + 1, max_retries + 1, exc, delay,
            )
            await asyncio.sleep(delay)
            attempt += 1


def get_default_model() -> str:
    """Return the default model name for the currently configured LLM provider.

    Use this instead of hard-coding ``settings.OLLAMA_MODEL`` in agent code so
    that the correct default is returned regardless of which provider is active.
    """
    from app.core.config import settings  # late import — avoids circular deps

    provider = settings.LLM_PROVIDER.lower()
    if provider == "anthropic":
        return settings.ANTHROPIC_MODEL
    if provider == "openai":
        return settings.OPENAI_MODEL
    return settings.OLLAMA_MODEL


# ---------------------------------------------------------------------------
# Per-agent, provider-aware model resolution (SPEC-023 / T12.3)
# ---------------------------------------------------------------------------

# Prefix → provider namespace. Used to decide whether a model id "belongs" to the
# active provider, so a legacy Ollama value (e.g. seeded in the DB) never gets sent
# to Anthropic/OpenAI as if it were one of their models.
_NAMESPACE_PREFIXES = (
    ("anthropic", ("claude",)),
    ("openai", ("gpt", "o1", "o3", "o4", "chatgpt", "text-")),
)


def _model_namespace(model: str) -> str:
    """Best-effort provider namespace of a model id (defaults to ``ollama``)."""
    m = (model or "").strip().lower()
    for provider, prefixes in _NAMESPACE_PREFIXES:
        if m.startswith(prefixes):
            return provider
    # On-prem tags (mistral:7b, llama3.2:3b, qwen2.5, gemma, phi, …) live here.
    return "ollama"


def _namespace_matches(model: str, provider: str) -> bool:
    return _model_namespace(model) == provider


def _load_agent_frontmatter(agent_name: str) -> dict:
    """Parse the YAML frontmatter of ``<agent_name>.agent.md`` (empty dict if absent).

    La ruta la resuelve `platform/projects/profiles` (T8.4). El import es local
    para no crear un ciclo: el *loader* de proyectos valida capacidades y estas
    acaban importando este módulo.
    """
    from app.platform.projects.profiles import find as find_profile

    filepath = find_profile(agent_name)
    if filepath is None:
        return {}
    try:
        raw = filepath.read_text(encoding="utf-8")
    except Exception:
        return {}
    if raw.startswith("---"):
        parts = raw.split("---", 2)
        if len(parts) >= 3:
            try:
                import yaml
                return yaml.safe_load(parts[1]) or {}
            except Exception:
                return {}
    return {}


def resolve_agent_model(agent_name: str, agent_settings: Optional[dict] = None) -> str:
    """Resolve the model for ``agent_name`` under the active provider (SPEC-023/AC3).

    Cascade, most specific first:

    1. ``agent_settings[agent].model`` — explicit per-run/UI override, honored only
       if its namespace matches the active provider (so a legacy Ollama value
       seeded in the DB doesn't hijack a Claude/OpenAI deployment).
    2. ``.agent.md`` ``models[<provider>]`` — provider-aware per-agent default.
    3. ``.agent.md`` legacy ``model`` — only if its namespace matches the provider.
    4. :func:`get_default_model` — the provider's global default.

    This keeps the per-agent tiering working for Claude *and* Ollama without a
    provider switch silently falling back to a single default for every agent.
    """
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    cfg = (agent_settings or {}).get(agent_name, {}) or {}

    # 1. Explicit override (namespace-guarded against stale/legacy values).
    override = cfg.get("model")
    if isinstance(override, str) and override.strip() and _namespace_matches(override, provider):
        return override.strip()

    frontmatter = _load_agent_frontmatter(agent_name)

    # 2. Provider-keyed map from the .agent.md.
    models_map = frontmatter.get("models")
    if isinstance(models_map, dict):
        mapped = models_map.get(provider)
        if isinstance(mapped, str) and mapped.strip():
            return mapped.strip()

    # 3. Legacy single model, only if it belongs to the active provider.
    legacy = frontmatter.get("model")
    if isinstance(legacy, str) and legacy.strip() and _namespace_matches(legacy, provider):
        return legacy.strip()

    # 4. Provider default.
    return get_default_model()


def _record_usage(provider: str, model: str, entrada, salida) -> None:
    """Anotar tokens consumidos (SPEC-019/T5.2 y SPEC-014/T9.1).

    Se llama desde cada proveedor porque es el único sitio donde se conocen: la
    respuesta de la API los trae, y `call_llm` solo ve el texto ya extraído.
    Van a dos sitios con propósitos distintos: a las métricas, que son agregadas y
    operativas, y a la traza del paso en curso, que es por ejecución y sirve para
    explicar **esta** ejecución.

    Nunca lanza — medir no puede tumbar una generación.
    """
    try:
        from app.platform.metrics import observe_llm_tokens

        observe_llm_tokens(
            provider=provider, model=model,
            input_tokens=int(entrada or 0) or None,
            output_tokens=int(salida or 0) or None,
        )
    except Exception:  # pragma: no cover - defensivo
        pass
    try:
        from app.platform.explainability import record_tokens

        record_tokens(entrada, salida)
    except Exception:  # pragma: no cover - defensivo
        pass


async def call_llm(
    prompt: str,
    *,
    model: Optional[str] = None,
    timeout: float = 60.0,
    system_prompt: Optional[str] = None,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> str:
    """Call the configured LLM provider and return the generated text.

    Args:
        prompt: The user / task prompt.
        model: Model override. ``None`` uses the provider's configured default.
        timeout: HTTP / SDK request timeout in seconds.
        system_prompt: Optional system message (used only with OpenAI Chat API).
        keep_alive: Ollama keep-alive seconds. Use 0 to unload the model
            immediately after the call (frees VRAM/RAM). -1 = Ollama default.
        num_ctx: Override the model context window size. Smaller values
            reduce KV-cache RAM. ``None`` uses the model's default.

    Returns:
        The generated text, stripped of leading/trailing whitespace.

    Raises:
        RuntimeError: On any network, API or parsing error.
    """
    from app.core.config import settings
    from app.platform.metrics import observe_llm_call

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()
    _inicio = time.perf_counter()

    async def _medido(coro_factory):
        """Cronometra la llamada y anota el resultado (SPEC-019/T5.2).

        Envuelve el dispatcher entero para que la latencia incluya los reintentos:
        es lo que de verdad espera quien llama, y un proveedor que solo responde al
        tercer intento tiene que verse lento, no sano.
        """
        estado = "error"
        try:
            resultado = await coro_factory()
            estado = "ok"
            return resultado
        finally:
            observe_llm_call(
                provider=provider, model=resolved_model,
                duration=time.perf_counter() - _inicio, status=estado,
            )

    if provider == "anthropic":
        return await _medido(lambda: _retry_async(
            lambda: _call_anthropic(
                prompt=prompt,
                model=resolved_model,
                timeout=timeout,
                system_prompt=system_prompt,
            ),
            what=f"Anthropic call ({resolved_model})",
        ))

    if provider == "openai":
        return await _medido(lambda: _retry_async(
            lambda: _call_openai(
                prompt=prompt,
                model=resolved_model,
                timeout=timeout,
                system_prompt=system_prompt,
            ),
            what=f"OpenAI call ({resolved_model})",
        ))

    # Default: Ollama
    return await _medido(lambda: _retry_async(
        lambda: _call_ollama(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            keep_alive=keep_alive,
            num_ctx=num_ctx,
        ),
        what=f"Ollama call ({resolved_model})",
    ))


async def call_llm_stream(
    prompt: str,
    *,
    model: Optional[str] = None,
    timeout: float = 60.0,
    system_prompt: Optional[str] = None,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> AsyncGenerator[str, None]:
    """Call the configured LLM provider and yield the generated tokens."""
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()

    if provider == "anthropic":
        stream_factory = lambda: _call_anthropic_stream(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            system_prompt=system_prompt,
        )
        what = f"Anthropic stream ({resolved_model})"
    elif provider == "openai":
        stream_factory = lambda: _call_openai_stream(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            system_prompt=system_prompt,
        )
        what = f"OpenAI stream ({resolved_model})"
    else:
        stream_factory = lambda: _call_ollama_stream(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            keep_alive=keep_alive,
            num_ctx=num_ctx,
        )
        what = f"Ollama stream ({resolved_model})"

    async for token in _retry_stream(stream_factory, what=what):
        yield token


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


async def _call_ollama(
    prompt: str,
    model: str,
    timeout: float,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> str:
    """Send a generation request to the local Ollama /api/generate endpoint."""
    from app.core.config import settings

    payload: dict = {"model": model, "prompt": prompt, "stream": False}
    options: dict = {}
    if num_ctx is not None:
        options["num_ctx"] = num_ctx
    if options:
        payload["options"] = options
    if keep_alive != -1:
        payload["keep_alive"] = keep_alive

    try:
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=timeout) as client:
            response = await client.post("/api/generate", json=payload)
            if response.status_code != 200:
                # 5xx / 429 are transient (server busy, model loading); 4xx is a
                # permanent client error (bad model name, malformed request).
                err = f"Ollama returned HTTP {response.status_code}: {response.text[:200]}"
                if response.status_code >= 500 or response.status_code == 429:
                    raise TransientLLMError(err)
                raise RuntimeError(err)
            datos = response.json()
            text = datos.get("response", "").strip()
            if not text:
                # Often a model still warming up — worth another attempt.
                raise TransientLLMError("Ollama returned an empty response")
            _record_usage("ollama", model, datos.get("prompt_eval_count"), datos.get("eval_count"))
            return text
    except httpx.TimeoutException as exc:
        raise TransientLLMError(
            f"Ollama request timed out after {timeout:.0f}s — "
            "consider a faster model or a higher timeout"
        ) from exc
    except httpx.RequestError as exc:
        raise TransientLLMError(f"Ollama unavailable: {exc}") from exc


async def _call_openai(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
) -> str:
    """Send a chat completion request via the OpenAI Python SDK.

    Works with the official OpenAI API and any OpenAI-compatible server
    (Azure OpenAI, vLLM, Groq, LM Studio) by setting OPENAI_BASE_URL.

    Security note: OPENAI_API_KEY is read from settings (env var / config.yaml)
    and never logged or exposed in error messages.
    """
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError(
            "openai package is not installed. "
            "Run: pip install 'openai>=1.0.0'"
        ) from exc

    client_kwargs: dict = {"timeout": timeout}

    # Use placeholder key when pointing to a local server that doesn't need auth
    client_kwargs["api_key"] = settings.OPENAI_API_KEY or "sk-placeholder"

    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    try:
        client = AsyncOpenAI(**client_kwargs)
        try:
            response = await client.chat.completions.create(
                model=model,
                messages=messages,
            )
        finally:
            await client.close()

        text = (response.choices[0].message.content or "").strip()
        if not text:
            raise TransientLLMError("OpenAI returned an empty response")
        uso = getattr(response, "usage", None)
        _record_usage("openai", model,
                      getattr(uso, "prompt_tokens", None), getattr(uso, "completion_tokens", None))
        return text

    except AuthenticationError as exc:
        # Permanent — retrying with the same bad key is pointless.
        raise RuntimeError(
            "OpenAI authentication failed — check OPENAI_API_KEY"
        ) from exc
    except APIConnectionError as exc:
        raise TransientLLMError(f"Could not reach the OpenAI endpoint: {exc}") from exc
    except APIError as exc:
        err = f"OpenAI API error (status {exc.status_code}): {exc.message}"
        if _is_retryable_status(exc.status_code):
            raise TransientLLMError(err) from exc
        raise RuntimeError(err) from exc
    except (TransientLLMError, RuntimeError):
        raise
    except Exception as exc:
        raise RuntimeError(f"OpenAI call failed: {type(exc).__name__}: {exc}") from exc


async def _call_ollama_stream(
    prompt: str,
    model: str,
    timeout: float,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> AsyncGenerator[str, None]:
    """Send a generation request with streaming enabled to local Ollama /api/generate."""
    from app.core.config import settings
    import json

    payload: dict = {"model": model, "prompt": prompt, "stream": True}
    options: dict = {}
    if num_ctx is not None:
        options["num_ctx"] = num_ctx
    if options:
        payload["options"] = options
    if keep_alive != -1:
        payload["keep_alive"] = keep_alive

    try:
        limits = httpx.Timeout(timeout=timeout, connect=5.0)
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=limits) as client:
            async with client.stream("POST", "/api/generate", json=payload) as response:
                if response.status_code != 200:
                    error_text = await response.aread()
                    err = (
                        f"Ollama stream returned HTTP {response.status_code}: "
                        f"{error_text[:200].decode(errors='replace')}"
                    )
                    if response.status_code >= 500 or response.status_code == 429:
                        raise TransientLLMError(err)
                    raise RuntimeError(err)
                async for line in response.aiter_lines():
                    if line:
                        try:
                            chunk = json.loads(line)
                            token = chunk.get("response", "")
                            if token:
                                yield token
                            # El chunk final (`done`) trae el recuento de tokens.
                            if chunk.get("done"):
                                _record_usage(
                                    "ollama", model,
                                    chunk.get("prompt_eval_count"), chunk.get("eval_count"),
                                )
                        except Exception:
                            pass
    except httpx.TimeoutException as exc:
        raise TransientLLMError(f"Ollama stream request timed out after {timeout:.0f}s") from exc
    except httpx.RequestError as exc:
        raise TransientLLMError(f"Ollama stream unavailable: {exc}") from exc


async def _call_openai_stream(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
) -> AsyncGenerator[str, None]:
    """Send a chat completion request with streaming enabled via the OpenAI Python SDK."""
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError("openai package is not installed.") from exc

    client_kwargs: dict = {"timeout": timeout}
    client_kwargs["api_key"] = settings.OPENAI_API_KEY or "sk-placeholder"

    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    try:
        client = AsyncOpenAI(**client_kwargs)
        try:
            # Sin `stream_options={"include_usage": True}` a propósito: esta ruta
            # admite `OPENAI_BASE_URL`, y las pasarelas compatibles con OpenAI a
            # menudo rechazan ese parámetro. Una llamada rota es peor que una
            # métrica ausente, así que el streaming de OpenAI queda sin recuento
            # de tokens (la latencia sí se mide, como en el resto).
            stream = await client.chat.completions.create(
                model=model,
                messages=messages,
                stream=True
            )
            async for chunk in stream:
                token = chunk.choices[0].delta.content or ""
                if token:
                    yield token
        finally:
              await client.close()

    except AuthenticationError as exc:
        raise RuntimeError("OpenAI authentication failed — check OPENAI_API_KEY") from exc
    except APIConnectionError as exc:
        raise TransientLLMError(f"Could not reach the OpenAI endpoint: {exc}") from exc
    except APIError as exc:
        err = f"OpenAI API error (status {exc.status_code}): {exc.message}"
        if _is_retryable_status(exc.status_code):
            raise TransientLLMError(err) from exc
        raise RuntimeError(err) from exc
    except (TransientLLMError, RuntimeError):
        raise
    except Exception as exc:
        raise RuntimeError(f"OpenAI stream failed: {type(exc).__name__}: {exc}") from exc


# ---------------------------------------------------------------------------
# Anthropic (Claude) — official ``anthropic`` SDK (AsyncAnthropic)
# ---------------------------------------------------------------------------


def _anthropic_text(message) -> str:
    """Concatenate the text of the ``text`` content blocks of a Claude message.

    A Claude response is a list of typed content blocks; with extended thinking
    there may also be ``thinking`` blocks. We only want the visible text.
    """
    parts = []
    for block in getattr(message, "content", None) or []:
        if getattr(block, "type", None) == "text":
            parts.append(getattr(block, "text", "") or "")
    return "".join(parts).strip()


def _anthropic_client_kwargs(api_key: str, timeout: float) -> dict:
    from app.core.config import settings

    kwargs: dict = {"api_key": api_key, "timeout": timeout}
    if settings.ANTHROPIC_BASE_URL:
        kwargs["base_url"] = settings.ANTHROPIC_BASE_URL
    return kwargs


def _require_anthropic_key() -> str:
    """Return the configured Anthropic API key or raise a *permanent* error.

    Lazy validation (SPEC-023/AC5): a missing key does not abort start-up; the
    first LLM call fails here with a non-retryable ``RuntimeError`` that never
    echoes key material.
    """
    from app.core.config import settings

    api_key = settings.ANTHROPIC_API_KEY
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY no está configurada — define la variable de entorno "
            "ANTHROPIC_API_KEY (o el bloque anthropic de config.yaml) para el "
            "proveedor 'anthropic', o cambia LLM_PROVIDER a 'ollama'/'openai'."
        )
    return api_key


def _import_anthropic():
    """Import the official SDK symbols, mapping a missing package to a clear error."""
    try:
        from anthropic import (  # type: ignore
            AsyncAnthropic,
            APIError,
            APIConnectionError,
            APIStatusError,
            AuthenticationError,
            RateLimitError,
        )
    except ImportError as exc:  # pragma: no cover - exercised only without the pkg
        raise RuntimeError(
            "El paquete 'anthropic' no está instalado. "
            "Ejecuta: pip install 'anthropic>=0.40.0'"
        ) from exc
    return (
        AsyncAnthropic,
        APIError,
        APIConnectionError,
        APIStatusError,
        AuthenticationError,
        RateLimitError,
    )


def _classify_anthropic_error(exc, errors) -> Exception:
    """Map an Anthropic SDK error to Transient (retryable) vs permanent RuntimeError.

    ``errors`` is the tuple returned by ``_import_anthropic`` so the class
    identities match the (possibly mocked) SDK in use. The auth branch never
    interpolates the exception, so no API key can leak into the message.
    """
    (_Client, APIError, APIConnectionError, APIStatusError,
     AuthenticationError, RateLimitError) = errors

    if isinstance(exc, AuthenticationError):
        return RuntimeError("Anthropic authentication failed — revisa ANTHROPIC_API_KEY")
    if isinstance(exc, RateLimitError):
        return TransientLLMError(f"Anthropic rate limit (429): {exc}")
    if isinstance(exc, APIConnectionError):
        return TransientLLMError(f"No se pudo contactar con el endpoint de Anthropic: {exc}")
    if isinstance(exc, (APIStatusError, APIError)):
        status = getattr(exc, "status_code", None)
        err = f"Anthropic API error (status {status})"
        if _is_retryable_status(status):
            return TransientLLMError(err)
        return RuntimeError(err)
    # Unknown SDK error — treat as permanent (do not mask real bugs by retrying).
    return RuntimeError(f"Anthropic call failed: {type(exc).__name__}: {exc}")


async def _call_anthropic(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
    max_tokens: Optional[int] = None,
) -> str:
    """Send a single generation request to Claude via the official SDK.

    Maps ``system_prompt`` to the top-level ``system`` parameter (Claude does not
    use a system *turn*) and fixes ``max_tokens`` (required by the API).
    """
    from app.core.config import settings

    api_key = _require_anthropic_key()
    symbols = _import_anthropic()
    AsyncAnthropic = symbols[0]

    resolved_max = max_tokens or getattr(settings, "ANTHROPIC_MAX_TOKENS", 4096)
    create_kwargs: dict = {
        "model": model,
        "max_tokens": resolved_max,
        "messages": [{"role": "user", "content": prompt}],
    }
    if system_prompt:
        create_kwargs["system"] = system_prompt

    client = AsyncAnthropic(**_anthropic_client_kwargs(api_key, timeout))
    try:
        message = await client.messages.create(**create_kwargs)
    except Exception as exc:  # noqa: BLE001 - re-raised as Transient/Runtime below
        raise _classify_anthropic_error(exc, symbols) from exc
    finally:
        await client.close()

    text = _anthropic_text(message)
    if not text:
        raise TransientLLMError("Anthropic devolvió una respuesta vacía")
    uso = getattr(message, "usage", None)
    _record_usage("anthropic", model,
                  getattr(uso, "input_tokens", None), getattr(uso, "output_tokens", None))
    return text


async def _call_anthropic_stream(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
    max_tokens: Optional[int] = None,
) -> AsyncGenerator[str, None]:
    """Stream a generation request from Claude, yielding text deltas."""
    from app.core.config import settings

    api_key = _require_anthropic_key()
    symbols = _import_anthropic()
    AsyncAnthropic = symbols[0]

    resolved_max = max_tokens or getattr(settings, "ANTHROPIC_MAX_TOKENS", 4096)
    create_kwargs: dict = {
        "model": model,
        "max_tokens": resolved_max,
        "messages": [{"role": "user", "content": prompt}],
    }
    if system_prompt:
        create_kwargs["system"] = system_prompt

    client = AsyncAnthropic(**_anthropic_client_kwargs(api_key, timeout))
    try:
        async with client.messages.stream(**create_kwargs) as stream:
            async for token in stream.text_stream:
                if token:
                    yield token
            # El mensaje final del stream trae el uso acumulado.
            try:
                final = await stream.get_final_message()
                uso = getattr(final, "usage", None)
                _record_usage("anthropic", model,
                              getattr(uso, "input_tokens", None), getattr(uso, "output_tokens", None))
            except Exception:  # pragma: no cover - el uso es opcional
                pass
    except Exception as exc:  # noqa: BLE001 - re-raised as Transient/Runtime below
        raise _classify_anthropic_error(exc, symbols) from exc
    finally:
        await client.close()


def _to_anthropic_tools(tool_schemas: list) -> list:
    """Convert OpenAI/Ollama-style function schemas to Anthropic tool schemas.

    Anthropic tools are ``{name, description, input_schema}``. OpenAI/Ollama pass
    ``{"type": "function", "function": {name, description, parameters}}``. Native
    Anthropic schemas (already carrying ``input_schema``) pass through unchanged.
    """
    converted: list = []
    for tool in tool_schemas or []:
        if not isinstance(tool, dict):
            continue
        if "function" in tool:  # OpenAI / Ollama style
            fn = tool["function"] or {}
            converted.append({
                "name": fn.get("name", ""),
                "description": fn.get("description", ""),
                "input_schema": fn.get("parameters") or {"type": "object", "properties": {}},
            })
        elif "input_schema" in tool:  # already Anthropic-native
            converted.append(tool)
        elif "name" in tool:
            converted.append({
                "name": tool.get("name", ""),
                "description": tool.get("description", ""),
                "input_schema": tool.get("parameters") or {"type": "object", "properties": {}},
            })
    return converted


# ---------------------------------------------------------------------------
# Agentic tool-calling loop
# ---------------------------------------------------------------------------

import json as _json
from typing import Callable, Awaitable

async def call_llm_with_tools(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    *,
    model: Optional[str] = None,
    timeout: float = 120.0,
    max_iterations: int = 6,
) -> str:
    """Run an agentic tool-calling loop until the model returns a plain text response.

    The loop:
      1. Sends system + user messages plus tool definitions.
      2. If the model calls a tool → executes it → appends result → repeats.
      3. Returns the first plain-text response (no tool calls), or raises after
         ``max_iterations`` rounds without a final answer.

    Supports both providers:
      * Ollama  — POST /api/chat with ``tools`` (llama3.2, mistral, …)
      * OpenAI  — AsyncOpenAI chat.completions.create() with ``tools``
    """
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()

    if provider == "anthropic":
        return await _tool_loop_anthropic(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            tool_schemas=tool_schemas,
            tool_executor=tool_executor,
            model=resolved_model,
            timeout=timeout,
            max_iterations=max_iterations,
        )

    if provider == "openai":
        return await _tool_loop_openai(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            tool_schemas=tool_schemas,
            tool_executor=tool_executor,
            model=resolved_model,
            timeout=timeout,
            max_iterations=max_iterations,
        )
    return await _tool_loop_ollama(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        tool_schemas=tool_schemas,
        tool_executor=tool_executor,
        model=resolved_model,
        timeout=timeout,
        max_iterations=max_iterations,
    )


async def _tool_loop_ollama(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    model: str,
    timeout: float,
    max_iterations: int,
) -> str:
    """Agentic loop using Ollama /api/chat endpoint."""
    from app.core.config import settings

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=timeout) as client:
        for iteration in range(max_iterations):
            payload: dict = {
                "model": model,
                "messages": messages,
                "stream": False,
            }
            if tool_schemas:
                payload["tools"] = tool_schemas

            async def _post_chat() -> dict:
                try:
                    resp = await client.post("/api/chat", json=payload)
                except httpx.TimeoutException as exc:
                    raise TransientLLMError(f"Ollama /api/chat timed out after {timeout:.0f}s") from exc
                except httpx.RequestError as exc:
                    raise TransientLLMError(f"Ollama /api/chat unavailable: {exc}") from exc
                if resp.status_code != 200:
                    err = f"Ollama /api/chat returned HTTP {resp.status_code}: {resp.text[:200]}"
                    if resp.status_code >= 500 or resp.status_code == 429:
                        raise TransientLLMError(err)
                    raise RuntimeError(err)
                return resp.json()

            data = await _retry_async(_post_chat, what=f"Ollama tool call ({model})")
            msg = data.get("message", {})
            tool_calls = msg.get("tool_calls") or []

            if not tool_calls:
                # Model returned a plain-text response — we're done
                return (msg.get("content") or "").strip()

            # Append assistant message with the tool calls
            messages.append({"role": "assistant", "content": msg.get("content", ""), "tool_calls": tool_calls})

            # Execute each tool call and append results
            for tc in tool_calls:
                fn = tc.get("function", {})
                name = fn.get("name", "")
                args = fn.get("arguments") or {}
                if isinstance(args, str):
                    try:
                        args = _json.loads(args)
                    except Exception:
                        args = {}
                logger.info("Tool call: %s(%s)", name, args)
                result = await tool_executor(name, args)
                messages.append({"role": "tool", "content": result})

    raise RuntimeError(f"Tool loop did not converge after {max_iterations} iterations")


async def _tool_loop_openai(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    model: str,
    timeout: float,
    max_iterations: int,
) -> str:
    """Agentic loop using the OpenAI Python SDK."""
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError("openai package not installed") from exc

    client_kwargs: dict = {
        "timeout": timeout,
        "api_key": settings.OPENAI_API_KEY or "sk-placeholder",
    }
    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    client = AsyncOpenAI(**client_kwargs)

    async def _create(kwargs: dict):
        try:
            return await client.chat.completions.create(**kwargs)
        except AuthenticationError as exc:
            raise RuntimeError("OpenAI authentication failed — check OPENAI_API_KEY") from exc
        except APIConnectionError as exc:
            raise TransientLLMError(f"Could not reach the OpenAI endpoint: {exc}") from exc
        except APIError as exc:
            err = f"OpenAI API error (status {exc.status_code}): {exc.message}"
            if _is_retryable_status(exc.status_code):
                raise TransientLLMError(err) from exc
            raise RuntimeError(err) from exc

    try:
        for iteration in range(max_iterations):
            kwargs: dict = {"model": model, "messages": messages}
            if tool_schemas:
                kwargs["tools"] = tool_schemas
                kwargs["tool_choice"] = "auto"

            response = await _retry_async(
                lambda k=kwargs: _create(k), what=f"OpenAI tool call ({model})"
            )
            choice = response.choices[0]
            assistant_msg = choice.message
            tool_calls = assistant_msg.tool_calls or []

            if not tool_calls:
                return (assistant_msg.content or "").strip()

            # Append assistant turn (with tool_calls)
            messages.append(assistant_msg.model_dump())

            # Execute each tool and append results
            for tc in tool_calls:
                fn = tc.function
                args = {}
                try:
                    args = _json.loads(fn.arguments or "{}")
                except Exception:
                    pass
                logger.info("Tool call: %s(%s)", fn.name, args)
                result = await tool_executor(fn.name, args)
                messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "content": result,
                })
    finally:
        await client.close()

    raise RuntimeError(f"Tool loop did not converge after {max_iterations} iterations")


async def _tool_loop_anthropic(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    model: str,
    timeout: float,
    max_iterations: int,
) -> str:
    """Agentic loop using the official Anthropic SDK (Claude tool use)."""
    from app.core.config import settings

    api_key = _require_anthropic_key()
    symbols = _import_anthropic()
    AsyncAnthropic = symbols[0]

    anthropic_tools = _to_anthropic_tools(tool_schemas)
    resolved_max = getattr(settings, "ANTHROPIC_MAX_TOKENS", 4096)
    messages: list = [{"role": "user", "content": user_prompt}]

    client = AsyncAnthropic(**_anthropic_client_kwargs(api_key, timeout))

    async def _create() -> "object":
        kwargs: dict = {
            "model": model,
            "max_tokens": resolved_max,
            "messages": messages,
        }
        if system_prompt:
            kwargs["system"] = system_prompt
        if anthropic_tools:
            kwargs["tools"] = anthropic_tools
        try:
            return await client.messages.create(**kwargs)
        except Exception as exc:  # noqa: BLE001 - re-raised as Transient/Runtime below
            raise _classify_anthropic_error(exc, symbols) from exc

    try:
        for _iteration in range(max_iterations):
            message = await _retry_async(_create, what=f"Anthropic tool call ({model})")

            if getattr(message, "stop_reason", None) != "tool_use":
                # No tool calls — plain-text answer, we're done.
                return _anthropic_text(message)

            # Echo the assistant turn (its content blocks) back into the history.
            messages.append({"role": "assistant", "content": message.content})

            # Execute each tool_use block and return the results in a single user turn.
            tool_results: list = []
            for block in getattr(message, "content", None) or []:
                if getattr(block, "type", None) != "tool_use":
                    continue
                name = getattr(block, "name", "")
                args = getattr(block, "input", None) or {}
                if isinstance(args, str):
                    try:
                        args = _json.loads(args)
                    except Exception:
                        args = {}
                logger.info("Tool call: %s(%s)", name, args)
                result = await tool_executor(name, args)
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": getattr(block, "id", None),
                    "content": result,
                })
            messages.append({"role": "user", "content": tool_results})
    finally:
        await client.close()

    raise RuntimeError(f"Tool loop did not converge after {max_iterations} iterations")
