"""Unified LLM dispatcher.

Routes generation calls to the configured provider (Ollama or OpenAI-compatible)
based on settings.LLM_PROVIDER. All agent adapters and routers should use
call_llm() / get_default_model() instead of talking to Ollama directly.

Supported providers
-------------------
* ``ollama``  — on-prem via Ollama HTTP API (default)
* ``openai``  — OpenAI Python SDK; also works with any OpenAI-compatible server
               (Azure OpenAI, vLLM, Groq, LM Studio, etc.) via OPENAI_BASE_URL.
"""

# Generated by GitHub Copilot

import logging
from typing import Optional, AsyncGenerator

import httpx

logger = logging.getLogger(__name__)


def get_default_model() -> str:
    """Return the default model name for the currently configured LLM provider.

    Use this instead of hard-coding ``settings.OLLAMA_MODEL`` in agent code so
    that the correct default is returned regardless of which provider is active.
    """
    from app.core.config import settings  # late import — avoids circular deps

    if settings.LLM_PROVIDER.lower() == "openai":
        return settings.OPENAI_MODEL
    return settings.OLLAMA_MODEL


async def call_llm(
    prompt: str,
    *,
    model: Optional[str] = None,
    timeout: float = 60.0,
    system_prompt: Optional[str] = None,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> str:
    """Call the configured LLM provider and return the generated text.

    Args:
        prompt: The user / task prompt.
        model: Model override. ``None`` uses the provider's configured default.
        timeout: HTTP / SDK request timeout in seconds.
        system_prompt: Optional system message (used only with OpenAI Chat API).
        keep_alive: Ollama keep-alive seconds. Use 0 to unload the model
            immediately after the call (frees VRAM/RAM). -1 = Ollama default.
        num_ctx: Override the model context window size. Smaller values
            reduce KV-cache RAM. ``None`` uses the model's default.

    Returns:
        The generated text, stripped of leading/trailing whitespace.

    Raises:
        RuntimeError: On any network, API or parsing error.
    """
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()

    if provider == "openai":
        return await _call_openai(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            system_prompt=system_prompt,
        )

    # Default: Ollama
    return await _call_ollama(
        prompt=prompt,
        model=resolved_model,
        timeout=timeout,
        keep_alive=keep_alive,
        num_ctx=num_ctx,
    )


async def call_llm_stream(
    prompt: str,
    *,
    model: Optional[str] = None,
    timeout: float = 60.0,
    system_prompt: Optional[str] = None,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> AsyncGenerator[str, None]:
    """Call the configured LLM provider and yield the generated tokens."""
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()

    if provider == "openai":
        async for token in _call_openai_stream(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            system_prompt=system_prompt,
        ):
            yield token
    else:
        async for token in _call_ollama_stream(
            prompt=prompt,
            model=resolved_model,
            timeout=timeout,
            keep_alive=keep_alive,
            num_ctx=num_ctx,
        ):
            yield token


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


async def _call_ollama(
    prompt: str,
    model: str,
    timeout: float,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> str:
    """Send a generation request to the local Ollama /api/generate endpoint."""
    from app.core.config import settings

    payload: dict = {"model": model, "prompt": prompt, "stream": False}
    options: dict = {}
    if num_ctx is not None:
        options["num_ctx"] = num_ctx
    if options:
        payload["options"] = options
    if keep_alive != -1:
        payload["keep_alive"] = keep_alive

    try:
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=timeout) as client:
            response = await client.post("/api/generate", json=payload)
            if response.status_code != 200:
                raise RuntimeError(
                    f"Ollama returned HTTP {response.status_code}: {response.text[:200]}"
                )
            text = response.json().get("response", "").strip()
            if not text:
                raise RuntimeError("Ollama returned an empty response")
            return text
    except httpx.TimeoutException as exc:
        raise RuntimeError(
            f"Ollama request timed out after {timeout:.0f}s — "
            "consider a faster model or a higher timeout"
        ) from exc
    except httpx.RequestError as exc:
        raise RuntimeError(f"Ollama unavailable: {exc}") from exc


async def _call_openai(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
) -> str:
    """Send a chat completion request via the OpenAI Python SDK.

    Works with the official OpenAI API and any OpenAI-compatible server
    (Azure OpenAI, vLLM, Groq, LM Studio) by setting OPENAI_BASE_URL.

    Security note: OPENAI_API_KEY is read from settings (env var / config.yaml)
    and never logged or exposed in error messages.
    """
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError(
            "openai package is not installed. "
            "Run: pip install 'openai>=1.0.0'"
        ) from exc

    client_kwargs: dict = {"timeout": timeout}

    # Use placeholder key when pointing to a local server that doesn't need auth
    client_kwargs["api_key"] = settings.OPENAI_API_KEY or "sk-placeholder"

    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    try:
        client = AsyncOpenAI(**client_kwargs)
        try:
            response = await client.chat.completions.create(
                model=model,
                messages=messages,
            )
        finally:
            await client.close()

        text = (response.choices[0].message.content or "").strip()
        if not text:
            raise RuntimeError("OpenAI returned an empty response")
        return text

    except AuthenticationError as exc:
        raise RuntimeError(
            "OpenAI authentication failed — check OPENAI_API_KEY"
        ) from exc
    except APIConnectionError as exc:
        raise RuntimeError(f"Could not reach the OpenAI endpoint: {exc}") from exc
    except APIError as exc:
        raise RuntimeError(f"OpenAI API error (status {exc.status_code}): {exc.message}") from exc
    except RuntimeError:
        raise
    except Exception as exc:
        raise RuntimeError(f"OpenAI call failed: {type(exc).__name__}: {exc}") from exc


async def _call_ollama_stream(
    prompt: str,
    model: str,
    timeout: float,
    keep_alive: int = -1,
    num_ctx: Optional[int] = None,
) -> AsyncGenerator[str, None]:
    """Send a generation request with streaming enabled to local Ollama /api/generate."""
    from app.core.config import settings
    import json

    payload: dict = {"model": model, "prompt": prompt, "stream": True}
    options: dict = {}
    if num_ctx is not None:
        options["num_ctx"] = num_ctx
    if options:
        payload["options"] = options
    if keep_alive != -1:
        payload["keep_alive"] = keep_alive

    try:
        limits = httpx.Timeout(timeout=timeout, connect=5.0)
        async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=limits) as client:
            async with client.stream("POST", "/api/generate", json=payload) as response:
                if response.status_code != 200:
                    error_text = await response.aread()
                    raise RuntimeError(
                        f"Ollama stream returned HTTP {response.status_code}: {error_text[:200].decode(errors='replace')}"
                    )
                async for line in response.aiter_lines():
                    if line:
                        try:
                            chunk = json.loads(line)
                            token = chunk.get("response", "")
                            if token:
                                yield token
                        except Exception:
                            pass
    except httpx.TimeoutException as exc:
        raise RuntimeError(f"Ollama stream request timed out after {timeout:.0f}s") from exc
    except httpx.RequestError as exc:
        raise RuntimeError(f"Ollama stream unavailable: {exc}") from exc


async def _call_openai_stream(
    prompt: str,
    model: str,
    timeout: float,
    system_prompt: Optional[str] = None,
) -> AsyncGenerator[str, None]:
    """Send a chat completion request with streaming enabled via the OpenAI Python SDK."""
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError("openai package is not installed.") from exc

    client_kwargs: dict = {"timeout": timeout}
    client_kwargs["api_key"] = settings.OPENAI_API_KEY or "sk-placeholder"

    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    messages.append({"role": "user", "content": prompt})

    try:
        client = AsyncOpenAI(**client_kwargs)
        try:
            stream = await client.chat.completions.create(
                model=model,
                messages=messages,
                stream=True
            )
            async for chunk in stream:
                token = chunk.choices[0].delta.content or ""
                if token:
                    yield token
        finally:
              await client.close()

    except AuthenticationError as exc:
        raise RuntimeError("OpenAI authentication failed — check OPENAI_API_KEY") from exc
    except APIConnectionError as exc:
        raise RuntimeError(f"Could not reach the OpenAI endpoint: {exc}") from exc
    except APIError as exc:
        raise RuntimeError(f"OpenAI API error (status {exc.status_code}): {exc.message}") from exc
    except Exception as exc:
        raise RuntimeError(f"OpenAI stream failed: {type(exc).__name__}: {exc}") from exc


# ---------------------------------------------------------------------------
# Agentic tool-calling loop
# ---------------------------------------------------------------------------

import json as _json
from typing import Callable, Awaitable

async def call_llm_with_tools(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    *,
    model: Optional[str] = None,
    timeout: float = 120.0,
    max_iterations: int = 6,
) -> str:
    """Run an agentic tool-calling loop until the model returns a plain text response.

    The loop:
      1. Sends system + user messages plus tool definitions.
      2. If the model calls a tool → executes it → appends result → repeats.
      3. Returns the first plain-text response (no tool calls), or raises after
         ``max_iterations`` rounds without a final answer.

    Supports both providers:
      * Ollama  — POST /api/chat with ``tools`` (llama3.2, mistral, …)
      * OpenAI  — AsyncOpenAI chat.completions.create() with ``tools``
    """
    from app.core.config import settings

    provider = settings.LLM_PROVIDER.lower()
    resolved_model = model or get_default_model()

    if provider == "openai":
        return await _tool_loop_openai(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            tool_schemas=tool_schemas,
            tool_executor=tool_executor,
            model=resolved_model,
            timeout=timeout,
            max_iterations=max_iterations,
        )
    return await _tool_loop_ollama(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        tool_schemas=tool_schemas,
        tool_executor=tool_executor,
        model=resolved_model,
        timeout=timeout,
        max_iterations=max_iterations,
    )


async def _tool_loop_ollama(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    model: str,
    timeout: float,
    max_iterations: int,
) -> str:
    """Agentic loop using Ollama /api/chat endpoint."""
    from app.core.config import settings

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    async with httpx.AsyncClient(base_url=settings.OLLAMA_BASE_URL, timeout=timeout) as client:
        for iteration in range(max_iterations):
            payload: dict = {
                "model": model,
                "messages": messages,
                "stream": False,
            }
            if tool_schemas:
                payload["tools"] = tool_schemas

            resp = await client.post("/api/chat", json=payload)
            if resp.status_code != 200:
                raise RuntimeError(f"Ollama /api/chat returned HTTP {resp.status_code}: {resp.text[:200]}")

            data = resp.json()
            msg = data.get("message", {})
            tool_calls = msg.get("tool_calls") or []

            if not tool_calls:
                # Model returned a plain-text response — we're done
                return (msg.get("content") or "").strip()

            # Append assistant message with the tool calls
            messages.append({"role": "assistant", "content": msg.get("content", ""), "tool_calls": tool_calls})

            # Execute each tool call and append results
            for tc in tool_calls:
                fn = tc.get("function", {})
                name = fn.get("name", "")
                args = fn.get("arguments") or {}
                if isinstance(args, str):
                    try:
                        args = _json.loads(args)
                    except Exception:
                        args = {}
                logger.info("Tool call: %s(%s)", name, args)
                result = await tool_executor(name, args)
                messages.append({"role": "tool", "content": result})

    raise RuntimeError(f"Tool loop did not converge after {max_iterations} iterations")


async def _tool_loop_openai(
    system_prompt: str,
    user_prompt: str,
    tool_schemas: list,
    tool_executor: Callable[[str, dict], Awaitable[str]],
    model: str,
    timeout: float,
    max_iterations: int,
) -> str:
    """Agentic loop using the OpenAI Python SDK."""
    from app.core.config import settings

    try:
        from openai import AsyncOpenAI, APIError, APIConnectionError, AuthenticationError
    except ImportError as exc:
        raise RuntimeError("openai package not installed") from exc

    client_kwargs: dict = {
        "timeout": timeout,
        "api_key": settings.OPENAI_API_KEY or "sk-placeholder",
    }
    if settings.OPENAI_BASE_URL:
        client_kwargs["base_url"] = settings.OPENAI_BASE_URL

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]

    client = AsyncOpenAI(**client_kwargs)
    try:
        for iteration in range(max_iterations):
            kwargs: dict = {"model": model, "messages": messages}
            if tool_schemas:
                kwargs["tools"] = tool_schemas
                kwargs["tool_choice"] = "auto"

            response = await client.chat.completions.create(**kwargs)
            choice = response.choices[0]
            assistant_msg = choice.message
            tool_calls = assistant_msg.tool_calls or []

            if not tool_calls:
                return (assistant_msg.content or "").strip()

            # Append assistant turn (with tool_calls)
            messages.append(assistant_msg.model_dump())

            # Execute each tool and append results
            for tc in tool_calls:
                fn = tc.function
                args = {}
                try:
                    args = _json.loads(fn.arguments or "{}")
                except Exception:
                    pass
                logger.info("Tool call: %s(%s)", fn.name, args)
                result = await tool_executor(fn.name, args)
                messages.append({
                    "role": "tool",
                    "tool_call_id": tc.id,
                    "content": result,
                })
    finally:
        await client.close()

    raise RuntimeError(f"Tool loop did not converge after {max_iterations} iterations")
