// Generated by GitHub Copilot
import React, { useCallback, useEffect, useRef, useState } from 'react';
import {
  ChevronDown, Database, FileText, Loader, Save, Sliders, Trash2, Upload, X,
} from 'lucide-react';
import { agentsApi } from '../../api/agents';
import toast from 'react-hot-toast';

const TABS = [
  { id: 'md', icon: 'Markdown', label: 'Markdown' },
  { id: 'params', icon: 'Parametros', label: 'Parámetros' },
  { id: 'rag', icon: 'RAG', label: 'RAG' },
];

/** Render a compact model selector used by the agent editor. */
function ModelSelector({ value, onChange, models }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const handler = (event) => {
      if (ref.current && !ref.current.contains(event.target)) {
        setOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <button
        type="button"
        className="input"
        onClick={() => setOpen((current) => !current)}
        style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer', textAlign: 'left' }}
        aria-haspopup="listbox"
        aria-expanded={open}
      >
        <span>{value || 'Selecciona modelo'}</span>
        <ChevronDown size={14} style={{ flexShrink: 0, color: 'var(--text-muted)' }} />
      </button>

      {open && (
        <ul
          role="listbox"
          style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 50,
            background: 'var(--bg-card)', border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)', listStyle: 'none', margin: '4px 0 0',
            padding: '4px 0', maxHeight: 200, overflowY: 'auto',
            boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
          }}
        >
          {models.map((modelName) => (
            <li
              key={modelName}
              role="option"
              aria-selected={modelName === value}
              onClick={() => {
                onChange(modelName);
                setOpen(false);
              }}
              style={{
                padding: '7px 14px', cursor: 'pointer', fontSize: 'var(--font-size-sm)',
                background: modelName === value ? 'var(--bg-overlay)' : 'transparent',
                color: modelName === value ? 'var(--brand-primary)' : 'var(--text-primary)',
              }}
            >
              {modelName}
            </li>
          ))}
          <li style={{ borderTop: '1px solid var(--border-subtle)', padding: '4px 8px' }}>
            <input
              className="input"
              placeholder="Otro modelo..."
              style={{ fontSize: 'var(--font-size-xs)', padding: '4px 8px' }}
              aria-label="Nombre de modelo personalizado"
              onKeyDown={(event) => {
                if (event.key === 'Enter' && event.target.value.trim()) {
                  onChange(event.target.value.trim());
                  setOpen(false);
                }
              }}
            />
          </li>
        </ul>
      )}
    </div>
  );
}

/** Render the RAG documents panel for a single agent profile. */
function RagTab({ agentName, ragCollection, ragChunkSize, ragChunkOverlap, onCollectionChange, ragDocIds = [], onDocIdsChange }) {
  const [docs, setDocs] = useState(null);
  const [libraryCollections, setLibraryCollections] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [lastIndexed, setLastIndexed] = useState(null);
  const [loadError, setLoadError] = useState('');
  // Auto-expand the saved collection when there are persisted doc selections
  const [expandedCollection, setExpandedCollection] = useState(
    ragDocIds.length > 0 ? ragCollection : null
  );
  const inputRef = useRef(null);

  const loadDocs = useCallback(async () => {
    setLoadError('');
    try {
      const response = await agentsApi.getRagDocuments(agentName);
      setDocs(response.documents || []);
    } catch (error) {
      setLoadError(error?.response?.data?.detail || 'No se pudo consultar Qdrant');
      setDocs([]);
    }
  }, [agentName]);

  const loadLibrary = useCallback(async () => {
    try {
      const data = await agentsApi.getLibraryDocs();
      setLibraryCollections(data.collections || []);
    } catch {
      // library unavailable — non-critical
    }
  }, []);

  useEffect(() => {
    loadDocs();
    loadLibrary();
  }, [loadDocs, loadLibrary]);

  /** Upload one or more files and refresh the indexed document list. */
  const handleFiles = async (files) => {
    for (const file of files) {
      setUploading(true);
      try {
        const response = await agentsApi.uploadRagDocument(agentName, file, {
          ragCollection,
          ragChunkSize,
          ragChunkOverlap,
        });
        setLastIndexed(response);
        toast.success(`${file.name} indexado (${response.chunks} chunks)`);
      } catch (error) {
        toast.error(error?.response?.data?.detail || `Error al subir ${file.name}`);
      } finally {
        setUploading(false);
      }
    }
    await loadDocs();
  };

  /** Delete a single indexed document from the agent collection. */
  const handleDelete = async (docId, filename) => {
    if (!globalThis.confirm(`¿Eliminar "${filename}" del índice RAG?`)) {
      return;
    }
    try {
      await agentsApi.deleteRagDocument(agentName, docId);
      toast.success('Documento eliminado');
      setDocs((current) => current.filter((item) => item.doc_id !== docId));
    } catch {
      toast.error('Error al eliminar');
    }
  };

  const ownDocsContent = (() => {
    if (docs === null) return <div style={{ minHeight: 24 }} aria-hidden="true" />;
    if (loadError) return <div style={{ color: 'var(--warning)', fontSize: 'var(--font-size-sm)' }}>{loadError}</div>;
    if (docs.length === 0) return (
      <div style={{ color: 'var(--text-muted)', fontSize: 'var(--font-size-sm)', fontStyle: 'italic' }}>
        Sin documentos indexados para este agente aún.
      </div>
    );
    return (
      <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
        {docs.map((doc) => (
          <li
            key={doc.doc_id}
            style={{
              display: 'flex', alignItems: 'center', gap: 'var(--space-3)',
              padding: 'var(--space-2) var(--space-3)',
              background: 'var(--bg-overlay)', borderRadius: 'var(--radius-sm)',
            }}
          >
            <FileText size={14} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
            <span style={{ flex: 1, fontSize: 'var(--font-size-sm)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
              {doc.filename}
            </span>
            <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', flexShrink: 0 }}>
              {doc.chunks} chunks
            </span>
            <button
              className="btn btn-ghost btn-sm btn-icon"
              onClick={() => handleDelete(doc.doc_id, doc.filename)}
              aria-label={`Eliminar ${doc.filename} del RAG`}
            >
              <Trash2 size={13} style={{ color: 'var(--error)' }} />
            </button>
          </li>
        ))}
      </ul>
    );
  })();

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }}>

      {/* ── Active collection ── */}
      <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', display: 'flex', gap: 'var(--space-4)', flexWrap: 'wrap' }}>
        <span>Colección activa: <strong style={{ color: 'var(--text-secondary)' }}>{ragCollection || 'rag_docs'}</strong></span>
        <span>Chunk size: <strong style={{ color: 'var(--text-secondary)' }}>{ragChunkSize}</strong></span>
        <span>Overlap: <strong style={{ color: 'var(--text-secondary)' }}>{ragChunkOverlap}</strong></span>
      </div>

      {/* ── Library picker ── */}
      {libraryCollections.length > 0 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
          <div style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            Usar colección de la biblioteca
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 'var(--space-2)' }}>
            {libraryCollections.map((col) => {
              const active = col.name === ragCollection;
              return (
                <button
                  key={col.name}
                  type="button"
                  onClick={() => {
                    onCollectionChange?.(col.name);
                    onDocIdsChange?.([]);
                    setExpandedCollection(expandedCollection === col.name ? null : col.name);
                  }}
                  style={{
                    padding: '4px 12px',
                    borderRadius: 'var(--radius-sm)',
                    fontSize: 'var(--font-size-xs)',
                    fontWeight: 500,
                    border: `1px solid ${active ? 'var(--brand-primary)' : 'var(--border-subtle)'}`,
                    background: active ? 'var(--brand-primary-light)' : 'var(--bg-elevated)',
                    color: active ? 'var(--brand-primary)' : 'var(--text-secondary)',
                    cursor: 'pointer',
                    transition: 'all 0.12s',
                  }}
                  aria-pressed={active}
                  aria-label={`Usar colección ${col.name} (${col.documents.length} docs)`}
                >
                  {col.name}
                  <span style={{ marginLeft: 6, opacity: 0.65 }}>{col.documents.length}</span>
                </button>
              );
            })}
          </div>

          {/* ── Per-document selector ── */}
          {expandedCollection && (() => {
            const col = libraryCollections.find((c) => c.name === expandedCollection);
            if (!col || col.documents.length === 0) return null;
            return (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginTop: 'var(--space-1)' }}>
                <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
                  Elige documentos específicos (vacío = toda la colección):
                </div>
                {col.documents.map((docItem) => {
                  const selected = ragDocIds.includes(docItem.doc_id);
                  return (
                    <label
                      key={docItem.doc_id}
                      style={{
                        display: 'flex', alignItems: 'center', gap: 'var(--space-2)',
                        padding: '4px 8px',
                        borderRadius: 'var(--radius-sm)',
                        background: selected ? 'var(--brand-primary-light)' : 'var(--bg-overlay)',
                        cursor: 'pointer',
                        fontSize: 'var(--font-size-xs)',
                      }}
                    >
                      <input
                        type="checkbox"
                        checked={selected}
                        onChange={() => {
                          const next = selected
                            ? ragDocIds.filter((id) => id !== docItem.doc_id)
                            : [...ragDocIds, docItem.doc_id];
                          onDocIdsChange?.(next);
                        }}
                        aria-label={`Incluir documento ${docItem.filename}`}
                      />
                      <FileText size={12} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
                      <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                        {docItem.filename}
                      </span>
                      <span style={{ color: 'var(--text-muted)', flexShrink: 0 }}>{docItem.chunks} chunks</span>
                    </label>
                  );
                })}
                {ragDocIds.length > 0 && (
                  <button
                    type="button"
                    className="btn btn-ghost btn-sm"
                    onClick={() => onDocIdsChange?.([])}
                    style={{ alignSelf: 'flex-start', fontSize: 'var(--font-size-xs)' }}
                  >
                    Limpiar selección (usar toda la colección)
                  </button>
                )}
              </div>
            );
          })()}

          <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
            {ragDocIds.length > 0
              ? `El agente buscará solo en ${ragDocIds.length} documento(s) seleccionado(s).`
              : 'Al seleccionar una colección, el agente consultará todos sus vectores como contexto RAG.'}
          </div>
        </div>
      )}

      {/* ── Upload new doc ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
        <div style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Subir nuevo documento
        </div>

        {lastIndexed && (
          <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--success)' }}>
            Indexado: {lastIndexed.filename} · {lastIndexed.chunks} chunks en "{lastIndexed.collection}"
          </div>
        )}

        <div
          role="button"
          tabIndex={0}
          aria-label="Zona de carga de archivos RAG"
          onDragOver={(event) => { event.preventDefault(); setDragging(true); }}
          onDragLeave={() => setDragging(false)}
          onDrop={(event) => {
            event.preventDefault();
            setDragging(false);
            const files = Array.from(event.dataTransfer.files).filter((file) =>
              ['.txt', '.md', '.pdf'].some((ext) => file.name.toLowerCase().endsWith(ext))
            );
            if (files.length) handleFiles(files);
            else toast.error('Solo .txt, .md y .pdf son aceptados');
          }}
          onClick={() => inputRef.current?.click()}
          onKeyDown={(event) => {
            if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); inputRef.current?.click(); }
          }}
          style={{
            border: `2px dashed ${dragging ? 'var(--brand-primary)' : 'var(--border-subtle)'}`,
            borderRadius: 'var(--radius-md)', padding: 'var(--space-5)',
            textAlign: 'center', cursor: 'pointer',
            background: dragging ? 'var(--bg-overlay)' : 'transparent',
            transition: 'all 0.15s',
          }}
        >
          {uploading ? (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
              <Loader size={20} style={{ color: 'var(--brand-primary)' }} />
              <span style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>Indexando...</span>
            </div>
          ) : (
            <>
              <Upload size={20} style={{ color: 'var(--text-muted)', marginBottom: 6 }} />
              <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 500 }}>Arrastra archivos o haz clic</div>
              <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>
                .txt · .md · .pdf — máx. 10 MB
              </div>
            </>
          )}
          <input
            ref={inputRef}
            type="file"
            accept=".txt,.md,.pdf"
            multiple
            style={{ display: 'none' }}
            aria-label="Seleccionar archivo RAG"
            onChange={(event) => { if (event.target.files?.length) handleFiles(Array.from(event.target.files)); }}
          />
        </div>
      </div>

      {/* ── Own indexed docs (only shown when not using library collection) ── */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
        <div style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Documentos propios del agente
        </div>
        {ragDocIds.length > 0 ? (
          <div style={{
            display: 'flex', alignItems: 'flex-start', gap: 'var(--space-2)',
            padding: 'var(--space-3)',
            background: 'var(--brand-primary-light)',
            borderRadius: 'var(--radius-sm)',
            border: '1px solid var(--brand-primary)',
            fontSize: 'var(--font-size-sm)',
            color: 'var(--brand-primary)',
          }}>
            <span style={{ fontWeight: 600, flexShrink: 0 }}>✓ Activo:</span>
            <span>
              El agente usará {ragDocIds.length === 1 ? 'el documento seleccionado' : `${ragDocIds.length} documentos seleccionados`} de la colección <strong>{ragCollection}</strong>. Los documentos propios no se usarán mientras haya una selección de biblioteca activa.
            </span>
          </div>
        ) : ownDocsContent}
      </div>

    </div>
  );
}



/** Edit an agent profile and persist changes through the backend API. */
export function AgentEditorModal({ agent, isBuiltin, models, onClose, onSaved, onDeleted }) {
  const [tab, setTab] = useState('md');
  const [mdContent, setMdContent] = useState(agent.content || `# ${agent.slug || agent.name}\n\nDescripción.\n`);
  const [params, setParams] = useState(() => {
    // rag_doc_ids may arrive as a JSON string from the API when stored as TEXT in SQLite
    let ragDocIds = agent.rag_doc_ids || [];
    if (typeof ragDocIds === 'string') {
      try { ragDocIds = JSON.parse(ragDocIds); } catch { ragDocIds = []; }
    }
    let agentTools = agent.tools || [];
    if (typeof agentTools === 'string') {
      try { agentTools = JSON.parse(agentTools); } catch { agentTools = []; }
    }
    return {
      model: agent.model || 'llama3.2:1b',
      temperature: agent.temperature ?? 0.7,
      prompt_template: agent.prompt_template || '',
      rag_enabled: agent.rag_enabled ?? false,
      graph_rag_enabled: agent.graph_rag_enabled ?? false,
      semantic_search_enabled: agent.semantic_search_enabled ?? false,
      rag_collection: agent.rag_collection || 'rag_docs',
      rag_chunk_size: agent.rag_chunk_size ?? 500,
      rag_chunk_overlap: agent.rag_chunk_overlap ?? 50,
      rag_doc_ids: ragDocIds,
      tools_enabled: agent.tools_enabled ?? false,
      tools: agentTools,
      scientific_format: agent.scientific_format || 'apa',
      output_language: agent.output_language || 'es',
      target_word_count: agent.target_word_count ?? 0,
    };
  });
  const [saving, setSaving] = useState(false);
  // Some callers (e.g. the Flow Designer palette) pass the slug as `id` and omit
  // `slug`; fall back to `id` so agent-specific controls render consistently.
  const agentSlug = agent.slug || agent.id;
  const isFormateador = agentSlug === 'formateador';
  const isRedactor = agentSlug === 'redactor';
  const isInvestigador = agentSlug === 'investigador';

  // Builtin agents with hardcoded adapters: RAG toggle has no effect on them.
  // investigador uses semantic RAG internally; redactor/revisor/formateador/publicador do not query RAG directly.
  const BUILTIN_OWN_ADAPTER = new Set(['investigador', 'redactor', 'revisor', 'formateador', 'publicador']);
  const showRagToggle = !BUILTIN_OWN_ADAPTER.has(agentSlug);

  // The API addresses profiles by their DB UUID. Some callers (Flow Designer
  // palette) pass the slug as `id` and carry the real UUID in `profileId`.
  const profileId = agent.profileId || agent.id;

  /** Persist the current tab contents for the selected agent. */
  const handleSave = async () => {
    setSaving(true);
    try {
      await agentsApi.updateClaudeDef(profileId, tab === 'markdown' ? mdContent : JSON.stringify(params));
      toast.success('Agente guardado');
      await onSaved();
    } catch {
      toast.error('Error al guardar');
    } finally {
      setSaving(false);
    }
  };

  /** Delete the current custom agent profile from the backend. */
  const handleDelete = async () => {
    if (!globalThis.confirm(`¿Eliminar el agente "${agent.name || agent.slug}"? No se puede deshacer.`)) {
      return;
    }

    try {
      await agentsApi.deleteClaudeDef(profileId);
      toast.success('Agente eliminado');
      onDeleted(agent.id);
    } catch (error) {
      toast.error(error?.response?.data?.detail || 'Error al eliminar');
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose} role="dialog" aria-modal="true" aria-labelledby="edit-agent-title">
      <div className="modal modal-lg" onClick={(event) => event.stopPropagation()}>
        <div className="modal-header">
          <h3 id="edit-agent-title">Editar — {agent.name || agent.slug}</h3>
          <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
            {!isBuiltin && (
              <button
                className="btn btn-ghost btn-sm"
                onClick={handleDelete}
                style={{ color: 'var(--error)' }}
                aria-label="Eliminar agente"
              >
                <Trash2 size={13} /> Eliminar
              </button>
            )}
            <button className="btn btn-ghost btn-sm btn-icon" onClick={onClose} aria-label="Cerrar"><X size={16} /></button>
          </div>
        </div>

        <div className="modal-body" style={{ padding: 0 }}>
          <div role="tablist" style={{ padding: 'var(--space-4) var(--space-6) 0', borderBottom: '1px solid var(--border-subtle)', display: 'flex', gap: 4 }}>
            {TABS.map((tabItem) => (
              <button
                key={tabItem.id}
                role="tab"
                aria-selected={tab === tabItem.id}
                onClick={() => setTab(tabItem.id)}
                style={{
                  display: 'flex', alignItems: 'center', gap: 6,
                  padding: '8px 14px', background: 'none', border: 'none', cursor: 'pointer',
                  fontFamily: 'var(--font-sans)', fontSize: 'var(--font-size-sm)', fontWeight: 500,
                  color: tab === tabItem.id ? 'var(--brand-primary)' : 'var(--text-muted)',
                  borderBottom: tab === tabItem.id ? '2px solid var(--brand-primary)' : '2px solid transparent',
                  marginBottom: -1,
                }}
              >
                {tabItem.id === 'params' ? <Sliders size={13} /> : tabItem.id === 'rag' ? <Database size={13} /> : null}
                {tabItem.label}
              </button>
            ))}
          </div>

          <div style={{ padding: 'var(--space-5) var(--space-6)' }}>
            {tab === 'md' && (
              <textarea
                className="input"
                style={{ minHeight: 320, fontFamily: 'var(--font-mono)', fontSize: 'var(--font-size-xs)', lineHeight: 1.7 }}
                value={mdContent}
                onChange={(event) => setMdContent(event.target.value)}
                aria-label="Contenido Markdown del agente"
              />
            )}

            {tab === 'params' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
                <div className="input-group">
                  <label className="input-label">Modelo (Ollama)</label>
                  <ModelSelector value={params.model} onChange={(value) => setParams((current) => ({ ...current, model: value }))} models={models} />
                </div>
                <div className="input-group">
                  <label className="input-label">Temperature <strong>{params.temperature}</strong></label>
                  <input
                    type="range"
                    min="0"
                    max="2"
                    step="0.1"
                    value={params.temperature}
                    onChange={(event) => setParams((current) => ({ ...current, temperature: Number.parseFloat(event.target.value) }))}
                    style={{ width: '100%', accentColor: 'var(--brand-primary)' }}
                    aria-label={`Temperature: ${params.temperature}`}
                  />
                </div>
                <div className="input-group">
                  <label className="input-label">Prompt template</label>
                  <textarea
                    className="input"
                    rows={5}
                    value={params.prompt_template}
                    onChange={(event) => setParams((current) => ({ ...current, prompt_template: event.target.value }))}
                    placeholder={isRedactor
                      ? 'Deja vacío para usar el prompt por defecto.\n\nVariables disponibles:\n{title} — título del artículo\n{keywords} — palabras clave\n{research_data} — contexto del investigador\n{feedback_section} — feedback del revisor (si aplica)'
                      : 'Usa {title}, {context}, {feedback} como variables...'}
                  />
                </div>

                {isRedactor && (
                  <div className="input-group">
                    <label className="input-label">Idioma de redacción</label>
                    <select
                      className="input"
                      value={params.output_language}
                      onChange={(event) => setParams((current) => ({ ...current, output_language: event.target.value }))}
                      aria-label="Seleccionar idioma de redacción"
                    >
                      <option value="es">Español</option>
                      <option value="en">English</option>
                    </select>
                    <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>
                      El redactor generará el borrador completo en este idioma.
                      Idioma activo: <strong style={{ color: 'var(--text-secondary)' }}>{params.output_language === 'es' ? 'Español' : 'English'}</strong>
                    </div>
                  </div>
                )}

                {isRedactor && (
                  <div className="input-group">
                    <label className="input-label" htmlFor="target-word-count">Cantidad de palabras objetivo</label>
                    <input
                      id="target-word-count"
                      type="number"
                      className="input"
                      min={0}
                      step={100}
                      value={params.target_word_count}
                      onChange={(event) => setParams((current) => ({ ...current, target_word_count: parseInt(event.target.value, 10) || 0 }))}
                      placeholder="0 = sin límite"
                      aria-label="Cantidad de palabras objetivo para el borrador"
                    />
                    <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>
                      Orientativo: el modelo intentará ajustar la extensión del borrador.
                      {params.target_word_count > 0
                        ? <> Objetivo: <strong style={{ color: 'var(--text-secondary)' }}>{params.target_word_count} palabras</strong></>
                        : ' Sin límite definido.'}
                    </div>
                  </div>
                )}

                {isFormateador && (
                  <div className="input-group">
                    <label className="input-label">Formato científico por defecto</label>
                    <select
                      className="input"
                      value={params.scientific_format}
                      onChange={(event) => setParams((current) => ({ ...current, scientific_format: event.target.value }))}
                      aria-label="Seleccionar formato científico"
                    >
                      <option value="apa">APA 7th edition — (Autor, Año)</option>
                      <option value="ieee">IEEE — [1], [2] numerados</option>
                      <option value="acl">ACL (conferencia) — (Autor et al., Año)</option>
                      <option value="vancouver">Vancouver — numeración secuencial</option>
                      <option value="chicago">Chicago 17th edition — (Autor Año)</option>
                      <option value="nature">Nature / NLM — superíndices numerados</option>
                    </select>
                    <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>
                      El formateador aplicará este estilo de citas a todos los borradores que procese.
                      Formato activo: <strong style={{ color: 'var(--text-secondary)' }}>{params.scientific_format.toUpperCase()}</strong>
                    </div>
                  </div>
                )}
                {isInvestigador && (
                  <div style={{
                    background: 'rgba(6,182,212,0.08)', border: '1px solid rgba(6,182,212,0.25)',
                    borderRadius: 'var(--radius-md)', padding: 'var(--space-4)',
                    fontSize: 'var(--font-size-xs)', color: 'var(--text-secondary)', lineHeight: 1.7,
                  }}>
                    <strong style={{ color: 'var(--agent-research)', display: 'block', marginBottom: 6 }}>Pipeline del Investigador</strong>
                    El agente ejecuta las siguientes etapas en orden:
                    <ol style={{ margin: '8px 0 0 16px', display: 'flex', flexDirection: 'column', gap: 4 }}>
                      <li><strong>RAG local</strong> — búsqueda vectorial (cosine similarity) en Qdrant con las keywords del artículo como query. Controlado por <em>Top-K RAG</em> y <em>coleción</em> del tab RAG.</li>
                      <li><strong>EuropePMC</strong> — consulta la API REST de EuropePMC y recupera artículos científicos en abierto relacionados con las keywords.</li>
                      <li><strong>Web scraping</strong> — si EuropePMC no aporta suficiente contexto, raspa arXiv, Wikipedia y Semantic Scholar. Cuando <em>Semantic re-rank</em> está activo, re-ordena las páginas descargadas por similitud coseno antes de pasarlas al modelo.</li>
                      <li><strong>Síntesis con Ollama</strong> — combina todas las fuentes y genera el campo <code>research_data</code> que recibe el Redactor.
                        <ul style={{ margin: '4px 0 0 16px', display: 'flex', flexDirection: 'column', gap: 2 }}>
                          <li>Con fuentes externas: usa el modelo configurado (por defecto <code>mistral:7b</code>) con <code>num_ctx = 8192</code> y timeout de 10 min.</li>
                          <li>Sin fuentes (solo parametric): usa <code>llama3.2:1b</code> como fallback con <code>num_ctx = 2048</code> y timeout de 2 min.</li>
                        </ul>
                      </li>
                    </ol>
                    <div style={{ marginTop: 8 }}>Gestiona los documentos propios del investigador en el tab <strong>RAG</strong>. Cambia el modelo de síntesis en <em>Configuración → Agentes → Investigador</em>.</div>
                  </div>
                )}

                {showRagToggle ? (
                  <>
                    <div
                      role="switch"
                      aria-checked={params.rag_enabled}
                      tabIndex={0}
                      onClick={() => setParams((current) => ({ ...current, rag_enabled: !current.rag_enabled }))}
                      onKeyDown={(event) => {
                        if (event.key === ' ') {
                          setParams((current) => ({ ...current, rag_enabled: !current.rag_enabled }));
                        }
                      }}
                      className="toggle-wrapper"
                      style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}
                    >
                      <div className={`toggle ${params.rag_enabled ? 'on' : ''}`} aria-hidden="true" />
                      <span className="toggle-label">RAG habilitado</span>
                    </div>

                    {params.rag_enabled && (
                      <div style={{ display: 'flex', gap: 'var(--space-4)', margin: 'var(--space-1) 0 var(--space-2)' }}>
                        <div
                          role="switch"
                          aria-checked={params.graph_rag_enabled}
                          tabIndex={0}
                          onClick={() => setParams((current) => {
                            const nextGraph = !current.graph_rag_enabled;
                            return {
                              ...current,
                              graph_rag_enabled: nextGraph,
                              semantic_search_enabled: nextGraph ? true : current.semantic_search_enabled
                            };
                          })}
                          onKeyDown={(event) => {
                            if (event.key === ' ') {
                              setParams((current) => {
                                const nextGraph = !current.graph_rag_enabled;
                                return {
                                  ...current,
                                  graph_rag_enabled: nextGraph,
                                  semantic_search_enabled: nextGraph ? true : current.semantic_search_enabled
                                };
                              });
                            }
                          }}
                          className="toggle-wrapper"
                          style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}
                        >
                          <div className={`toggle ${params.graph_rag_enabled ? 'on' : ''}`} aria-hidden="true" />
                          <span className="toggle-label" style={{ fontSize: 'var(--font-size-xs)' }}>Graph RAG</span>
                        </div>

                        <div
                          role="switch"
                          aria-checked={params.semantic_search_enabled}
                          tabIndex={0}
                          onClick={() => setParams((current) => {
                            const nextSemantic = !current.semantic_search_enabled;
                            return {
                              ...current,
                              semantic_search_enabled: nextSemantic,
                              graph_rag_enabled: nextSemantic ? current.graph_rag_enabled : false
                            };
                          })}
                          onKeyDown={(event) => {
                            if (event.key === ' ') {
                              setParams((current) => {
                                const nextSemantic = !current.semantic_search_enabled;
                                return {
                                  ...current,
                                  semantic_search_enabled: nextSemantic,
                                  graph_rag_enabled: nextSemantic ? current.graph_rag_enabled : false
                                };
                              });
                            }
                          }}
                          className="toggle-wrapper"
                          style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}
                        >
                          <div className={`toggle ${params.semantic_search_enabled ? 'on' : ''}`} aria-hidden="true" />
                          <span className="toggle-label" style={{ fontSize: 'var(--font-size-xs)' }}>Búsqueda Semántica</span>
                        </div>
                      </div>
                    )}

                    {params.rag_enabled && (
                      <>
                        <div className="input-group">
                          <label className="input-label">Colección RAG</label>
                          <input
                            className="input"
                            value={params.rag_collection}
                            onChange={(event) => setParams((current) => ({ ...current, rag_collection: event.target.value }))}
                            placeholder="rag_docs"
                          />
                        </div>
                        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 'var(--space-3)' }}>
                          <div className="input-group">
                            <label className="input-label">Chunk size</label>
                            <input
                              className="input"
                              type="number"
                              min="100"
                              max="4000"
                              value={params.rag_chunk_size}
                              onChange={(event) => setParams((current) => ({ ...current, rag_chunk_size: Number.parseInt(event.target.value || '500', 10) }))}
                            />
                          </div>
                          <div className="input-group">
                            <label className="input-label">Overlap</label>
                            <input
                              className="input"
                              type="number"
                              min="0"
                              max={Math.max((params.rag_chunk_size || 500) - 1, 0)}
                              value={params.rag_chunk_overlap}
                              onChange={(event) => setParams((current) => ({ ...current, rag_chunk_overlap: Number.parseInt(event.target.value || '50', 10) }))}
                            />
                          </div>
                        </div>
                      </>
                    )}
                  </>
                ) : !isInvestigador && (
                  <div style={{
                    background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)',
                    borderRadius: 'var(--radius-md)', padding: 'var(--space-3) var(--space-4)',
                    fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', lineHeight: 1.6,
                  }}>
                    Este agente tiene un adaptador propio y no consulta RAG directamente. El contexto de investigación le llega a través del estado del pipeline (campo <code>research_data</code>).
                  </div>
                )}
              </div>
            )}

            {tab === 'rag' && (
              <RagTab
                agentName={agent.id}
                ragCollection={params.rag_collection}
                ragChunkSize={params.rag_chunk_size}
                ragChunkOverlap={params.rag_chunk_overlap}
                ragDocIds={params.rag_doc_ids || []}
                onCollectionChange={(col) => setParams((p) => ({ ...p, rag_collection: col, rag_doc_ids: [] }))}
                onDocIdsChange={(ids) => setParams((p) => ({ ...p, rag_doc_ids: ids }))}
              />
            )}


          </div>
        </div>

        {(tab !== 'rag') && (
          <div className="modal-footer">
            <button className="btn btn-ghost" onClick={onClose}>Cancelar</button>
            <button className="btn btn-primary" onClick={handleSave} disabled={saving}>
              <Save size={14} /> {saving ? 'Guardando...' : 'Guardar cambios'}
            </button>
          </div>
        )}
        {tab === 'rag' && (
          <div className="modal-footer">
            <button className="btn btn-ghost" onClick={onClose}>Cerrar</button>
            <button className="btn btn-primary" onClick={handleSave} disabled={saving}>
              <Save size={14} /> {saving ? 'Guardando...' : 'Guardar colección'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

/** Create a new agent profile and persist it through the backend API. */
export function AgentCreateModal({ builtInIds, onClose, onCreate }) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [model, setModel] = useState('llama3.2:1b');
  const [models, setModels] = useState(['llama3.2:1b']);
  const [ragEnabled, setRagEnabled] = useState(false);
  const [ragCollection, setRagCollection] = useState('rag_docs');
  const [ragChunkSize, setRagChunkSize] = useState(500);
  const [ragChunkOverlap, setRagChunkOverlap] = useState(50);
  const [saving, setSaving] = useState(false);
  const [nameError, setNameError] = useState('');

  useEffect(() => {
    agentsApi.getModels().then((response) => setModels(response.models || ['llama3.2:1b'])).catch(() => {});
  }, []);

  const validateName = (value) => {
    if (!value) return 'Nombre requerido';
    if (!/^[a-z0-9_-]+$/.test(value)) return 'Solo minúsculas, números, guiones y guiones bajos';
    if (builtInIds.has(value)) return 'Ese nombre está reservado';
    return '';
  };

  const handleSubmit = async () => {
    const validationError = validateName(name);
    if (validationError) {
      setNameError(validationError);
      return;
    }

    setSaving(true);
    try {
      await onCreate({
        name,
        description,
        model,
        rag_enabled: ragEnabled,
        rag_collection: ragCollection,
        rag_chunk_size: ragChunkSize,
        rag_chunk_overlap: ragChunkOverlap,
      });
      onClose();
    } catch (error) {
      toast.error(error?.response?.data?.detail || 'Error al crear agente');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={onClose} role="dialog" aria-modal="true" aria-labelledby="new-agent-title">
      <div className="modal" onClick={(event) => event.stopPropagation()} style={{ maxWidth: 480 }}>
        <div className="modal-header">
          <h3 id="new-agent-title">Nuevo agente personalizado</h3>
          <button className="btn btn-ghost btn-sm btn-icon" onClick={onClose} aria-label="Cerrar"><X size={16} /></button>
        </div>
        <div className="modal-body" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          <div className="input-group">
            <label className="input-label" htmlFor="new-agent-name">Identificador <span aria-hidden="true">*</span></label>
            <input
              id="new-agent-name"
              className="input"
              value={name}
              onChange={(event) => {
                setName(event.target.value.toLowerCase());
                setNameError('');
              }}
              placeholder="mi-agente-custom"
              aria-describedby={nameError ? 'name-error' : undefined}
            />
            {nameError && (
              <div id="name-error" role="alert" style={{ display: 'flex', alignItems: 'center', gap: 4, marginTop: 4, color: 'var(--error)', fontSize: 'var(--font-size-xs)' }}>
                {nameError}
              </div>
            )}
          </div>
          <div className="input-group">
            <label className="input-label" htmlFor="new-agent-desc">Descripción</label>
            <textarea
              id="new-agent-desc"
              className="input"
              rows={3}
              value={description}
              onChange={(event) => setDescription(event.target.value)}
              placeholder="¿Qué hace este agente?"
            />
          </div>
          <div className="input-group">
            <label className="input-label">Modelo por defecto</label>
            <ModelSelector value={model} onChange={setModel} models={models} />
          </div>
          <div
            role="switch"
            aria-checked={ragEnabled}
            tabIndex={0}
            onClick={() => setRagEnabled((current) => !current)}
            onKeyDown={(event) => {
              if (event.key === ' ') {
                setRagEnabled((current) => !current);
              }
            }}
            className="toggle-wrapper"
            style={{ cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}
          >
            <div className={`toggle ${ragEnabled ? 'on' : ''}`} aria-hidden="true" />
            <span className="toggle-label">RAG habilitado</span>
          </div>
          {ragEnabled && (
            <>
              <div className="input-group">
                <label className="input-label" htmlFor="new-agent-rag">Colección RAG</label>
                <input
                  id="new-agent-rag"
                  className="input"
                  value={ragCollection}
                  onChange={(event) => setRagCollection(event.target.value)}
                  placeholder="rag_docs"
                />
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 'var(--space-3)' }}>
                <div className="input-group">
                  <label className="input-label" htmlFor="new-agent-chunk-size">Chunk size</label>
                  <input
                    id="new-agent-chunk-size"
                    className="input"
                    type="number"
                    min="100"
                    max="4000"
                    value={ragChunkSize}
                    onChange={(event) => setRagChunkSize(Number.parseInt(event.target.value || '500', 10))}
                  />
                </div>
                <div className="input-group">
                  <label className="input-label" htmlFor="new-agent-chunk-overlap">Overlap</label>
                  <input
                    id="new-agent-chunk-overlap"
                    className="input"
                    type="number"
                    min="0"
                    max={Math.max(ragChunkSize - 1, 0)}
                    value={ragChunkOverlap}
                    onChange={(event) => setRagChunkOverlap(Number.parseInt(event.target.value || '50', 10))}
                  />
                </div>
              </div>
            </>
          )}
        </div>
        <div className="modal-footer">
          <button className="btn btn-ghost" onClick={onClose}>Cancelar</button>
          <button className="btn btn-primary" onClick={handleSubmit} disabled={saving}>
            {saving ? 'Creando...' : 'Crear agente'}
          </button>
        </div>
      </div>
    </div>
  );
}