// Generated by GitHub Copilot
import React, { useEffect, useRef, useState, useCallback } from 'react';
import {
  Bot, Pencil, Plus, ChevronDown, Trash2,
  Search, PenLine, Eye, FileText, Send, Cpu,
} from 'lucide-react';
import { agentsApi } from '../api/agents';
import { AgentCreateModal, AgentEditorModal } from '../components/agents/AgentEditorModal';
import { useProjectStore } from '../store/projectStore';
import toast from 'react-hot-toast';

const BUILTIN_SLUGS = new Set(['investigador', 'redactor', 'revisor', 'formateador', 'publicador', 'orquestador',
  'arquitecto', 'backend-dev', 'frontend-dev', 'qa-tester', 'devops', 'code-reviewer',
  'estratega', 'copywriter', 'social-media', 'seo-specialist', 'analista',
  'clasificador', 'agente-soporte', 'escalador', 'resolutor', 'qa-calidad',
  'art-director', 'ui-designer', 'ux-researcher', 'revisor-visual', 'motion-designer',
]);

const BUILTIN_META = {
  // AlejandrIA Magazine — DS agent palette
  investigador:    { icon: Search,   color: '#0d9dda' },
  redactor:        { icon: PenLine,  color: '#6b4fe3' },
  revisor:         { icon: Eye,      color: '#c47d04' },
  formateador:     { icon: FileText, color: '#2e844a' },
  publicador:      { icon: Send,     color: '#cb4b3f' },
  orquestador:     { icon: Cpu,      color: '#0176d3' },
  // Desarrollo
  arquitecto:      { color: '#2e844a' },
  'backend-dev':   { color: '#2e844a' },
  'frontend-dev':  { color: '#2e844a' },
  'qa-tester':     { color: '#2e844a' },
  devops:          { color: '#2e844a' },
  'code-reviewer': { color: '#2e844a' },
  // Marketing
  estratega:       { color: '#c47d04' },
  copywriter:      { color: '#c47d04' },
  'social-media':  { color: '#c47d04' },
  'seo-specialist':{ color: '#c47d04' },
  analista:        { color: '#c47d04' },
  // Tiqueting
  clasificador:    { color: '#0d9dda' },
  'agente-soporte':{ color: '#0d9dda' },
  escalador:       { color: '#0d9dda' },
  resolutor:       { color: '#0d9dda' },
  'qa-calidad':    { color: '#0d9dda' },
  // Diseño
  'art-director':  { color: '#6b4fe3' },
  'ui-designer':   { color: '#6b4fe3' },
  'ux-researcher': { color: '#6b4fe3' },
  'revisor-visual':{ color: '#6b4fe3' },
  'motion-designer':{ color: '#6b4fe3' },
};

// ---------------------------------------------------------------------------
// ModelSelector dropdown
// ---------------------------------------------------------------------------

function ModelSelector({ value, onChange, models }) {
  const [open, setOpen] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    const handler = (e) => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <button
        type="button"
        className="input"
        onClick={() => setOpen(o => !o)}
        style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer', textAlign: 'left' }}
        aria-haspopup="listbox"
        aria-expanded={open}
      >
        <span>{value || 'Selecciona modelo'}</span>
        <ChevronDown size={14} style={{ flexShrink: 0, color: 'var(--text-muted)' }} />
      </button>
      {open && (
        <ul
          role="listbox"
          style={{
            position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 50,
            background: 'var(--bg-card)', border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-md)', listStyle: 'none', margin: '4px 0 0',
            padding: '4px 0', maxHeight: 200, overflowY: 'auto',
            boxShadow: '0 8px 24px rgba(0,0,0,0.3)',
          }}
        >
          {models.map(m => (
            <li
              key={m}
              role="option"
              aria-selected={m === value}
              onClick={() => { onChange(m); setOpen(false); }}
              style={{
                padding: '7px 14px', cursor: 'pointer', fontSize: 'var(--font-size-sm)',
                background: m === value ? 'var(--bg-overlay)' : 'transparent',
                color: m === value ? 'var(--brand-primary)' : 'var(--text-primary)',
              }}
            >
              {m}
            </li>
          ))}
          <li style={{ borderTop: '1px solid var(--border-subtle)', padding: '4px 8px' }}>
            <input
              className="input"
              placeholder="Otro modelo…"
              style={{ fontSize: 'var(--font-size-xs)', padding: '4px 8px' }}
              aria-label="Nombre de modelo personalizado"
              onKeyDown={e => {
                if (e.key === 'Enter' && e.target.value.trim()) {
                  onChange(e.target.value.trim());
                  setOpen(false);
                }
              }}
            />
          </li>
        </ul>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Agent card
// ---------------------------------------------------------------------------

function AgentCard({ agent, isBuiltin, onEdit, onDelete }) {
  const meta = BUILTIN_META[agent.slug] || {};
  const color = meta.color || 'var(--text-muted)';
  const Icon = meta.icon || Bot;

  return (
    <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
        <div style={{
          width: 40, height: 40, borderRadius: 'var(--radius-md)', display: 'flex',
          alignItems: 'center', justifyContent: 'center', flexShrink: 0,
          background: isBuiltin ? `${color}18` : 'var(--bg-inset)',
          color: isBuiltin ? color : 'var(--text-muted)',
        }}>
          <Icon size={20} strokeWidth={1.5} />
        </div>
        <div>
          <div style={{ fontWeight: 600, fontSize: 'var(--font-size-base)' }}>
            {agent.name || agent.slug}
          </div>
          <div style={{ fontSize: 10, fontWeight: 600, color, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
            {isBuiltin ? 'sistema' : 'personalizado'}
          </div>
        </div>
      </div>
      {agent.model && (
        <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
          Modelo: <strong style={{ color: 'var(--text-secondary)' }}>{agent.model}</strong>
        </div>
      )}
      <button
        className="btn btn-ghost btn-sm"
        style={{ alignSelf: 'flex-start' }}
        onClick={() => onEdit(agent, isBuiltin)}
        aria-label={`Editar agente ${agent.name || agent.slug}`}
      >
        <Pencil size={13} /> Editar
      </button>
      {!isBuiltin && (
        <button
          className="btn btn-ghost btn-sm"
          style={{ alignSelf: 'flex-start', color: 'var(--error)' }}
          onClick={() => onDelete(agent)}
          aria-label={`Eliminar agente ${agent.name || agent.slug}`}
        >
          <Trash2 size={13} /> Eliminar
        </button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function AgentsPage() {
  const { activeProject } = useProjectStore();
  const [profiles, setProfiles] = useState([]);
  const [models, setModels] = useState(['llama3.2:1b']);
  const [editAgent, setEditAgent] = useState(null);
  const [editIsBuiltin, setEditIsBuiltin] = useState(false);
  const [showNew, setShowNew] = useState(false);

  const loadProfiles = useCallback(async () => {
    if (!activeProject?.id) { setProfiles([]); return; }
    try {
      const defs = await agentsApi.getClaudeDefs(activeProject.id);
      setProfiles(defs);
    } catch { setProfiles([]); }
  }, [activeProject?.id]);

  useEffect(() => {
    loadProfiles();
    agentsApi.getModels().then(r => setModels(r.models || ['llama3.2:1b'])).catch(() => {});
  }, [loadProfiles]);

  const builtins = profiles.filter(p => BUILTIN_SLUGS.has(p.slug));
  const custom = profiles.filter(p => !BUILTIN_SLUGS.has(p.slug));

  const handleDelete = async (agent) => {
    if (!globalThis.confirm(`¿Eliminar el agente "${agent.name || agent.slug}"? Esta acción no se puede deshacer.`)) return;
    try {
      await agentsApi.deleteClaudeDef(agent.id);
      setProfiles(p => p.filter(x => x.id !== agent.id));
      toast.success(`Agente "${agent.name || agent.slug}" eliminado`);
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Error al eliminar el agente');
    }
  };

  return (
    <div className="page-body">
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 'var(--space-6)', gap: 'var(--space-4)', flexWrap: 'wrap' }}>
        <div>
          <h2 style={{ marginBottom: 4 }}>Agentes</h2>
          <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>
            Gestiona perfiles, modelos y bases de conocimiento de cada agente.
          </p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowNew(true)} aria-label="Crear nuevo agente personalizado">
          <Plus size={14} /> Nuevo agente
        </button>
      </div>

      {/* Built-in agents */}
      {builtins.length > 0 && (
        <section aria-labelledby="section-builtin">
          <div id="section-builtin" style={{ marginBottom: 'var(--space-2)', fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
            Agentes del sistema
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 'var(--space-3)', marginBottom: 'var(--space-6)' }}>
            {builtins.map(agent => (
              <AgentCard key={agent.id} agent={agent} isBuiltin onEdit={(a, b) => { setEditAgent(a); setEditIsBuiltin(b); }} onDelete={handleDelete} />
            ))}
          </div>
        </section>
      )}

      {/* Custom agents */}
      {custom.length > 0 && (
        <section aria-labelledby="section-custom">
          <div id="section-custom" style={{ marginBottom: 'var(--space-2)', fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
            Agentes personalizados
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 'var(--space-3)' }}>
            {custom.map(agent => (
              <AgentCard key={agent.id} agent={agent} isBuiltin={false} onEdit={(a, b) => { setEditAgent(a); setEditIsBuiltin(b); }} onDelete={handleDelete} />
            ))}
          </div>
        </section>
      )}

      {profiles.length === 0 && (
        <div style={{ textAlign: 'center', color: 'var(--text-muted)', padding: 'var(--space-8)', fontSize: 'var(--font-size-sm)' }}>
          No se encontraron perfiles. Comprueba que el backend está en ejecución.
        </div>
      )}

      {showNew && (
        <AgentCreateModal
          builtInIds={BUILTIN_SLUGS}
          onClose={() => setShowNew(false)}
          onCreate={async (payload) => {
            await agentsApi.createClaudeDef({ ...payload, project_id: activeProject?.id });
            toast.success(`Agente "${payload.name}" creado`);
            await loadProfiles();
          }}
        />
      )}

      {editAgent && (
        <AgentEditorModal
          agent={editAgent}
          isBuiltin={editIsBuiltin}
          models={models}
          onClose={() => setEditAgent(null)}
          onSaved={async () => { setEditAgent(null); await loadProfiles(); }}
          onDeleted={(id) => { setEditAgent(null); setProfiles(p => p.filter(x => x.id !== id)); }}
        />
      )}
    </div>
  );
}
