import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import { ArrowLeft, CheckCircle, XCircle, UserPlus, Clock, AlertCircle, Pencil, Save, X, GitBranch, FileText, Plus, Trash2, Palette } from 'lucide-react';
import { useArticleStore } from '../store/articleStore';
import { useAuthStore } from '../store/authStore';
import { agentsApi } from '../api/agents';
import toast from 'react-hot-toast';

// Generated by GitHub Copilot
/**
 * Converts a markdown string to plain text by removing formatting syntax.
 * Used when entering article body edit mode so the user edits clean prose.
 */
function stripMarkdown(text) {
  if (!text) return '';
  return text
    .replace(/```[\s\S]*?```/gm, '')          // fenced code blocks
    .replace(/`([^`]+)`/g, '$1')              // inline code
    .replace(/^#{1,6}\s+(.*)$/gm, '$1')       // headings
    .replace(/\*\*([^*]+)\*\*/g, '$1')        // bold **
    .replace(/__([^_]+)__/g, '$1')            // bold __
    .replace(/\*([^*]+)\*/g, '$1')            // italic *
    .replace(/_([^_]+)_/g, '$1')              // italic _
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1') // links
    .replace(/^[-*+]\s+/gm, '')              // unordered lists
    .replace(/^\d+\.\s+/gm, '')              // ordered lists
    .replace(/^>\s*/gm, '')                   // blockquotes
    .replace(/---+/g, '')                     // horizontal rules
    .replace(/\n{3,}/g, '\n\n')              // collapse excess blank lines
    .trim();
}

const STATUS_CONFIG = {
  draft:     { label: 'Borrador',   cls: 'badge-draft',      icon: <Clock size={11} /> },
  in_review: { label: 'Pendiente',  cls: 'badge-pending',    icon: <AlertCircle size={11} /> },
  approved:  { label: 'Aprobado',   cls: 'badge-approved',   icon: <CheckCircle size={11} /> },
  published: { label: 'Publicado',  cls: 'badge-published',  icon: <CheckCircle size={11} /> },
  rejected:  { label: 'Rechazado',  cls: 'badge-error',      icon: <XCircle size={11} /> },
};

export default function ArticleDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const { currentArticle, fetchArticle, approveArticle, rejectArticle, assignReviewer, updateArticle, publishArticle } = useArticleStore();
  const [loading, setLoading] = useState(true);
  const [reviewerEmail, setReviewerEmail] = useState('');  // accepts email or full name
  const [showPipelineModal, setShowPipelineModal] = useState(false);
  const [pipelineAgents, setPipelineAgents] = useState([]);   // [{id, label}] from last run
  const [selectedAgents, setSelectedAgents] = useState([]);   // subset chosen by user
  const [loadingRuns, setLoadingRuns] = useState(false);
  const [usedDefaultFlow, setUsedDefaultFlow] = useState(false);
  const [rejectComment, setRejectComment] = useState('');
  const [showRejectModal, setShowRejectModal] = useState(false);
  const [working, setWorking] = useState(false);
  const [editingBody, setEditingBody] = useState(false);
  const [bodyDraft, setBodyDraft] = useState('');
  const [editingMeta, setEditingMeta] = useState(false);
  const [abstractDraft, setAbstractDraft] = useState('');
  const [authorsDraft, setAuthorsDraft] = useState([]);

  useEffect(() => {
    fetchArticle(id).finally(() => setLoading(false));
  }, [id]);

  const article = currentArticle;
  const st = article ? (STATUS_CONFIG[article.status] || STATUS_CONFIG.draft) : null;
  const isReviewer = user?.role === 'admin' ||
    (article?.reviewer_id && user?.id &&
      String(article.reviewer_id).toLowerCase() === String(user.id).toLowerCase());
  // isAuthor: user who created this article, or an admin acting on behalf of any article
  const isAuthor = (article?.author_id && user?.id &&
    String(article.author_id).toLowerCase() === String(user.id).toLowerCase()) ||
    user?.role === 'admin';

  const canPublishDirect = (user?.role === 'admin' || user?.role === 'redactor')
    && article?.status === 'draft';

  const handleApprove = async () => {
    setWorking(true);
    try {
      await approveArticle(id);
      toast.success('Artículo aprobado ✅');
    } catch { toast.error('Error al aprobar'); }
    finally { setWorking(false); }
  };

  const handlePublishDirect = async () => {
    setWorking(true);
    try {
      await publishArticle(id);
      toast.success('Artículo publicado 🚀');
    } catch (err) { toast.error(err?.response?.data?.detail || 'Error al publicar'); }
    finally { setWorking(false); }
  };

  const handleReject = async () => {
    setWorking(true);
    try {
      await rejectArticle(id, rejectComment);
      toast.success('Artículo rechazado');
      setShowRejectModal(false);
    } catch { toast.error('Error al rechazar'); }
    finally { setWorking(false); }
  };

  const handleAssign = async () => {
    if (!reviewerEmail.trim()) { toast.error('Escribe el email o nombre del revisor'); return; }
    setWorking(true);
    try {
      await assignReviewer(id, reviewerEmail);
      toast.success('Revisor asignado — artículo en revisión');
      setReviewerEmail('');
    } catch (err) { toast.error(err?.response?.data?.detail || 'Revisor no encontrado'); }
    finally { setWorking(false); }
  };

  const AGENT_LABELS = {
    investigador: '🔍 Investigador', redactor: '✍️ Redactor', revisor: '👁️ Revisor',
    formateador: '📄 Formateador', publicador: '🚀 Publicador', orquestador: '🧠 Orquestador',
  };

  // Canonical order for the pipeline selector
  const ORDERED_AGENTS = ['investigador', 'redactor', 'revisor', 'formateador', 'publicador'];

  const handleOpenPipelineModal = async () => {
    setLoadingRuns(true);
    setShowPipelineModal(true);
    setUsedDefaultFlow(false);
    try {
      // Load available agents + last run history in parallel
      const [defsData, runsData] = await Promise.allSettled([
        agentsApi.getDefinitions(),
        agentsApi.getRuns(id),
      ]);

      // Build full agent list: definitions dict keys, ordered canonically
      const defIds = defsData.status === 'fulfilled'
        ? Object.keys(defsData.value)
        : ORDERED_AGENTS;
      // Keep canonical order, append any extra agents not in the canonical list
      const allAgents = [
        ...ORDERED_AGENTS.filter(a => defIds.includes(a)),
        ...defIds.filter(a => !ORDERED_AGENTS.includes(a)),
      ];
      setPipelineAgents(allAgents);

      // Pre-select agents from the last run (in canonical order)
      const runs = runsData.status === 'fulfilled' ? (runsData.value.runs || []) : [];
      const seenInHistory = new Set();
      runs.forEach(r => seenInHistory.add(r.agent_name));

      if (seenInHistory.size > 0) {
        // Preserve canonical order for the pre-selection
        setSelectedAgents(allAgents.filter(a => seenInHistory.has(a)));
      } else {
        // No history — pre-select all
        setSelectedAgents([...allAgents]);
        setUsedDefaultFlow(true);
      }
    } catch {
      toast.error('No se pudo cargar los agentes disponibles');
      setPipelineAgents(ORDERED_AGENTS);
      setSelectedAgents([...ORDERED_AGENTS]);
      setUsedDefaultFlow(true);
    } finally {
      setLoadingRuns(false);
    }
  };

  const handleConfirmPipeline = () => {
    if (selectedAgents.length === 0) { toast.error('Selecciona al menos un agente'); return; }
    setShowPipelineModal(false);
    navigate(`/execution/${article.id}`, {
      state: { flowSequence: selectedAgents, agentSettings: {}, keywords: [], contextDescription: '', articleOutline: '' },
    });
  };

  const handleEditBody = () => {
    // Keep raw markdown so the user can paste/edit formatted content
    setBodyDraft(article.body || '');
    setEditingBody(true);
  };

  const handleSaveBody = async () => {
    setWorking(true);
    try {
      await updateArticle(id, { body: bodyDraft });
      setEditingBody(false);
      toast.success('Contenido guardado');
    } catch { toast.error('Error al guardar'); }
    finally { setWorking(false); }
  };

  const handleEditMeta = () => {
    setAbstractDraft(article.abstract || '');
    setAuthorsDraft(
      (article.authors && article.authors.length)
        ? article.authors.map(a => ({ name: a.name || '', affiliation: a.affiliation || '', email: a.email || '' }))
        : [{ name: '', affiliation: '', email: '' }]
    );
    setEditingMeta(true);
  };

  const updateAuthorField = (idx, field, value) =>
    setAuthorsDraft(prev => prev.map((a, i) => i === idx ? { ...a, [field]: value } : a));

  const handleSaveMeta = async () => {
    setWorking(true);
    try {
      // Drop empty author rows; an author needs at least a name
      const authors = authorsDraft
        .map(a => ({ name: a.name.trim(), affiliation: a.affiliation.trim(), email: a.email.trim() }))
        .filter(a => a.name);
      await updateArticle(id, { authors, abstract: abstractDraft });
      setEditingMeta(false);
      toast.success('Metadatos del paper guardados');
    } catch { toast.error('Error al guardar los metadatos'); }
    finally { setWorking(false); }
  };

  const handleViewPaper = () => navigate(`/articles/${id}/paper`);
  const handleDesignPaper = () => navigate(`/articles/${id}/design`);

  if (loading) return <div className="page-body"><div className="empty-state"><div className="spinner spinner-lg" /></div></div>;
  if (!article) return <div className="page-body"><div className="empty-state"><h3>Artículo no encontrado</h3></div></div>;

  return (
    <div className="page-body" style={{ maxWidth: 900, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', marginBottom: 'var(--space-6)' }}>
        <button className="btn btn-ghost btn-sm btn-icon" onClick={() => navigate(-1)}><ArrowLeft size={16} /></button>
        <div style={{ flex: 1 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', flexWrap: 'wrap' }}>
            <h2 style={{ margin: 0, fontSize: 'var(--font-size-xl)' }}>{article.title}</h2>
            {st && <span className={`badge ${st.cls}`}>{st.icon} {st.label}</span>}
          </div>
          <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>
            Creado: {new Date(article.created_at).toLocaleDateString('es-ES', { day: '2-digit', month: 'long', year: 'numeric' })}
            {article.scientific_format && article.scientific_format !== 'none' && ` · Formato ${article.scientific_format.toUpperCase()}`}
          </div>
        </div>
      </div>

      {/* Status banner */}
      {article.status === 'in_review' && (
        <div style={{ background: 'var(--status-warning-bg)', border: '1px solid rgba(245,158,11,0.25)', borderRadius: 'var(--radius-md)', padding: 'var(--space-4)', marginBottom: 'var(--space-5)', display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
          <AlertCircle size={16} style={{ color: 'var(--status-warning)', flexShrink: 0 }} />
          <div style={{ fontSize: 'var(--font-size-sm)' }}>
            <strong style={{ color: 'var(--status-warning)' }}>Pendiente de aprobación</strong>
            {article.reviewer_id && <span style={{ color: 'var(--text-muted)' }}> · Revisor asignado</span>}
          </div>
        </div>
      )}

      {article.status === 'approved' && (
        <div style={{ background: 'var(--status-success-bg)', border: '1px solid rgba(16,185,129,0.25)', borderRadius: 'var(--radius-md)', padding: 'var(--space-4)', marginBottom: 'var(--space-5)', display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
          <CheckCircle size={16} style={{ color: 'var(--status-success)', flexShrink: 0 }} />
          <strong style={{ color: 'var(--status-success)', fontSize: 'var(--font-size-sm)' }}>Artículo aprobado</strong>
        </div>
      )}

      {article.status === 'rejected' && article.rejection_comment && (
        <div style={{ background: 'var(--status-error-bg)', border: '1px solid rgba(239,68,68,0.25)', borderRadius: 'var(--radius-md)', padding: 'var(--space-4)', marginBottom: 'var(--space-5)' }}>
          <div style={{ fontWeight: 600, color: 'var(--status-error)', fontSize: 'var(--font-size-sm)', marginBottom: 4 }}>Rechazado</div>
          <div style={{ color: 'var(--text-secondary)', fontSize: 'var(--font-size-sm)' }}>{article.rejection_comment}</div>
        </div>
      )}

      {/* Main content grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 280px', gap: 'var(--space-6)', alignItems: 'start' }}>
        {/* Article body */}
        <div className="card" style={{ padding: 'var(--space-8)' }}>
          {/* Edit / Save toolbar */}
          <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: editingBody ? 'var(--space-3)' : 0 }}>
            {!editingBody ? (
              <button
                className="btn btn-ghost btn-sm"
                onClick={handleEditBody}
                aria-label="Editar contenido del artículo"
              >
                <Pencil size={13} /> Editar
              </button>
            ) : (
              <div style={{ display: 'flex', gap: 6 }}>
                <button
                  className="btn btn-ghost btn-sm"
                  onClick={() => setEditingBody(false)}
                  disabled={working}
                  aria-label="Cancelar edición"
                >
                  <X size={13} /> Cancelar
                </button>
                <button
                  className="btn btn-primary btn-sm"
                  onClick={handleSaveBody}
                  disabled={working}
                  aria-label="Guardar contenido"
                >
                  <Save size={13} /> Guardar
                </button>
              </div>
            )}
          </div>

          {editingBody ? (
            <textarea
              value={bodyDraft}
              onChange={e => setBodyDraft(e.target.value)}
              autoFocus
              aria-label="Contenido del artículo en texto plano"
              style={{
                width: '100%', minHeight: 400, background: 'var(--bg-surface)',
                border: '1px solid var(--border-default)', borderRadius: 'var(--radius-md)',
                padding: 'var(--space-4)', color: 'var(--text-primary)',
                fontSize: 'var(--font-size-sm)', fontFamily: 'inherit',
                lineHeight: 1.7, resize: 'vertical', outline: 'none', boxSizing: 'border-box',
              }}
            />
          ) : article.body && !article.body.startsWith('Error:') ? (
            <div className="markdown-body">
              <ReactMarkdown>{article.body}</ReactMarkdown>
            </div>
          ) : (
            <div className="empty-state" style={{ padding: 'var(--space-10)' }}>
              <h3>{article.body?.startsWith('Error:') ? 'Error en la generación' : 'Sin contenido'}</h3>
              <p style={{ color: 'var(--text-muted)', fontSize: 'var(--font-size-sm)' }}>
                {article.body?.startsWith('Error:')
                  ? 'El agente no pudo generar el contenido. Puedes escribirlo manualmente usando el botón Editar.'
                  : 'Este artículo aún no tiene contenido generado.'}
              </p>
              <button className="btn btn-primary btn-sm" style={{ marginTop: 'var(--space-4)' }} onClick={handleEditBody}>
                <Pencil size={13} /> Escribir manualmente
              </button>
            </div>
          )}
        </div>

        {/* Sidebar actions */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
          {/* Direct publish — admin / redactor on draft articles */}
          {canPublishDirect && (
            <div className="card">
              <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)', marginBottom: 'var(--space-3)' }}>Publicar</div>
              <button
                className="btn btn-primary w-full"
                onClick={handlePublishDirect}
                disabled={working}
                aria-label="Publicar este borrador directamente"
              >
                <CheckCircle size={14} /> Publicar borrador
              </button>
              <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 'var(--space-2)' }}>
                El artículo pasará a estado <strong>Publicado</strong> sin pasar por revisión.
              </div>
            </div>
          )}

          {/* Reviewer actions */}
          {isReviewer && article.status === 'in_review' && (
            <div className="card">
              <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)', marginBottom: 'var(--space-3)' }}>Acciones de revisión</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                <button className="btn btn-primary w-full" onClick={handleApprove} disabled={working}>
                  <CheckCircle size={14} /> Aprobar artículo
                </button>
                <button className="btn btn-danger w-full" onClick={() => setShowRejectModal(true)} disabled={working}>
                  <XCircle size={14} /> Rechazar
                </button>
              </div>
            </div>
          )}

          {/* Assign reviewer — available to the article author and admins */}
          {isAuthor && (
            <div className="card">
              <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)', marginBottom: 'var(--space-2)', display: 'flex', alignItems: 'center', gap: 6 }}>
                <UserPlus size={14} /> Asignar revisor
              </div>
              <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginBottom: 'var(--space-3)' }}>
                El artículo quedará en estado <strong>Pendiente</strong> hasta que el revisor apruebe.
              </div>
              <div style={{ display: 'flex', gap: 6 }}>
                <input className="input" style={{ flex: 1, padding: '6px 10px', fontSize: 'var(--font-size-xs)' }}
                  placeholder="email o nombre completo"
                  value={reviewerEmail}
                  onChange={e => setReviewerEmail(e.target.value)}
                  onKeyDown={e => e.key === 'Enter' && handleAssign()}
                  aria-label="Email o nombre del revisor"
                />
                <button className="btn btn-primary btn-sm" onClick={handleAssign} disabled={working} aria-label="Asignar revisor">
                  <UserPlus size={13} />
                </button>
              </div>
            </div>
          )}

          {/* Pipeline actions */}
          <div className="card">
            <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)', marginBottom: 'var(--space-3)' }}>Acciones</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              <button
                className="btn btn-ghost btn-sm w-full"
                onClick={handleViewPaper}
                aria-label="Ver el artículo maquetado como paper"
              >
                <FileText size={13} /> Ver maquetación
              </button>
              <button
                className="btn btn-ghost btn-sm w-full"
                onClick={handleDesignPaper}
                aria-label="Editar el diseño del paper con vista previa en vivo"
              >
                <Palette size={13} /> Diseñar paper
              </button>
              <button
                className="btn btn-ghost btn-sm w-full"
                onClick={handleOpenPipelineModal}
                disabled={working}
                aria-label="Ejecutar pipeline de agentes sobre este artículo"
              >
                <GitBranch size={13} /> Reejecutar pipeline
              </button>
            </div>
          </div>

          {/* Paper metadata (title block) */}
          <div className="card">
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 'var(--space-3)' }}>
              <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)' }}>Metadatos del paper</div>
              {isAuthor && !editingMeta && (
                <button className="btn btn-ghost btn-sm" onClick={handleEditMeta} aria-label="Editar metadatos del paper">
                  <Pencil size={12} /> Editar
                </button>
              )}
            </div>

            {!editingMeta ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', fontSize: 'var(--font-size-xs)' }}>
                <div>
                  <span style={{ color: 'var(--text-muted)' }}>Autores: </span>
                  <span style={{ color: 'var(--text-secondary)' }}>
                    {article.authors && article.authors.length
                      ? article.authors.map(a => a.name).join(', ')
                      : '—'}
                  </span>
                </div>
                <div>
                  <span style={{ color: 'var(--text-muted)' }}>Abstract: </span>
                  <span style={{ color: 'var(--text-secondary)' }}>
                    {article.abstract ? `${article.abstract.slice(0, 80)}${article.abstract.length > 80 ? '…' : ''}` : '—'}
                  </span>
                </div>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
                {/* Authors editor */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                  {authorsDraft.map((a, idx) => (
                    <div key={idx} style={{ display: 'flex', flexDirection: 'column', gap: 4, padding: '8px', background: 'var(--bg-surface)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--border-default)' }}>
                      <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>
                        <input className="input" style={{ flex: 1, padding: '4px 8px', fontSize: 'var(--font-size-xs)' }}
                          placeholder="Nombre" value={a.name}
                          onChange={e => updateAuthorField(idx, 'name', e.target.value)} aria-label={`Nombre autor ${idx + 1}`} />
                        <button className="btn btn-ghost btn-sm btn-icon" onClick={() => setAuthorsDraft(prev => prev.filter((_, i) => i !== idx))} aria-label={`Eliminar autor ${idx + 1}`}>
                          <Trash2 size={12} />
                        </button>
                      </div>
                      <input className="input" style={{ padding: '4px 8px', fontSize: 'var(--font-size-xs)' }}
                        placeholder="Afiliación" value={a.affiliation}
                        onChange={e => updateAuthorField(idx, 'affiliation', e.target.value)} aria-label={`Afiliación autor ${idx + 1}`} />
                      <input className="input" style={{ padding: '4px 8px', fontSize: 'var(--font-size-xs)' }}
                        placeholder="email" value={a.email}
                        onChange={e => updateAuthorField(idx, 'email', e.target.value)} aria-label={`Email autor ${idx + 1}`} />
                    </div>
                  ))}
                  <button className="btn btn-ghost btn-sm" onClick={() => setAuthorsDraft(prev => [...prev, { name: '', affiliation: '', email: '' }])}>
                    <Plus size={12} /> Añadir autor
                  </button>
                </div>

                {/* Abstract editor */}
                <div>
                  <label className="input-label" style={{ fontSize: 'var(--font-size-xs)' }}>Abstract</label>
                  <textarea className="input" rows={4}
                    style={{ width: '100%', fontSize: 'var(--font-size-xs)', boxSizing: 'border-box' }}
                    placeholder="Resumen del artículo…"
                    value={abstractDraft}
                    onChange={e => setAbstractDraft(e.target.value)} aria-label="Abstract del artículo" />
                </div>

                <div style={{ display: 'flex', gap: 6, justifyContent: 'flex-end' }}>
                  <button className="btn btn-ghost btn-sm" onClick={() => setEditingMeta(false)} disabled={working}>
                    <X size={12} /> Cancelar
                  </button>
                  <button className="btn btn-primary btn-sm" onClick={handleSaveMeta} disabled={working}>
                    <Save size={12} /> Guardar
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Metadata */}
          <div className="card">
            <div style={{ fontWeight: 600, fontSize: 'var(--font-size-sm)', marginBottom: 'var(--space-3)' }}>Detalles</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
              {[
                { label: 'Estado', value: st?.label },
                { label: 'Formato', value: (article.scientific_format && article.scientific_format !== 'none') ? article.scientific_format.toUpperCase() : '—' },
                { label: 'Palabras', value: article.body ? article.body.split(/\s+/).length : 0 },
                { label: 'Creado', value: new Date(article.created_at).toLocaleDateString('es-ES') },
                { label: 'Actualizado', value: new Date(article.updated_at).toLocaleDateString('es-ES') },
              ].map(item => (
                <div key={item.label} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 'var(--font-size-xs)' }}>
                  <span style={{ color: 'var(--text-muted)' }}>{item.label}</span>
                  <span style={{ color: 'var(--text-secondary)', fontWeight: 500 }}>{item.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Pipeline agent-select modal */}
      {showPipelineModal && (
        <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Seleccionar agentes" onKeyDown={e => e.key === 'Escape' && setShowPipelineModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Reejecutar pipeline</h3>
              <button className="btn btn-ghost btn-sm btn-icon" onClick={() => setShowPipelineModal(false)} aria-label="Cerrar">✕</button>
            </div>
            <div className="modal-body">
              {loadingRuns ? (
                <div style={{ textAlign: 'center', padding: 'var(--space-6)' }}><div className="spinner" /></div>
              ) : (
                <>
                  {usedDefaultFlow && (
                    <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--status-warning)', background: 'var(--status-warning-bg)', borderRadius: 'var(--radius-sm)', padding: '6px 10px', marginBottom: 'var(--space-3)' }}>
                      Sin historial previo — todos los agentes preseleccionados.
                    </div>
                  )}
                  <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)', marginBottom: 'var(--space-4)' }}>
                    Selecciona los agentes que quieres ejecutar. Se usarán en el orden mostrado.
                  </p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                    {pipelineAgents.map(agentId => (
                      <label key={agentId} style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', cursor: 'pointer', padding: '8px 12px', borderRadius: 'var(--radius-md)', background: selectedAgents.includes(agentId) ? 'var(--bg-overlay)' : 'transparent', fontSize: 'var(--font-size-sm)' }}>
                        <input
                          type="checkbox"
                          checked={selectedAgents.includes(agentId)}
                          onChange={e => setSelectedAgents(prev =>
                            e.target.checked ? [...prev, agentId] : prev.filter(a => a !== agentId)
                          )}
                          aria-label={`Incluir agente ${agentId}`}
                        />
                        {AGENT_LABELS[agentId] || agentId}
                      </label>
                    ))}
                  </div>
                </>
              )}
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setShowPipelineModal(false)}>Cancelar</button>
              <button className="btn btn-primary" onClick={handleConfirmPipeline} disabled={selectedAgents.length === 0}>
                <GitBranch size={14} /> Ejecutar
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Reject modal */}
      {showRejectModal && (
        <div className="modal-backdrop" onClick={() => setShowRejectModal(false)}>
          <div className="modal" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Rechazar artículo</h3>
              <button className="btn btn-ghost btn-sm btn-icon" onClick={() => setShowRejectModal(false)}>✕</button>
            </div>
            <div className="modal-body">
              <div className="input-group">
                <label className="input-label">Motivo del rechazo</label>
                <textarea className="input" rows={4}
                  placeholder="Explica los cambios necesarios..."
                  value={rejectComment}
                  onChange={e => setRejectComment(e.target.value)} />
              </div>
            </div>
            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setShowRejectModal(false)}>Cancelar</button>
              <button className="btn btn-danger" onClick={handleReject} disabled={working || !rejectComment.trim()}>
                <XCircle size={14} /> Confirmar rechazo
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
