// Generated by GitHub Copilot
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Database, Bot, Box, Shield, Save, LogOut, RefreshCw,
  Search, Cpu, ChevronDown, ChevronRight, Layers, Sparkles,
} from 'lucide-react';
import { configApi } from '../api/config';
import { useAuthStore } from '../store/authStore';
import { useProjectStore } from '../store/projectStore';
import toast from 'react-hot-toast';

// ── Nested-path helpers ──────────────────────────────────────────────────────

/** Read a dot-separated path from a nested object. */
function getPath(obj, path) {
  if (!path) return obj;
  return path.split('.').reduce((acc, key) => (acc == null ? undefined : acc[key]), obj);
}

/** Return a new object with the dot-separated path set to value (deep clone). */
function setPath(obj, path, value) {
  const keys = path.split('.');
  const result = structuredClone(obj || {});
  let curr = result;
  for (let i = 0; i < keys.length - 1; i++) {
    if (curr[keys[i]] == null || typeof curr[keys[i]] !== 'object') curr[keys[i]] = {};
    curr = curr[keys[i]];
  }
  curr[keys[keys.length - 1]] = value;
  return result;
}

// ── Section / field definitions ─────────────────────────────────────────────

const SECTIONS = [
  {
    id: 'app',
    label: 'Aplicación',
    icon: <Layers size={15} />,
    fields: [
      { path: 'app.name', label: 'Nombre', type: 'text', desc: 'Nombre de la plataforma (cosmético, aparece en logs y UI)' },
      { path: 'app.version', label: 'Versión', type: 'text', desc: 'Versión actual de la aplicación (ej: 0.2.0)' },
      { path: 'app.debug', label: 'Modo debug', type: 'toggle', desc: 'Activa logs detallados, endpoints /dev y stack traces completos en errores HTTP' },
    ],
  },
  {
    id: 'llm',
    label: 'Motor LLM',
    icon: <Cpu size={15} />,
    fields: [
      {
        path: 'llm.provider', label: 'Proveedor', type: 'select',
        desc: 'Motor LLM activo: anthropic (Claude, por defecto), ollama (local) u openai (API o servidor compatible)',
        options: [
          { value: 'anthropic', label: 'Claude (Anthropic)' },
          { value: 'ollama', label: 'Ollama (local)' },
          { value: 'openai', label: 'OpenAI API' },
        ],
      },
    ],
  },
  {
    id: 'anthropic',
    label: 'Claude (Anthropic)',
    icon: <Sparkles size={15} />,
    visibleWhen: cfg => (getPath(cfg, 'llm.provider') || 'anthropic') === 'anthropic',
    fields: [
      {
        // Read-only on purpose: config.yaml is tracked in git, so the key is
        // never writable from the UI — only its presence is reported (SPEC-023).
        path: 'anthropic.api_key', label: 'API Key', type: 'env-status',
        desc: 'Solo por variable de entorno: ANTHROPIC_API_KEY=sk-ant-… (nunca se guarda en config.yaml, que está versionado)',
      },
      { path: 'anthropic.model', label: 'Modelo por defecto', type: 'text', desc: 'Default global del proveedor (ej: claude-opus-5). El modelo por agente se define en su .agent.md' },
      { path: 'anthropic.max_tokens', label: 'Max tokens', type: 'number', desc: 'Anthropic exige max_tokens en cada llamada (por defecto 4096)' },
      { path: 'anthropic.base_url', label: 'Base URL (opcional)', type: 'text', desc: 'Dejar vacío para usar el endpoint oficial de Anthropic' },
    ],
  },
  {
    id: 'ollama',
    label: 'Ollama',
    icon: <Bot size={15} />,
    // Strict match: the default provider is anthropic, so an absent value must
    // not fall back to showing the Ollama section.
    visibleWhen: cfg => getPath(cfg, 'llm.provider') === 'ollama',
    fields: [
      { path: 'ollama.base_url', label: 'URL base', type: 'text', desc: 'http://localhost:11434' },
      { path: 'ollama.default_model', label: 'Modelo generación', type: 'model-select', desc: 'Modelo por defecto para todos los agentes' },
      { path: 'ollama.embed_model', label: 'Modelo embeddings', type: 'model-select', desc: 'Modelo para vectorización RAG (ej: nomic-embed-text)' },
    ],
  },
  {
    id: 'openai',
    label: 'OpenAI',
    icon: <Search size={15} />,
    visibleWhen: cfg => getPath(cfg, 'llm.provider') === 'openai',
    fields: [
      { path: 'openai.api_key', label: 'API Key', type: 'password', desc: 'sk-...' },
      { path: 'openai.model', label: 'Modelo generación', type: 'text', desc: 'ej: gpt-4o-mini' },
      { path: 'openai.embed_model', label: 'Modelo embeddings', type: 'text', desc: 'ej: text-embedding-3-small' },
      { path: 'openai.base_url', label: 'Base URL (opcional)', type: 'text', desc: 'Dejar vacío para usar la URL oficial de OpenAI' },
    ],
  },
  {
    id: 'qdrant',
    label: 'Qdrant (RAG)',
    icon: <Box size={15} />,
    fields: [
      { path: 'qdrant.url', label: 'URL', type: 'text', desc: 'http://localhost:6333' },
      { path: 'qdrant.collection', label: 'Colección', type: 'text', desc: 'Nombre de la colección vectorial' },
      { path: 'qdrant.vector_size', label: 'Dimensiones vector', type: 'number', desc: '768 para nomic-embed-text, 1536 para text-embedding-3-small' },
      { path: 'qdrant.api_key', label: 'API Key', type: 'password', desc: 'Dejar vacío si Qdrant es local sin autenticación' },
    ],
  },
  {
    id: 'rag',
    label: 'RAG global',
    icon: <Database size={15} />,
    fields: [
      { path: 'rag.chunk_size', label: 'Chunk size', type: 'number', desc: 'Tamaño de fragmento al indexar documentos (tokens aprox.)' },
      { path: 'rag.chunk_overlap', label: 'Chunk overlap', type: 'number', desc: 'Solapamiento entre fragmentos consecutivos' },
      { path: 'rag.top_k', label: 'Top-K resultados', type: 'number', desc: 'Número de fragmentos relevantes a recuperar por consulta' },
      { path: 'rag.score_threshold', label: 'Score mínimo', type: 'number-float', desc: 'Umbral de similitud para descartar resultados (0 = sin filtro)' },
    ],
  },
  {
    id: 'agent-investigador',
    label: 'Investigador',
    icon: <Search size={15} />,
    group: 'agents',
    fields: [
      { path: 'agents.investigador.model', label: 'Modelo', type: 'model-select-nullable', desc: 'Dejar vacío para usar el modelo global' },
      { path: 'agents.investigador.temperature', label: 'Temperature', type: 'number-float', desc: 'Creatividad del modelo (0.0 – 1.0)' },
      { path: 'agents.investigador.rag_enabled', label: 'RAG activado', type: 'toggle', desc: 'Consultar base vectorial en la fase de investigación' },
      { path: 'agents.investigador.rag_collection', label: 'Colección RAG', type: 'text', desc: 'Colección Qdrant específica (vacío = colección global)' },
      { path: 'agents.investigador.rag_top_k', label: 'Top-K RAG', type: 'number', desc: 'Fragmentos a recuperar (sobreescribe el global)' },
      { path: 'agents.investigador.rag_chunk_size', label: 'Chunk size', type: 'number', desc: 'Tamaño de chunk al indexar páginas scrapeadas' },
      { path: 'agents.investigador.semantic_rerank', label: 'Semantic re-rank', type: 'toggle', desc: 'Re-ordenar páginas scrapeadas por similitud semántica (coseno)' },
    ],
  },
  {
    id: 'agent-redactor',
    label: 'Redactor',
    icon: <Bot size={15} />,
    group: 'agents',
    fields: [
      { path: 'agents.redactor.model', label: 'Modelo', type: 'model-select-nullable', desc: 'Dejar vacío para usar el modelo global' },
      { path: 'agents.redactor.temperature', label: 'Temperature', type: 'number-float', desc: 'Creatividad del modelo (0.0 – 1.0)' },
      { path: 'agents.redactor.rag_enabled', label: 'RAG activado', type: 'toggle', desc: 'Usar contexto RAG al redactar' },
    ],
  },
  {
    id: 'agent-revisor',
    label: 'Revisor',
    icon: <Bot size={15} />,
    group: 'agents',
    fields: [
      { path: 'agents.revisor.model', label: 'Modelo', type: 'model-select-nullable', desc: 'Dejar vacío para usar el modelo global' },
      { path: 'agents.revisor.temperature', label: 'Temperature', type: 'number-float', desc: 'Creatividad del modelo (0.0 – 1.0)' },
      { path: 'agents.revisor.rag_enabled', label: 'RAG activado', type: 'toggle', desc: 'Usar contexto RAG al revisar' },
    ],
  },
  {
    id: 'agent-formateador',
    label: 'Formateador',
    icon: <Bot size={15} />,
    group: 'agents',
    fields: [
      { path: 'agents.formateador.model', label: 'Modelo', type: 'model-select-nullable', desc: 'Dejar vacío para usar el modelo global' },
      { path: 'agents.formateador.temperature', label: 'Temperature', type: 'number-float', desc: 'Creatividad del modelo (0.0 – 1.0)' },
      { path: 'agents.formateador.rag_enabled', label: 'RAG activado', type: 'toggle', desc: 'Usar contexto RAG al formatear' },
    ],
  },
  {
    id: 'agent-publicador',
    label: 'Publicador',
    icon: <Bot size={15} />,
    group: 'agents',
    fields: [
      { path: 'agents.publicador.model', label: 'Modelo', type: 'model-select-nullable', desc: 'Dejar vacío para usar el modelo global' },
      { path: 'agents.publicador.rag_enabled', label: 'RAG activado', type: 'toggle', desc: 'Usar contexto RAG al publicar' },
    ],
  },
  {
    id: 'database',
    label: 'Base de datos',
    icon: <Database size={15} />,
    fields: [
      { path: 'database.url', label: 'Database URL', type: 'text', desc: 'Cadena de conexión SQLAlchemy' },
    ],
  },
  {
    id: 'security',
    label: 'Seguridad JWT',
    icon: <Shield size={15} />,
    fields: [
      { path: 'security.secret_key', label: 'Secret Key', type: 'password', desc: 'Clave secreta para firmar tokens JWT — usa openssl rand -hex 32 para generar una segura' },
      { path: 'security.algorithm', label: 'Algoritmo', type: 'text', desc: 'Algoritmo de firma JWT (ej: HS256). Cambiar requiere revocar todos los tokens activos.' },
      { path: 'security.access_token_expire_minutes', label: 'Expiración access token (min)', type: 'number', desc: 'Tiempo de vida del token de acceso en minutos (por defecto: 30)' },
      { path: 'security.refresh_token_expire_days', label: 'Expiración refresh token (días)', type: 'number', desc: 'Tiempo de vida del token de refresco en días (por defecto: 7)' },
    ],
  },
  {
    id: 'access_control',
    label: 'Control de acceso',
    icon: <Shield size={15} />,
    fields: [
      { path: 'access_control.enable_dev_role_promotion', label: 'Dev Role Promotion', type: 'toggle', desc: 'Permite auto-promoción a reviewer via POST /api/v1/auth/dev/promote-reviewer. Solo activar en entornos de desarrollo.' },
    ],
  },
];

// ── FieldControl ─────────────────────────────────────────────────────────────

/**
 * Renders the appropriate input control for a field definition.
 * Handles: toggle, select, model-select, model-select-nullable, number, number-float, text, password.
 */
function FieldControl({ field, config, onChange, ollamaModels, modelsLoading, onReloadModels, llmStatus }) {
  const value = getPath(config, field.path);
  const isNullable = field.type === 'model-select-nullable';

  // Read-only indicator for secrets that live in the environment, never in
  // config.yaml (tracked in git). Reports presence only — never the value.
  if (field.type === 'env-status') {
    const isSet = !!llmStatus?.anthropic?.api_key_set;
    return (
      <span
        role="status"
        style={{
          display: 'inline-flex', alignItems: 'center', gap: 6,
          padding: '5px 10px', borderRadius: 6,
          fontSize: 'var(--font-size-xs)', fontFamily: 'var(--font-mono)',
          border: '1px solid var(--border-color, #d0d7de)',
          color: isSet ? 'var(--color-success, #1a7f37)' : 'var(--color-danger, #b42318)',
        }}
      >
        <span aria-hidden="true">{isSet ? '●' : '○'}</span>
        {isSet ? 'Configurada por entorno' : 'No configurada'}
      </span>
    );
  }

  if (field.type === 'toggle') {
    return (
      <button
        role="switch"
        aria-checked={!!value}
        className={`toggle-wrapper ${value ? 'on' : ''}`}
        onClick={() => onChange(field.path, !value)}
        tabIndex={0}
        aria-label={field.label}
        onKeyDown={e => (e.key === ' ' || e.key === 'Enter') && onChange(field.path, !value)}
        style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}
      >
        <div className={`toggle ${value ? 'on' : ''}`} />
      </button>
    );
  }

  if (field.type === 'select') {
    return (
      <select
        className="input"
        style={{ width: 200, padding: '6px 10px', fontSize: 'var(--font-size-xs)' }}
        value={value || ''}
        onChange={e => onChange(field.path, e.target.value)}
        aria-label={field.label}
      >
        {(field.options || []).map(o => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
    );
  }

  if (field.type === 'model-select' || isNullable) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
        {ollamaModels.length > 0 ? (
          <select
            className="input"
            style={{ width: 240, padding: '6px 10px', fontSize: 'var(--font-size-xs)' }}
            value={value || ''}
            onChange={e => onChange(field.path, e.target.value || null)}
            aria-label={field.label}
          >
            {isNullable && <option value="">(hereda modelo global)</option>}
            {value && !ollamaModels.includes(value) && (
              <option value={value}>{value} (actual)</option>
            )}
            {ollamaModels.map(m => <option key={m} value={m}>{m}</option>)}
          </select>
        ) : (
          <input
            className="input"
            type="text"
            style={{ width: 240, padding: '6px 10px', fontSize: 'var(--font-size-xs)' }}
            value={value || ''}
            placeholder={isNullable ? '(hereda modelo global)' : 'ej: mistral:7b'}
            onChange={e => onChange(field.path, e.target.value || null)}
            aria-label={field.label}
          />
        )}
        <button
          className="btn btn-ghost btn-sm"
          onClick={onReloadModels}
          disabled={modelsLoading}
          title="Recargar modelos instalados"
          aria-label="Recargar modelos Ollama"
          style={{ padding: '5px 8px' }}
        >
          <RefreshCw size={13} style={modelsLoading ? { animation: 'spin 1s linear infinite' } : {}} />
        </button>
        {ollamaModels.length > 0 && (
          <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
            {ollamaModels.length} detectado{ollamaModels.length === 1 ? '' : 's'}
          </span>
        )}
      </div>
    );
  }

  if (field.type === 'number' || field.type === 'number-float') {
    return (
      <input
        className="input"
        type="number"
        style={{ width: 120, padding: '6px 10px', fontSize: 'var(--font-size-xs)' }}
        value={value ?? ''}
        step={field.type === 'number-float' ? '0.05' : '1'}
        min={field.type === 'number-float' ? '0' : '1'}
        onChange={e => {
          const v = field.type === 'number-float'
            ? Number.parseFloat(e.target.value)
            : Number.parseInt(e.target.value, 10);
          onChange(field.path, Number.isNaN(v) ? null : v);
        }}
        aria-label={field.label}
      />
    );
  }

  // text / password
  return (
    <input
      className="input"
      type={field.type === 'password' ? 'password' : 'text'}
      style={{
        width: 280, padding: '6px 10px', fontSize: 'var(--font-size-xs)',
        fontFamily: field.type === 'password' ? 'var(--font-mono)' : 'inherit',
      }}
      value={value ?? ''}
      onChange={e => onChange(field.path, e.target.value)}
      aria-label={field.label}
    />
  );
}

// ── ConfigSection ─────────────────────────────────────────────────────────────

/**
 * Collapsible section card. Renders a header with chevron toggle and a list of field rows.
 */
function ConfigSection({ section, config, onChange, ollamaModels, modelsLoading, onReloadModels, llmStatus, defaultOpen = true }) {
  const [open, setOpen] = useState(defaultOpen);
  const isAgent = !!section.group;

  return (
    <div className="config-section" style={isAgent ? { borderLeft: '3px solid var(--color-accent, #6c63ff)' } : {}}>
      <button
        className="config-section-header"
        onClick={() => setOpen(o => !o)}
        aria-expanded={open}
        style={{
          width: '100%', background: 'none', border: 'none', cursor: 'pointer',
          textAlign: 'left', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}
      >
        <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          {section.icon}
          {section.label}
        </span>
        {open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
      </button>
      {open && (
        <div className="config-section-body">
          {section.fields.map(field => (
            <div className="config-row" key={field.path}>
              <div className="config-row-info">
                <div className="config-row-key">{field.label}</div>
                <div className="config-row-desc">{field.desc}</div>
              </div>
              <FieldControl
                field={field}
                config={config}
                onChange={onChange}
                ollamaModels={ollamaModels}
                modelsLoading={modelsLoading}
                onReloadModels={onReloadModels}
                llmStatus={llmStatus}
              />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── ConfigPage ────────────────────────────────────────────────────────────────

/**
 * Config page: reads/writes config.yaml via GET/PUT /api/v1/config.
 * Uses nested dot-notation paths to map fields to YAML structure.
 */
export default function ConfigPage() {
  const navigate = useNavigate();
  const { logout } = useAuthStore();
  const { activeProject } = useProjectStore();
  const [config, setConfig] = useState({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [ollamaModels, setOllamaModels] = useState([]);
  const [modelsLoading, setModelsLoading] = useState(false);
  const [llmStatus, setLlmStatus] = useState(null);

  const loadModels = () => {
    setModelsLoading(true);
    configApi.listModels()
      .then(data => setOllamaModels(data.models || []))
      .catch(() => setOllamaModels([]))
      .finally(() => setModelsLoading(false));
  };

  useEffect(() => {
    Promise.all([
      configApi.get(),
      configApi.listModels().catch(() => ({ models: [] })),
      configApi.llmStatus().catch(() => null),
    ])
      .then(([data, modelsData, status]) => {
        setConfig(data || {});
        setOllamaModels(modelsData.models || []);
        setLlmStatus(status);
        setLoading(false);
      })
      .catch(() => {
        setLoading(false);
        toast.error('No se pudo cargar la configuración');
      });
  }, []);

  const handleChange = (path, value) => setConfig(c => setPath(c, path, value));

  const handleSave = async () => {
    setSaving(true);
    try {
      await configApi.update(config);
      toast.success('Configuración guardada');
    } catch {
      toast.error('Error al guardar configuración');
    } finally {
      setSaving(false);
    }
  };

  const handleLogout = () => {
    const projectName = activeProject?.name;
    logout();
    toast.success('Sesión cerrada');
    navigate('/auth', projectName ? { state: { projectName } } : undefined);
  };

  if (loading) {
    return (
      <div className="page-body">
        <div className="empty-state"><div className="spinner spinner-lg" /></div>
      </div>
    );
  }

  const commonProps = {
    config,
    onChange: handleChange,
    ollamaModels,
    modelsLoading,
    onReloadModels: loadModels,
    llmStatus,
  };

  const mainSections = SECTIONS.filter(s => !s.group && (!s.visibleWhen || s.visibleWhen(config)));
  const agentSections = SECTIONS.filter(s => !!s.group);

  return (
    <div className="page-body" style={{ maxWidth: 820, margin: '0 auto' }}>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        marginBottom: 'var(--space-6)',
      }}>
        <div>
          <h2 style={{ marginBottom: 4 }}>Configuración</h2>
          <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>
            Parámetros del sistema (config.yaml)
          </p>
        </div>
        <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
          <button className="btn btn-ghost btn-sm" onClick={() => {
            configApi.get().then(data => { setConfig(data || {}); toast.success('Recargado'); });
          }}>
            <RefreshCw size={14} /> Recargar
          </button>
          <button className="btn btn-primary" onClick={handleSave} disabled={saving}>
            <Save size={14} /> {saving ? 'Guardando…' : 'Guardar'}
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
        {/* Main sections */}
        {mainSections.map(s => (
          <ConfigSection key={s.id} section={s} {...commonProps} defaultOpen />
        ))}

        {/* Agent defaults group */}
        {agentSections.length > 0 && (
          <div>
            <div style={{
              display: 'flex', alignItems: 'center', gap: 8,
              padding: 'var(--space-2) var(--space-1)',
              color: 'var(--text-muted)', fontSize: 'var(--font-size-xs)',
              textTransform: 'uppercase', letterSpacing: '0.08em', fontWeight: 600,
            }}>
              <Layers size={13} />
              Agentes — defaults globales (sobrescritos por agent_profile en BD)
            </div>

            {/* Explanation callout */}
            <div style={{
              background: 'var(--surface-2, #f5f5f5)',
              border: '1px solid var(--border-muted, #ddd)',
              borderLeft: '3px solid var(--color-accent, #6c63ff)',
              borderRadius: 6,
              padding: '8px 12px',
              marginBottom: 'var(--space-3)',
              fontSize: 'var(--font-size-xs)',
              color: 'var(--text-muted)',
              lineHeight: 1.5,
            }}>
              <strong style={{ color: 'var(--text-default)' }}>Prioridad en runtime:</strong>{' '}
              los perfiles de agente guardados en BD (editables en cada proyecto) <em>siempre</em> tienen
              prioridad sobre estos defaults. Estos valores solo aplican cuando el campo en BD está vacío
              o el agente no tiene perfil guardado.
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
              {agentSections.map(s => (
                <ConfigSection key={s.id} section={s} {...commonProps} defaultOpen={false} />
              ))}
            </div>
          </div>
        )}

        {/* Logout */}
        <div className="config-section">
          <div className="config-section-header" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <LogOut size={15} /> Sesión
          </div>
          <div className="config-section-body">
            <div className="config-row">
              <div className="config-row-info">
                <div className="config-row-key">Cerrar sesión</div>
                <div className="config-row-desc">Elimina el token de sesión actual</div>
              </div>
              <button className="btn btn-danger btn-sm" onClick={handleLogout}>
                <LogOut size={13} /> Cerrar sesión
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
