// Generated by GitHub Copilot
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Database, FileText, FolderOpen, Loader, RefreshCw, Trash2, Upload, X } from 'lucide-react';
import { agentsApi } from '../api/agents';
import toast from 'react-hot-toast';

/**
 * Global document library: shows all vectorised files stored in Qdrant (or local store)
 * grouped by collection. Users can upload new documents or delete existing ones.
 */
export default function DocumentsPage() {
  const [collections, setCollections] = useState([]);
  const [backend, setBackend] = useState('');
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [dragging, setDragging] = useState(false);
  const [uploadCollection, setUploadCollection] = useState('rag_docs');
  const [showUpload, setShowUpload] = useState(false);
  const inputRef = useRef(null);

  const loadLibrary = useCallback(async () => {
    setLoading(true);
    try {
      const data = await agentsApi.getLibraryDocs();
      setCollections(data.collections || []);
      setBackend(data.storage_backend || '');
    } catch {
      toast.error('No se pudo cargar la biblioteca vectorial');
      setCollections([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { loadLibrary(); }, [loadLibrary]);

  const handleFiles = async (files) => {
    for (const file of files) {
      setUploading(true);
      try {
        const res = await agentsApi.uploadLibraryDocument(file, uploadCollection || 'rag_docs');
        toast.success(`${res.filename} indexado · ${res.chunks} chunks en "${res.collection}"`);
      } catch (err) {
        toast.error(err?.response?.data?.detail || `Error al subir ${file.name}`);
      } finally {
        setUploading(false);
      }
    }
    await loadLibrary();
    setShowUpload(false);
  };

  const handleDelete = async (collection, docId, filename) => {
    if (!globalThis.confirm(`¿Eliminar "${filename}" de la colección "${collection}"?`)) return;
    try {
      await agentsApi.deleteLibraryDocument(collection, docId);
      toast.success('Documento eliminado');
      await loadLibrary();
    } catch {
      toast.error('No se pudo eliminar el documento');
    }
  };

  if (loading) {
    return (
      <div className="page-body">
        <div className="empty-state"><div className="spinner spinner-lg" /></div>
      </div>
    );
  }

  const totalDocs = collections.reduce((sum, c) => sum + c.documents.length, 0);

  return (
    <div className="page-body">
      {/* ── Header ── */}
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 'var(--space-4)', marginBottom: 'var(--space-6)', flexWrap: 'wrap' }}>
        <div>
          <h2 style={{ marginBottom: 4 }}>Biblioteca vectorial</h2>
          <p style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>
            {totalDocs > 0
              ? `${totalDocs} docs en ${collections.length} colecciones · vectores en ${backend}`
              : 'Documentos vectorizados disponibles para que cualquier agente los consuma como RAG.'}
          </p>
        </div>
        <div style={{ display: 'flex', gap: 'var(--space-2)' }}>
          <button className="btn btn-ghost btn-sm" onClick={loadLibrary} aria-label="Recargar">
            <RefreshCw size={14} />
          </button>
          <button className="btn btn-primary btn-sm" onClick={() => setShowUpload((v) => !v)}>
            <Upload size={14} /> Subir documento
          </button>
        </div>
      </div>

      {/* ── Upload panel ── */}
      {showUpload && (
        <div className="config-section" style={{ marginBottom: 'var(--space-5)' }}>
          <div className="config-section-header" style={{ justifyContent: 'space-between' }}>
            <span>Subir a la biblioteca</span>
            <button className="btn btn-ghost btn-sm btn-icon" onClick={() => setShowUpload(false)} aria-label="Cerrar">
              <X size={14} />
            </button>
          </div>
          <div className="config-section-body" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-3)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
              <label htmlFor="upload-collection" style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)', flexShrink: 0 }}>
                Colección:
              </label>
              <input
                id="upload-collection"
                className="input"
                value={uploadCollection}
                onChange={(e) => setUploadCollection(e.target.value)}
                placeholder="rag_docs"
                style={{ maxWidth: 200 }}
              />
            </div>

            <button
              type="button"
              aria-label="Zona de arrastre para subir archivos"
              onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={(e) => {
                e.preventDefault();
                setDragging(false);
                const files = Array.from(e.dataTransfer.files).filter((f) =>
                  ['.txt', '.md', '.pdf'].some((ext) => f.name.toLowerCase().endsWith(ext))
                );
                if (files.length) handleFiles(files);
                else toast.error('Solo .txt, .md y .pdf son aceptados');
              }}
              onClick={() => inputRef.current?.click()}
              style={{
                border: `2px dashed ${dragging ? 'var(--brand-primary)' : 'var(--border-subtle)'}`,
                borderRadius: 'var(--radius-md)', padding: 'var(--space-6)',
                textAlign: 'center', cursor: 'pointer', width: '100%',
                background: dragging ? 'var(--bg-overlay)' : 'transparent',
                transition: 'all 0.15s',
              }}
            >
              {uploading ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
                  <Loader size={20} style={{ color: 'var(--brand-primary)' }} />
                  <span style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>Indexando…</span>
                </div>
              ) : (
                <>
                  <Upload size={22} style={{ color: 'var(--text-muted)', marginBottom: 8 }} />
                  <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 500 }}>Arrastra archivos o haz clic</div>
                  <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginTop: 4 }}>.txt · .md · .pdf — máx. 10 MB</div>
                </>
              )}
              <input
                ref={inputRef}
                type="file"
                accept=".txt,.md,.pdf"
                multiple
                style={{ display: 'none' }}
                aria-label="Seleccionar archivos para la biblioteca RAG"
                onChange={(e) => { if (e.target.files?.length) handleFiles(Array.from(e.target.files)); }}
              />
            </button>
          </div>
        </div>
      )}

      {/* ── Collections list ── */}
      {collections.length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon"><Database size={28} /></div>
          <h3>Biblioteca vacía</h3>
          <p>Sube documentos con el botón de arriba para vectorizarlos y ponerlos a disposición de los agentes.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }}>
          {collections.map((col) => (
            <section key={col.name} className="config-section">
              <div className="config-section-header" style={{ justifyContent: 'space-between' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <FolderOpen size={15} />
                  <span style={{ fontWeight: 600 }}>{col.name}</span>
                </div>
                <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', fontWeight: 500 }}>
                  {col.documents.length === 1 ? '1 doc' : `${col.documents.length} docs`} · {col.total_chunks} chunks
                </div>
              </div>
              <div className="config-section-body">
                {col.documents.length === 0 ? (
                  <div style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)', fontStyle: 'italic' }}>
                    Colección vacía.
                  </div>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>
                    {col.documents.map((doc) => (
                      <div
                        key={doc.doc_id}
                        style={{
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 'var(--space-3)',
                          background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)',
                          borderRadius: 'var(--radius-md)', padding: 'var(--space-3) var(--space-4)',
                        }}
                      >
                        <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', minWidth: 0 }}>
                          <FileText size={15} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
                          <div style={{ minWidth: 0 }}>
                            <div style={{ fontWeight: 500, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                              {doc.filename}
                            </div>
                            <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
                              {doc.chunks} chunks
                              {doc.agent_name && doc.agent_name !== '__library__' && (
                                <span style={{ marginLeft: 8, opacity: 0.6 }}>· subido por {doc.agent_name}</span>
                              )}
                            </div>
                          </div>
                        </div>
                        <button
                          className="btn btn-ghost btn-sm btn-icon"
                          onClick={() => handleDelete(col.name, doc.doc_id, doc.filename)}
                          aria-label={`Eliminar ${doc.filename}`}
                        >
                          <Trash2 size={14} style={{ color: 'var(--error)' }} />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </section>
          ))}
        </div>
      )}
    </div>
  );
}
