// Generated by GitHub Copilot
import React, { useEffect, useState, useCallback } from 'react';
import { AsyncState, EmptyState } from '../components/ui/states';
import { mensajeDeCarga } from '../api/errors';
import ReactMarkdown from 'react-markdown';
import { ChevronLeft, ChevronRight, BookOpen, Loader } from 'lucide-react';
import api from '../api/client';

/**
 * Public magazine page — no authentication required.
 * Displays published articles as a full-screen slideshow.
 */
export default function MagazinePage() {
  const [articles, setArticles] = useState([]);
  const [current, setCurrent] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const cargar = useCallback(() => {
    setLoading(true);
    setError(null);
    api.get('/api/v1/magazine')
      .then(r => setArticles(r.data))
      // Esta es la portada pública: con `.catch(() => {})` un backend caído se
      // leía como «no hay artículos publicados aún», que es justo lo contrario
      // de lo que le interesa saber a quien llega de fuera.
      .catch(err => setError(mensajeDeCarga(err, 'No se pudo cargar la revista')))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { cargar(); }, [cargar]);

  const prev = useCallback(() => setCurrent(c => (c - 1 + articles.length) % articles.length), [articles.length]);
  const next = useCallback(() => setCurrent(c => (c + 1) % articles.length), [articles.length]);

  useEffect(() => {
    const handleKey = (e) => {
      if (e.key === 'ArrowRight') next();
      if (e.key === 'ArrowLeft')  prev();
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [next, prev]);

  const article = articles[current];

  return (
    <div style={{
      minHeight: '100vh',
      background: 'var(--bg-base)',
      display: 'flex',
      flexDirection: 'column',
    }}>
      {/* Topbar */}
      <header style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '16px 32px',
        borderBottom: '1px solid var(--border-subtle)',
        background: 'var(--bg-surface)',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <BookOpen size={20} style={{ color: 'var(--brand-primary)' }} />
          <span style={{ fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)' }}>
            Alej<span style={{ color: 'var(--brand-primary)' }}>andrIA</span> Magazine
          </span>
        </div>
        {!loading && articles.length > 0 && (
          <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
            {current + 1} / {articles.length}
          </span>
        )}
      </header>

      {/* Content */}
      <div style={{ flex: 1, display: 'flex', alignItems: 'stretch', position: 'relative', overflow: 'hidden' }}>

        {/* Prev button */}
        {articles.length > 1 && (
          <button
            onClick={prev}
            aria-label="Artículo anterior"
            style={{
              position: 'absolute', left: 16, top: '50%', transform: 'translateY(-50%)',
              zIndex: 10, background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
              borderRadius: '50%', width: 40, height: 40, display: 'flex', alignItems: 'center',
              justifyContent: 'center', cursor: 'pointer', color: 'var(--text-primary)',
            }}
          >
            <ChevronLeft size={20} />
          </button>
        )}

        {/* Article slide */}
        <div style={{
          flex: 1, display: 'flex', justifyContent: 'center', padding: '40px 80px',
          overflowY: 'auto',
        }}>
          <AsyncState
            loading={loading}
            error={error}
            isEmpty={articles.length === 0}
            onRetry={cargar}
            loadingLabel="Cargando la revista…"
            empty={(
              <EmptyState
                icon={<BookOpen size={28} />}
                title="No hay artículos publicados aún"
                description="Vuelve pronto: los artículos aparecen aquí en cuanto se publican."
              />
            )}
          >
            {(
            <article style={{ maxWidth: 780, width: '100%' }}>
              {/* Article header */}
              <div style={{ marginBottom: 32, paddingBottom: 24, borderBottom: '1px solid var(--border-subtle)' }}>
                {article.scientific_format && article.scientific_format !== 'none' && (
                  <span className="badge badge-approved" style={{ marginBottom: 12, display: 'inline-flex' }}>
                    {article.scientific_format.toUpperCase()}
                  </span>
                )}
                <h1 style={{ fontSize: '1.8rem', fontWeight: 700, color: 'var(--text-primary)', lineHeight: 1.3, margin: '8px 0 12px' }}>
                  {article.title}
                </h1>
                <div style={{ fontSize: 'var(--font-size-sm)', color: 'var(--text-muted)' }}>
                  Publicado el {new Date(article.published_at || article.created_at).toLocaleDateString('es-ES', { day: '2-digit', month: 'long', year: 'numeric' })}
                </div>
              </div>

              {/* Body */}
              <div className="markdown-body">
                <ReactMarkdown>{article.body}</ReactMarkdown>
              </div>
            </article>
            )}
          </AsyncState>
        </div>

        {/* Next button */}
        {articles.length > 1 && (
          <button
            onClick={next}
            aria-label="Artículo siguiente"
            style={{
              position: 'absolute', right: 16, top: '50%', transform: 'translateY(-50%)',
              zIndex: 10, background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
              borderRadius: '50%', width: 40, height: 40, display: 'flex', alignItems: 'center',
              justifyContent: 'center', cursor: 'pointer', color: 'var(--text-primary)',
            }}
          >
            <ChevronRight size={20} />
          </button>
        )}
      </div>

      {/* Dot pagination */}
      {articles.length > 1 && (
        <div style={{ display: 'flex', justifyContent: 'center', gap: 8, padding: '16px 0', background: 'var(--bg-surface)', borderTop: '1px solid var(--border-subtle)' }}>
          {articles.map((_, i) => (
            <button
              key={i}
              onClick={() => setCurrent(i)}
              aria-label={`Ir al artículo ${i + 1}`}
              style={{
                width: i === current ? 20 : 8, height: 8, borderRadius: 4,
                background: i === current ? 'var(--brand-primary)' : 'var(--border-default)',
                border: 'none', cursor: 'pointer', padding: 0,
                transition: 'width 0.2s, background 0.2s',
              }}
            />
          ))}
        </div>
      )}
    </div>
  );
}
