// Generated by GitHub Copilot
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  BookOpen, Plus, Trash2, ChevronRight, X, Loader,
  Newspaper, Code2, Megaphone, Ticket, Palette, Wand2,
} from 'lucide-react';
import { useProjectStore } from '../store/projectStore';
import { useAuthStore } from '../store/authStore';
import toast from 'react-hot-toast';

// ── Use-case catalogue ────────────────────────────────────────────────────────

const USE_CASES = [
  {
    value: 'alejandria_magazine',
    label: 'AlejandrIA Magazine',
    description: 'Flujo editorial completo para revista científica.',
    icon: <Newspaper size={22} />,
    color: 'var(--brand-primary)',
    disabled: true, // this is the system project, handled separately
  },
  {
    value: 'desarrollo',
    label: 'Desarrollo',
    description: 'Agentes orientados a ciclos de desarrollo de software.',
    icon: <Code2 size={22} />,
    color: '#2e844a',
  },
  {
    value: 'marketing',
    label: 'Marketing',
    description: 'Generación de contenido y campañas de marketing.',
    icon: <Megaphone size={22} />,
    color: '#c47d04',
  },
  {
    value: 'tiqueting',
    label: 'Tiqueting',
    description: 'Gestión y resolución automática de tickets de soporte.',
    icon: <Ticket size={22} />,
    color: '#0d9dda',
  },
  {
    value: 'diseno',
    label: 'Diseño',
    description: 'Flujos de revisión y producción de assets visuales.',
    icon: <Palette size={22} />,
    color: '#6b4fe3',
  },
  {
    value: 'custom',
    label: 'Custom',
    description: 'Crea tus propios agentes completamente desde cero.',
    icon: <Wand2 size={22} />,
    color: '#8793a5',
  },
];

const CASE_LABEL = Object.fromEntries(USE_CASES.map(u => [u.value, u.label]));
const CASE_ICON  = Object.fromEntries(USE_CASES.map(u => [u.value, u.icon]));
const CASE_COLOR = Object.fromEntries(USE_CASES.map(u => [u.value, u.color]));

// ── Modal ─────────────────────────────────────────────────────────────────────

function NewProjectModal({ onClose, onCreated }) {
  const { createProject, isLoading } = useProjectStore();
  const [step, setStep] = useState('type'); // 'type' | 'details'
  const [selectedType, setSelectedType] = useState(null);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');

  const options = USE_CASES.filter(u => u.value !== 'alejandria_magazine');

  const handleSelectType = (value) => {
    setSelectedType(value);
    setName(CASE_LABEL[value] + ' Project');
    setStep('details');
  };

  const handleCreate = async (e) => {
    e.preventDefault();
    if (!name.trim()) return;
    const result = await createProject(name.trim(), description.trim(), selectedType);
    if (result.ok) {
      toast.success('Proyecto creado');
      onCreated(result.project);
    } else {
      toast.error(result.error);
    }
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Crear nuevo proyecto"
      style={{
        position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 1000, padding: '1rem',
      }}
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div style={{
        background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)', padding: '2rem', width: '100%', maxWidth: 560,
        boxShadow: 'var(--shadow-lg)',
      }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
          <h2 style={{ margin: 0, color: 'var(--text-primary)', fontSize: '1.1rem', fontWeight: 600 }}>
            {step === 'type' ? 'Elige el tipo de proyecto' : 'Detalles del proyecto'}
          </h2>
          <button
            onClick={onClose}
            aria-label="Cerrar modal"
            style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-secondary)', padding: 4 }}
          >
            <X size={18} />
          </button>
        </div>

        {/* Step: choose type */}
        {step === 'type' && (
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
            {options.map(uc => (
              <button
                key={uc.value}
                onClick={() => handleSelectType(uc.value)}
                style={{
                  display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 6,
                  background: 'var(--bg-surface)', border: '1px solid var(--border-default)',
                  borderRadius: 'var(--radius-md)', padding: '1rem', cursor: 'pointer',
                  textAlign: 'left', transition: 'border-color 0.15s, background 0.15s',
                }}
                onMouseEnter={e => { e.currentTarget.style.borderColor = uc.color; e.currentTarget.style.background = 'var(--bg-overlay)'; }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-default)'; e.currentTarget.style.background = 'var(--bg-surface)'; }}
              >
                <span style={{ color: uc.color }}>{uc.icon}</span>
                <span style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '0.9rem' }}>{uc.label}</span>
                <span style={{ color: 'var(--text-muted)', fontSize: '0.78rem', lineHeight: 1.4 }}>{uc.description}</span>
              </button>
            ))}
          </div>
        )}

        {/* Step: details form */}
        {step === 'details' && (
          <form onSubmit={handleCreate} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {/* Selected type badge */}
            <div style={{ display: 'flex', alignItems: 'center', gap: 8,
              background: 'var(--bg-surface)', border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-md)', padding: '0.6rem 1rem' }}>
              <span style={{ color: CASE_COLOR[selectedType] }}>{CASE_ICON[selectedType]}</span>
              <span style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{CASE_LABEL[selectedType]}</span>
              <button
                type="button"
                onClick={() => setStep('type')}
                style={{ marginLeft: 'auto', background: 'none', border: 'none', cursor: 'pointer',
                  color: 'var(--text-muted)', fontSize: '0.78rem', textDecoration: 'underline' }}
              >
                Cambiar
              </button>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label htmlFor="proj-name" style={{ color: 'var(--text-secondary)', fontSize: '0.83rem' }}>
                Nombre del proyecto *
              </label>
              <input
                id="proj-name"
                value={name}
                onChange={e => setName(e.target.value)}
                required
                maxLength={255}
                autoFocus
                style={{
                  background: 'var(--bg-surface)', border: '1px solid var(--border-default)',
                  borderRadius: 'var(--radius-md)', padding: '0.6rem 0.85rem',
                  color: 'var(--text-primary)', fontSize: '0.9rem', outline: 'none',
                }}
              />
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              <label htmlFor="proj-desc" style={{ color: 'var(--text-secondary)', fontSize: '0.83rem' }}>
                Descripción (opcional)
              </label>
              <textarea
                id="proj-desc"
                value={description}
                onChange={e => setDescription(e.target.value)}
                rows={3}
                maxLength={1000}
                style={{
                  background: 'var(--bg-surface)', border: '1px solid var(--border-default)',
                  borderRadius: 'var(--radius-md)', padding: '0.6rem 0.85rem',
                  color: 'var(--text-primary)', fontSize: '0.9rem', outline: 'none', resize: 'vertical',
                }}
              />
            </div>

            <div style={{ display: 'flex', gap: '0.75rem', marginTop: 4 }}>
              <button
                type="button"
                onClick={() => setStep('type')}
                style={{
                  flex: 1, padding: '0.65rem', background: 'var(--bg-surface)',
                  border: '1px solid var(--border-default)', borderRadius: 'var(--radius-md)',
                  color: 'var(--text-secondary)', cursor: 'pointer', fontSize: '0.88rem',
                }}
              >
                Atrás
              </button>
              <button
                type="submit"
                disabled={isLoading || !name.trim()}
                style={{
                  flex: 2, padding: '0.65rem', background: 'var(--brand-gradient)',
                  border: 'none', borderRadius: 'var(--radius-md)',
                  color: '#fff', cursor: 'pointer', fontSize: '0.88rem',
                  fontWeight: 600, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                  opacity: isLoading || !name.trim() ? 0.6 : 1,
                }}
              >
                {isLoading ? <Loader size={15} style={{ animation: 'spin 1s linear infinite' }} /> : null}
                Crear proyecto
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}

// ── Project card ──────────────────────────────────────────────────────────────

function ProjectCard({ project, onSelect, onDelete }) {
  const color = CASE_COLOR[project.use_case_type] ?? 'var(--brand-primary)';
  const icon  = CASE_ICON[project.use_case_type]  ?? <BookOpen size={20} />;

  return (
    <div
      style={{
        background: 'var(--bg-elevated)', border: '1px solid var(--border-default)',
        borderRadius: 'var(--radius-lg)', padding: '1.25rem 1.5rem',
        display: 'flex', alignItems: 'center', gap: '1rem',
        cursor: 'pointer', transition: 'border-color 0.15s, background 0.15s',
        position: 'relative',
      }}
      onClick={() => onSelect(project)}
      role="button"
      tabIndex={0}
      aria-label={`Abrir proyecto ${project.name}`}
      onKeyDown={e => e.key === 'Enter' && onSelect(project)}
      onMouseEnter={e => { e.currentTarget.style.borderColor = color; e.currentTarget.style.background = 'var(--bg-overlay)'; }}
      onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-default)'; e.currentTarget.style.background = 'var(--bg-elevated)'; }}
    >
      {/* Icon badge */}
      <div style={{
        width: 44, height: 44, borderRadius: 'var(--radius-md)',
        background: `color-mix(in srgb, ${color} 15%, transparent)`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        color, flexShrink: 0,
      }}>
        {icon}
      </div>

      {/* Info */}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '0.95rem' }}>
            {project.name}
          </span>
          {project.is_system && (
            <span style={{
              fontSize: '0.7rem', padding: '2px 7px',
              background: 'var(--brand-primary-light)', color: 'var(--brand-primary)',
              borderRadius: 99, fontWeight: 600,
            }}>
              Sistema
            </span>
          )}
        </div>
        {project.description && (
          <p style={{
            color: 'var(--text-muted)', fontSize: '0.8rem', margin: '2px 0 0',
            overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
          }}>
            {project.description}
          </p>
        )}
      </div>

      {/* Delete (user projects only) */}
      {!project.is_system && (
        <button
          onClick={e => { e.stopPropagation(); onDelete(project); }}
          aria-label={`Eliminar proyecto ${project.name}`}
          style={{
            background: 'none', border: 'none', cursor: 'pointer',
            color: 'var(--text-muted)', padding: 6, borderRadius: 'var(--radius-sm)',
            flexShrink: 0,
          }}
          onMouseEnter={e => { e.currentTarget.style.color = 'var(--status-error)'; }}
          onMouseLeave={e => { e.currentTarget.style.color = 'var(--text-muted)'; }}
        >
          <Trash2 size={15} />
        </button>
      )}

      <ChevronRight size={16} style={{ color: 'var(--text-muted)', flexShrink: 0 }} />
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function ProjectSelectionPage() {
  const navigate = useNavigate();
  const { user, logout } = useAuthStore();
  const { projects, fetchProjects, selectProject, deleteProject, isLoading } = useProjectStore();
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    // Reset active project so the user must explicitly choose one
    selectProject(null);
    fetchProjects();
  }, []);

  const handleSelect = (project) => {
    selectProject(project);
    navigate('/dashboard/flow-designer');
  };

  const handleCreated = (project) => {
    selectProject(project);
    setShowModal(false);
    navigate('/dashboard/flow-designer');
  };

  const handleDelete = async (project) => {
    if (!window.confirm(`¿Eliminar "${project.name}"? Esta acción no se puede deshacer.`)) return;
    const result = await deleteProject(project.id);
    if (result.ok) toast.success('Proyecto eliminado');
    else toast.error(result.error);
  };

  const handleLogout = () => {
    logout();
    toast.success('Sesión cerrada');
    navigate('/auth');
  };

  const initials = user?.full_name?.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase() || 'U';

  return (
    <div style={{
      minHeight: '100vh', background: 'var(--bg-base)',
      display: 'flex', flexDirection: 'column',
    }}>
      {/* Top bar */}
      <header style={{
        padding: '0 2rem', height: 60, display: 'flex', alignItems: 'center',
        borderBottom: '1px solid var(--border-subtle)', background: 'var(--bg-surface)',
        justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 30, height: 30, borderRadius: 8, background: 'var(--brand-gradient)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <BookOpen size={15} color="white" />
          </div>
          <span style={{ color: 'var(--text-primary)', fontWeight: 700, fontSize: '1rem' }}>
            Alej<span style={{ color: 'var(--brand-accent)' }}>andrIA</span>
          </span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <span style={{ color: 'var(--text-secondary)', fontSize: '0.83rem' }}>{user?.email}</span>
          <div style={{
            width: 32, height: 32, borderRadius: '50%', background: 'var(--brand-gradient)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            color: '#fff', fontWeight: 700, fontSize: '0.8rem',
          }}>
            {initials}
          </div>
          <button
            onClick={handleLogout}
            style={{
              background: 'none', border: '1px solid var(--border-default)',
              borderRadius: 'var(--radius-md)', padding: '5px 12px',
              color: 'var(--text-secondary)', cursor: 'pointer', fontSize: '0.8rem',
            }}
          >
            Salir
          </button>
        </div>
      </header>

      {/* Content */}
      <main style={{ flex: 1, display: 'flex', justifyContent: 'center', padding: '3rem 1rem' }}>
        <div style={{ width: '100%', maxWidth: 680 }}>
          {/* Heading */}
          <div style={{ marginBottom: '2rem' }}>
            <h1 style={{ color: 'var(--text-primary)', fontWeight: 700, fontSize: '1.6rem', margin: 0 }}>
              Tus proyectos
            </h1>
            <p style={{ color: 'var(--text-muted)', margin: '6px 0 0', fontSize: '0.9rem' }}>
              Selecciona un proyecto para continuar o crea uno nuevo.
            </p>
          </div>

          {/* New project button */}
          <button
            onClick={() => setShowModal(true)}
            aria-label="Crear nuevo proyecto"
            style={{
              width: '100%', padding: '0.9rem 1.25rem',
              background: 'var(--bg-elevated)', border: '1.5px dashed var(--border-strong)',
              borderRadius: 'var(--radius-lg)', cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: 10,
              color: 'var(--text-secondary)', fontSize: '0.9rem', fontWeight: 500,
              marginBottom: '1.5rem', transition: 'border-color 0.15s, background 0.15s',
            }}
            onMouseEnter={e => { e.currentTarget.style.borderColor = 'var(--brand-primary)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
            onMouseLeave={e => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.color = 'var(--text-secondary)'; }}
          >
            <Plus size={18} />
            Nuevo proyecto
          </button>

          {/* Project list */}
          {isLoading && projects.length === 0 ? (
            <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem' }}>
              <Loader size={24} style={{ color: 'var(--text-muted)', animation: 'spin 1s linear infinite' }} />
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {projects.map(p => (
                <ProjectCard
                  key={p.id}
                  project={p}
                  onSelect={handleSelect}
                  onDelete={handleDelete}
                />
              ))}
              {projects.length === 0 && (
                <p style={{ color: 'var(--text-muted)', textAlign: 'center', padding: '2rem' }}>
                  No hay proyectos aún. ¡Crea el primero!
                </p>
              )}
            </div>
          )}
        </div>
      </main>

      {/* Modal */}
      {showModal && (
        <NewProjectModal
          onClose={() => setShowModal(false)}
          onCreated={handleCreated}
        />
      )}

      {/* Spinner keyframe */}
      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
