// Generated by GitHub Copilot
import React, { useEffect, useState, useCallback } from 'react';
import { Shield, User, BookOpen, Globe, Loader, ChevronDown, ChevronUp, X, FolderOpen } from 'lucide-react';
import { authApi } from '../api/auth';
import { projectsApi } from '../api/projects';
import toast from 'react-hot-toast';
import { useAuthStore } from '../store/authStore';

const ROLES = [
  { value: 'admin',    label: 'Admin',    icon: <Shield size={13} />,   desc: 'Acceso total a la plataforma y gestión de usuarios' },
  { value: 'redactor', label: 'Redactor', icon: <User size={13} />,     desc: 'Puede crear y editar artículos, ejecutar pipelines' },
  { value: 'lector',   label: 'Lector',   icon: <BookOpen size={13} />, desc: 'Solo lectura de artículos publicados' },
  { value: 'publico',  label: 'Público',  icon: <Globe size={13} />,    desc: 'Acceso únicamente a la revista pública' },
];

const ROLE_BADGE = {
  admin:    'badge-published',
  redactor: 'badge-approved',
  lector:   'badge-pending',
  publico:  'badge-draft',
};

/**
 * Admin-only page for listing and managing platform users.
 * Allows role assignment and project access management per user.
 */
export default function UsersPage() {
  const { user: me } = useAuthStore();
  const [users, setUsers] = useState([]);
  const [allProjects, setAllProjects] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(null); // userId being saved
  // expandedUser -> { projects: [...], loading: bool }
  const [expandedUser, setExpandedUser] = useState(null);
  const [userProjects, setUserProjects] = useState({}); // userId -> ProjectResponse[]
  const [addingProject, setAddingProject] = useState(null); // userId being granted

  useEffect(() => {
    Promise.all([authApi.listUsers(), projectsApi.list()])
      .then(([us, ps]) => { setUsers(us); setAllProjects(ps); })
      .catch(() => toast.error('Error al cargar datos'))
      .finally(() => setLoading(false));
  }, []);

  const handleRoleChange = async (userId, newRole) => {
    setSaving(userId);
    try {
      const updated = await authApi.assignRole(userId, newRole);
      setUsers(prev => prev.map(u => u.id === userId ? { ...u, role: updated.role } : u));
      toast.success(`Rol actualizado a "${newRole}"`);
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Error al actualizar rol');
    } finally {
      setSaving(null);
    }
  };

  const toggleUserProjects = useCallback(async (userId) => {
    if (expandedUser === userId) {
      setExpandedUser(null);
      return;
    }
    setExpandedUser(userId);
    if (userProjects[userId]) return; // already loaded
    try {
      const projects = await authApi.getUserProjects(userId);
      setUserProjects(prev => ({ ...prev, [userId]: projects }));
    } catch {
      toast.error('Error al cargar proyectos del usuario');
    }
  }, [expandedUser, userProjects]);

  const handleGrant = async (userId, projectId) => {
    setAddingProject(userId);
    try {
      await authApi.grantProject(userId, projectId);
      const projects = await authApi.getUserProjects(userId);
      setUserProjects(prev => ({ ...prev, [userId]: projects }));
      toast.success('Acceso al proyecto concedido');
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Error al conceder acceso');
    } finally {
      setAddingProject(null);
    }
  };

  const handleRevoke = async (userId, projectId) => {
    try {
      await authApi.revokeProject(userId, projectId);
      setUserProjects(prev => ({
        ...prev,
        [userId]: (prev[userId] || []).filter(p => p.id !== projectId),
      }));
      toast.success('Acceso al proyecto revocado');
    } catch (err) {
      toast.error(err?.response?.data?.detail || 'Error al revocar acceso');
    }
  };

  if (loading) {
    return (
      <div className="page-body">
        <div className="empty-state"><div className="spinner spinner-lg" /></div>
      </div>
    );
  }

  return (
    <div className="page-body" style={{ width: '100%', maxWidth: 1140, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: 'var(--space-6)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
          <Shield size={20} style={{ color: 'var(--brand-primary)' }} />
          <h2 style={{ margin: 0, fontSize: 'var(--font-size-xl)' }}>Gestión de usuarios</h2>
        </div>
        <p style={{ color: 'var(--text-muted)', fontSize: 'var(--font-size-sm)', margin: 0 }}>
          Asigna roles y acceso a proyectos para los usuarios de la plataforma.
        </p>
      </div>

      {/* Role legend */}
      <div className="card" style={{ padding: 'var(--space-4)', marginBottom: 'var(--space-5)' }}>
        <div style={{ fontWeight: 600, fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', marginBottom: 'var(--space-3)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Permisos por rol
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))', gap: 'var(--space-3)' }}>
          {ROLES.map(r => (
            <div key={r.value} style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
              <span className={`badge ${ROLE_BADGE[r.value]}`} style={{ marginTop: 2, flexShrink: 0 }}>
                {r.icon} {r.label}
              </span>
              <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', lineHeight: 1.5 }}>
                {r.desc}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Users table */}
      <div className="card" style={{ overflow: 'hidden' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ borderBottom: '1px solid var(--border-default)' }}>
              {['Usuario', 'Email', 'Rol', 'Proyectos', ''].map(h => (
                <th key={h} style={{ padding: '10px 16px', textAlign: 'left', fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {users.map(u => {
              const isMe = u.id === me?.id;
              return (
                <React.Fragment key={u.id}>
                <tr style={{ borderBottom: expandedUser === u.id ? 'none' : '1px solid var(--border-subtle)' }}>
                  {/* Name + initials */}
                  <td style={{ padding: '12px 16px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                      <div className="avatar" style={{ width: 30, height: 30, fontSize: '0.7rem' }}>
                        {u.full_name?.split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase()}
                      </div>
                      <div>
                        <div style={{ fontSize: 'var(--font-size-sm)', fontWeight: 600, color: 'var(--text-primary)' }}>
                          {u.full_name} {isMe && <span style={{ color: 'var(--text-muted)', fontWeight: 400, fontSize: 'var(--font-size-xs)' }}>(tú)</span>}
                        </div>
                        <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
                          {new Date(u.created_at).toLocaleDateString('es-ES')}
                        </div>
                      </div>
                    </div>
                  </td>

                  {/* Email */}
                  <td style={{ padding: '12px 16px', fontSize: 'var(--font-size-sm)', color: 'var(--text-secondary)' }}>
                    {u.email}
                  </td>

                  {/* Current role badge */}
                  <td style={{ padding: '12px 16px' }}>
                    <span className={`badge ${ROLE_BADGE[u.role] || 'badge-draft'}`}>
                      {ROLES.find(r => r.value === u.role)?.icon}
                      {' '}{u.role}
                    </span>
                  </td>

                  {/* Projects toggle */}
                  <td style={{ padding: '12px 16px' }}>
                    {!isMe && (
                      <button
                        className="btn btn-ghost"
                        style={{ padding: '4px 10px', fontSize: 'var(--font-size-xs)', display: 'flex', alignItems: 'center', gap: 5 }}
                        onClick={() => toggleUserProjects(u.id)}
                        aria-expanded={expandedUser === u.id}
                        aria-label={`Gestionar proyectos de ${u.full_name}`}
                      >
                        <FolderOpen size={13} />
                        Proyectos
                        {expandedUser === u.id ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
                      </button>
                    )}
                  </td>

                  {/* Role selector */}
                  <td style={{ padding: '12px 16px', textAlign: 'right' }}>
                    {isMe ? (
                      <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>
                        No puedes cambiar tu propio rol
                      </span>
                    ) : (
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, justifyContent: 'flex-end' }}>
                        {saving === u.id && <Loader size={14} style={{ animation: 'spin 1s linear infinite', color: 'var(--brand-primary)' }} />}
                        <select
                          className="input"
                          style={{ padding: '4px 8px', fontSize: 'var(--font-size-xs)', width: 120 }}
                          value={u.role}
                          disabled={saving === u.id}
                          onChange={e => handleRoleChange(u.id, e.target.value)}
                          aria-label={`Rol de ${u.full_name}`}
                        >
                          {ROLES.map(r => (
                            <option key={r.value} value={r.value}>{r.label}</option>
                          ))}
                        </select>
                      </div>
                    )}
                  </td>
                </tr>

                {/* Expanded project access panel */}
                {expandedUser === u.id && (
                  <tr>
                    <td colSpan={5} style={{ padding: '0 16px 16px 56px', borderBottom: '1px solid var(--border-subtle)', background: 'var(--surface-secondary)' }}>
                      <div style={{ paddingTop: 12 }}>
                        <p style={{ fontSize: 'var(--font-size-xs)', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.04em', marginBottom: 10 }}>
                          Acceso a proyectos
                        </p>

                        {/* Granted projects chips */}
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 12 }}>
                          {userProjects[u.id] === undefined && <div className="spinner" />}
                          {userProjects[u.id] !== undefined && userProjects[u.id].length === 0 && (
                            <span style={{ fontSize: 'var(--font-size-xs)', color: 'var(--text-muted)' }}>Sin proyectos asignados</span>
                          )}
                          {userProjects[u.id] !== undefined && userProjects[u.id].length > 0 && userProjects[u.id].map(p => (
                              <span
                                key={p.id}
                                style={{
                                  display: 'inline-flex', alignItems: 'center', gap: 6,
                                  background: 'var(--surface-tertiary)', border: '1px solid var(--border-default)',
                                  borderRadius: 20, padding: '3px 10px', fontSize: 'var(--font-size-xs)',
                                  color: 'var(--text-secondary)',
                                }}
                              >
                                {p.name}
                                <button
                                  onClick={() => handleRevoke(u.id, p.id)}
                                  style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: 0, display: 'flex', alignItems: 'center' }}
                                  aria-label={`Revocar acceso a ${p.name}`}
                                >
                                  <X size={11} />
                                </button>
                              </span>
                            ))}
                        </div>

                        {/* Add project select */}
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <select
                            id={`add-project-${u.id}`}
                            className="input"
                            style={{ padding: '4px 8px', fontSize: 'var(--font-size-xs)', maxWidth: 260 }}
                            defaultValue=""
                            aria-label={`Añadir proyecto a ${u.full_name}`}
                            onChange={e => {
                              if (e.target.value) {
                                handleGrant(u.id, e.target.value);
                                e.target.value = '';
                              }
                            }}
                            disabled={addingProject === u.id}
                          >
                            <option value="" disabled>Añadir proyecto…</option>
                            {allProjects
                              .filter(p => !(userProjects[u.id] || []).some(up => up.id === p.id))
                              .map(p => (
                                <option key={p.id} value={p.id}>{p.name}</option>
                              ))
                            }
                          </select>
                          {addingProject === u.id && <Loader size={14} style={{ animation: 'spin 1s linear infinite', color: 'var(--brand-primary)' }} />}
                        </div>
                      </div>
                    </td>
                  </tr>
                )}
                </React.Fragment>
              );
            })}
          </tbody>
        </table>
        {users.length === 0 && (
          <div className="empty-state" style={{ padding: 'var(--space-8)' }}>
            <p style={{ color: 'var(--text-muted)' }}>No hay usuarios registrados.</p>
          </div>
        )}
      </div>
    </div>
  );
}
