from contextlib import asynccontextmanager
import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import select

from app.database import init_db
# Import models to ensure they are registered on Base.metadata
from app import models
from app.core.config import settings
from app.core.security import hash_password
from app.routers import auth, articles, ai, agents, flows, config, notifications, checkpoints, projects
from app.routers.magazine import router as magazine_router
from app.shared.database import AsyncSessionLocal
from app.shared.agents_seed import seed_agents_for_project
from app.models import UserModel, UserRole, ProjectModel, ProjectUseCaseType, AgentProfileModel


# Generated by GitHub Copilot
async def ensure_local_admin_user() -> None:
    """Ensure the local SQLite dev environment always has an admin login."""
    if not settings.DATABASE_URL.startswith("sqlite"):
        return

    # Read password from env; fall back to a dev-only default
    admin_password = os.environ.get("DEV_ADMIN_PASSWORD", "admin123")

    async with AsyncSessionLocal() as session:
        result = await session.execute(select(UserModel).where(UserModel.email == "admin@admin"))
        user = result.scalars().first()

        if user is None:
            user = UserModel(
                email="admin@admin",
                hashed_password=hash_password(admin_password),
                full_name="Admin",
                role=UserRole.ADMIN,
                is_active=True,
            )
            session.add(user)
        else:
            user.hashed_password = hash_password(admin_password)
            user.full_name = "Admin"
            user.role = UserRole.ADMIN
            user.is_active = True

        await session.commit()


# Generated by GitHub Copilot
async def ensure_alejandria_magazine_project() -> None:
    """Ensure the AlejandrIA Magazine system project always exists."""
    async with AsyncSessionLocal() as session:
        result = await session.execute(
            select(ProjectModel).where(ProjectModel.is_system == True)  # noqa: E712
        )
        existing = result.scalars().first()
        if existing is None:
            project = ProjectModel(
                name="AlejandrIA Magazine",
                description="Proyecto de revista científica con flujo editorial completo.",
                use_case_type=ProjectUseCaseType.ALEJANDRIA_MAGAZINE,
                owner_id=None,
                is_system=True,
            )
            session.add(project)
            await session.commit()
            await session.refresh(project)
            await seed_agents_for_project(project.id, ProjectUseCaseType.ALEJANDRIA_MAGAZINE)
        else:
            # Seed if not yet seeded
            await seed_agents_for_project(existing.id, ProjectUseCaseType.ALEJANDRIA_MAGAZINE)


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize DB tables on startup
    await init_db()
    await ensure_local_admin_user()
    await ensure_alejandria_magazine_project()
    yield


app = FastAPI(title="AlejandrIA Magazine API", version="0.1.0", lifespan=lifespan)

# CORS: restrict origins in production via ALLOWED_ORIGINS env var
# Development default allows the local Vite dev server on ports 5173 and 5174.
_raw_origins = os.environ.get(
    "ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174",
)
_allowed_origins = [o.strip() for o in _raw_origins.split(",") if o.strip()]

app.add_middleware(
    CORSMiddleware,
    allow_origins=_allowed_origins,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

# Registrar routers
app.include_router(auth.router)
app.include_router(articles.router)
app.include_router(ai.router)
app.include_router(agents.router)
app.include_router(flows.router)
app.include_router(config.router)
app.include_router(notifications.router)
app.include_router(checkpoints.router)
app.include_router(projects.router)
app.include_router(magazine_router)



@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "alejandria_backend"}