import asyncio
import logging
import hashlib
import httpx
from typing import Dict, Any, List

from app.core.config import settings
from app.modules.agents.adapters.rag import (
    semantic_search_context, chunk_text, ensure_collection, upsert_chunks,
)

logger = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _doc_id_for(text: str, prefix: str = "discovered") -> str:
    """Deterministic doc_id derived from content hash — avoids duplicate indexing."""
    return f"{prefix}-{hashlib.sha256(text.encode()).hexdigest()[:16]}"


async def _index_text(
    text: str,
    filename: str,
    doc_id: str,
    collection: str,
    chunk_size: int = 400,
) -> None:
    """Chunk a text snippet and upsert it into Qdrant asynchronously (fire-and-forget)."""
    try:
        await ensure_collection(
            settings.QDRANT_URL, collection,
            settings.RAG_VECTOR_SIZE, settings.QDRANT_API_KEY,
        )
        overlap = max(40, chunk_size // 10)
        chunks = chunk_text(text, chunk_size=chunk_size, overlap=overlap)
        if chunks:
            await upsert_chunks(
                qdrant_url=settings.QDRANT_URL,
                collection=collection,
                doc_id=doc_id,
                agent_name="investigador",
                filename=filename,
                chunks=chunks,
                ollama_base_url=settings.OLLAMA_BASE_URL,
                embedding_model=settings.OLLAMA_EMBED_MODEL,
                vector_size=settings.RAG_VECTOR_SIZE,
                api_key=settings.QDRANT_API_KEY,
            )
            logger.info(
                "Auto-indexed '%s' (%d chunks, size=%d) into '%s'",
                filename, len(chunks), chunk_size, collection,
            )
    except Exception as exc:
        logger.warning("Auto-index failed for '%s': %s", filename, exc)


# Generated by GitHub Copilot
async def run_investigador(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Investigador Agent — three-stage research pipeline:

    1. Local RAG (Qdrant)   — semantic search of existing knowledge base.
    2. EuropePMC API        — peer-reviewed papers; auto-indexed into Qdrant.
    3. Deterministic scraping — DDG HTML search → extract real URLs → fetch
       each page → index with large chunks (1 200 chars) for deep coverage.
       This does NOT depend on LLM tool calling; every step is Python-level.
    4. LLM synthesis        — summarise all collected material (optional,
       falls back gracefully if model is too small).

    Content from stages 2-3 is indexed immediately (fire-and-forget) so
    subsequent pipeline runs start with a richer local knowledge base.
    """
    article_id = state.get("article_id")
    title = state.get("title") or ""
    keywords = state.get("keywords") or []
    log = state.get("_log") or (lambda msg, level="info": None)

    logger.info("Running Investigador for article %s with keywords %s", article_id, keywords)
    log(f"🔑 Keywords: {', '.join(keywords) if keywords else '(ninguna)'}")

    # Build query: title words + unique keywords (deduped, title takes priority)
    title_words = [w.strip(".,;:?!()[]") for w in title.split() if len(w) > 3] if title else []
    kw_words = [k for k in keywords if k.lower() not in {w.lower() for w in title_words}]
    combined_terms = title_words + kw_words
    query_str = " ".join(combined_terms) if combined_terms else "scientific research"
    log(f"🔍 Query de búsqueda: \"{query_str[:100]}\"")

    agent_cfg = (state.get("agent_settings") or {}).get("investigador", {})
    context_hint = (agent_cfg.get("context_hint") or "").strip()

    # semantic_rerank: agent_profile > config.yaml global default
    _agent_rerank = agent_cfg.get("semantic_rerank")
    if _agent_rerank is None:
        semantic_rerank = settings.SCRAPER_SEMANTIC_RERANK
    else:
        semantic_rerank = bool(_agent_rerank)
    if context_hint:
        query_str = f"{context_hint} {query_str}"
        logger.info("Investigador context hint: '%s'", context_hint[:80])
        log(f"💡 Context hint aplicado: \"{context_hint[:80]}\"")

    sources: List[Dict[str, Any]] = []
    research_chunks: List[str] = []

    # Resolve RAG collection
    rag_collection = (agent_cfg.get("rag_collection") or "").strip() or settings.QDRANT_COLLECTION
    rag_top_k = int(agent_cfg.get("rag_top_k") or 0) or settings.RAG_TOP_K
    rag_chunk_size = int(agent_cfg.get("rag_chunk_size") or 0) or settings.RAG_CHUNK_SIZE
    rag_doc_ids = agent_cfg.get("rag_doc_ids") or None
    if isinstance(rag_doc_ids, list) and len(rag_doc_ids) == 0:
        rag_doc_ids = None

    # ── Stage 1: Local RAG ───────────────────────────────────────────────────
    log(f"🔎 Etapa 1/3 — Buscando en base de conocimiento local (colección: {rag_collection})...")
    try:
        rag_context = await semantic_search_context(
            query=query_str,
            qdrant_url=settings.QDRANT_URL,
            collection=rag_collection,
            agent_name="investigador",
            ollama_base_url=settings.OLLAMA_BASE_URL,
            embedding_model=settings.OLLAMA_EMBED_MODEL,
            limit=rag_top_k,
            api_key=settings.QDRANT_API_KEY,
            doc_ids=rag_doc_ids,
        )
        if rag_context:
            rag_parts = [p for p in rag_context.split("\n\n---\n\n") if p]
            for index, text in enumerate(rag_parts):
                research_chunks.append(f"[RAG Source: local-{index}] {text}")
                sources.append({
                    "title": f"Local Document Chunk ({index + 1})",
                    "authors": "Biblioteca Local",
                    "journal": "Base de Conocimiento",
                    "year": "N/A",
                    "doi": "",
                    "url": f"local://investigador/{index + 1}",
                    "snippet": text[:200],
                })
            log(f"✅ RAG local: {len(rag_parts)} fragmento(s) encontrado(s).")
        else:
            log("ℹ️ RAG local sin resultados para esta consulta.")
    except Exception as exc:
        logger.warning("Could not search Qdrant: %s", exc)
        log(f"⚠️ RAG local no disponible: {exc}", "warning")

    # ── Stage 2: EuropePMC ───────────────────────────────────────────────────
    log("🌐 Etapa 2/3 — Consultando EuropePMC para papers científicos...")
    try:
        url = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"
        params = {"query": query_str, "format": "json", "pageSize": 3}
        async with httpx.AsyncClient(timeout=8.0) as client:
            res = await client.get(url, params=params)
            if res.status_code == 200:
                results = res.json().get("resultList", {}).get("result", [])
                for paper in results:
                    title = paper.get("title", "Untitled Paper")
                    author_string = paper.get("authorString", "Unknown Authors")
                    journal = paper.get("journalTitle", "Unknown Journal")
                    pub_year = paper.get("pubYear", "N/A")
                    doi = paper.get("doi")
                    abstract = paper.get("abstractText", "No abstract available.")

                    paper_url = f"https://doi.org/{doi}" if doi else "https://europepmc.org"
                    full_text = (
                        f"Title: {title}\nAuthors: {author_string}\n"
                        f"Journal: {journal} ({pub_year})\nAbstract: {abstract}"
                    )
                    research_chunks.append(
                        f"[EuropePMC] {title}\nAuthors: {author_string}\n"
                        f"Journal: {journal} ({pub_year})\nAbstract: {abstract[:300]}..."
                    )
                    sources.append({
                        "title": title,
                        "authors": author_string,
                        "journal": journal,
                        "year": pub_year,
                        "doi": doi or "",
                        "url": paper_url,
                        "snippet": abstract[:200],
                    })

                    # Auto-index abstract into Qdrant for future RAG reuse
                    doc_id = _doc_id_for(full_text, prefix="europepmc")
                    asyncio.ensure_future(_index_text(
                        full_text, f"[EuropePMC] {title[:80]}.txt", doc_id, rag_collection
                    ))

                if results:
                    log(f"✅ EuropePMC: {len(results)} paper(s) encontrado(s). Indexando en background...")
                    for paper in results:
                        log(f"  📄 {paper.get('title', 'Untitled')} ({paper.get('pubYear', '?')})")
                else:
                    log("ℹ️ EuropePMC no devolvió resultados para esta consulta.")
    except Exception as exc:
        logger.warning("Could not search EuropePMC: %s", exc)
        log(f"⚠️ EuropePMC no disponible: {exc}", "warning")

    # ── Stage 3: Graph-based web scraping ────────────────────────────────────
    # Uses requests + BeautifulSoup + NetworkX BFS to crawl relevant pages.
    # Falls back to Playwright headless Chromium for JS-heavy pages.
    # No LLM in the loop — pure deterministic scraping, always works.
    from app.modules.agents.adapters.scraper import graph_scrape

    log("🕸️ Etapa 3/3 — Scraping web con grafo de navegación (requests + bs4 + playwright)...")
    try:
        scraped_pages = await graph_scrape(
            query=query_str,
            keywords=keywords or [],
            max_pages=10,
            max_depth=2,
            min_relevance=0.05,
            use_playwright=True,
            ollama_base_url=settings.OLLAMA_BASE_URL,
            embed_model=settings.OLLAMA_EMBED_MODEL,
            semantic_rerank=semantic_rerank,
            log_fn=log,
        )
        added = 0
        for page in scraped_pages:
            if len(page.text.split()) < 30:
                continue
            chunk_header = f"[Web: {page.title or page.url}] (relevance={page.relevance:.2f})"
            research_chunks.append(f"{chunk_header}\nURL: {page.url}\n\n{page.text[:3000]}")
            import datetime
            sources.append({
                "title": page.title or "Página Web",
                "authors": "N/A",
                "journal": "Búsqueda Web",
                "year": datetime.datetime.now().year,
                "doi": "",
                "url": page.url,
                "snippet": page.snippet(200),
            })
            # Auto-index into Qdrant for future RAG reuse
            doc_id = _doc_id_for(page.text, prefix="scrape")
            asyncio.ensure_future(_index_text(
                page.text, f"[Scrape] {(page.title or page.url)[:80]}.txt",
                doc_id, rag_collection, chunk_size=rag_chunk_size,
            ))
            added += 1

        if added:
            log(f"✅ Scraping completado — {added} página(s) con contenido relevante.")
        else:
            log("ℹ️ Scraping no obtuvo páginas con contenido suficiente.", "warning")
    except Exception as exc:
        exc_desc = str(exc) or type(exc).__name__
        logger.warning("Graph scrape failed (non-critical): %s", exc_desc)
        log(f"⚠️ Scraping fallido: {exc_desc}", "warning")

    # ── Stage 4: LLM synthesis ────────────────────────────────────────────────
    # Always run synthesis — with or without external sources.
    # If no external content was found, the LLM uses its parametric knowledge.
    try:
        from app.shared.llm import call_llm, get_default_model
        model = (agent_cfg.get("model") or "").strip() or get_default_model()

        # When there are no external sources, use a lightweight model for
        # parametric synthesis to avoid OOM when the next agent loads.
        # The investigador model (often mistral:7b) would stay in VRAM
        # and crash the redactor's KV-cache allocation.
        _SYNTHESIS_FALLBACK_MODEL = "llama3.2:1b"

        if research_chunks:
            log(f"🧠 Etapa 4/4 — Síntesis con LLM ({model}) de {len(research_chunks)} fragmento(s)...")
            synthesis_model = model
            combined = "\n\n---\n\n".join(research_chunks[:8])
            synthesis_prompt = (
                "Eres un investigador científico. Lee el siguiente material de investigación y "
                "elabora un resumen estructurado en español con los hallazgos más relevantes, "
                "incluyendo fuentes cuando estén disponibles. Sé conciso pero completo.\n\n"
                f"MATERIAL RECOPILADO:\n{combined[:6000]}\n\n"
                "RESUMEN DE INVESTIGACIÓN:"
            )
        else:
            synthesis_model = _SYNTHESIS_FALLBACK_MODEL
            log(f"🧠 Etapa 4/4 — Sin fuentes externas. Síntesis desde conocimiento paramétrico ({synthesis_model})...")
            kw_str = ", ".join(keywords[:8]) if keywords else query_str
            synthesis_prompt = (
                f"Eres un investigador científico experto. Escribe un resumen de investigación "
                f"en español sobre el siguiente tema: '{query_str}'.\n\n"
                f"Palabras clave: {kw_str}\n\n"
                f"Estructura el resumen con:\n"
                f"- Estado del arte\n- Conceptos fundamentales\n- Aplicaciones y relevancia\n"
                f"- Líneas de investigación actuales\n\n"
                f"RESUMEN DE INVESTIGACIÓN:"
            )

        synthesis = await call_llm(
            synthesis_prompt,
            model=synthesis_model,
            timeout=600.0 if research_chunks else 120.0,
            keep_alive=0,   # unload after synthesis — frees VRAM before redactor loads its model
            num_ctx=8192 if research_chunks else 2048,   # more context for multi-source synthesis
        )
        if synthesis and len(synthesis.split()) > 30:
            research_chunks.append(f"[Síntesis] {synthesis}")
            sources.append({
                "title": f"Síntesis sobre: {query_str[:80]}",
                "url": "synthesis://investigador",
                "snippet": synthesis[:200],
            })
            log(f"✅ Síntesis generada — {len(synthesis.split())} palabras.")
        else:
            log("⚠️ Síntesis LLM vacía o muy corta.", "warning")
    except Exception as exc:
        logger.warning("LLM synthesis failed (non-critical): %s", exc)
        log(f"⚠️ Síntesis LLM no disponible: {exc}", "warning")

    # ── Fallback de último recurso ────────────────────────────────────────────
    if not research_chunks:
        log("⚠️ Sin ningún contenido de investigación generado. Usando contexto mínimo.", "warning")
        research_chunks.append(
            f"[Contexto base] Tema: {query_str}\nPalabras clave: {', '.join(keywords[:8])}\n"
            "No se encontraron fuentes externas para este tema. "
            "El redactor debe usar su conocimiento propio para generar el artículo."
        )

    research_data = "\n\n---\n\n".join(research_chunks)
    log(f"📦 Investigación completada: {len(sources)} fuente(s), {len(research_chunks)} fragmento(s).")
    return {"research_data": research_data, "sources": sources}
