import logging
from typing import Dict, Any, List

from app.core.config import settings
from app.modules.agents.adapters.rag import semantic_search_context

logger = logging.getLogger(__name__)



# Generated by GitHub Copilot
async def run_investigador(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Investigador Agent — two-stage research pipeline:

    1. Local RAG (Qdrant)   — semantic search of existing knowledge base.
    2. LLM synthesis        — summarise all collected material (optional,
       falls back gracefully if model is too small).
    """
    article_id = state.get("article_id")
    title = state.get("title") or ""
    keywords = state.get("keywords") or []
    log = state.get("_log") or (lambda msg, level="info": None)

    logger.info("Running Investigador for article %s with keywords %s", article_id, keywords)
    log(f"🔑 Keywords: {', '.join(keywords) if keywords else '(ninguna)'}")

    # Build query: title words + unique keywords (deduped, title takes priority)
    title_words = [w.strip(".,;:?!()[]") for w in title.split() if len(w) > 3] if title else []
    kw_words = [k for k in keywords if k.lower() not in {w.lower() for w in title_words}]
    combined_terms = title_words + kw_words
    query_str = " ".join(combined_terms) if combined_terms else "scientific research"
    log(f"🔍 Query de búsqueda: \"{query_str[:100]}\"")

    agent_cfg = (state.get("agent_settings") or {}).get("investigador", {})
    context_hint = (agent_cfg.get("context_hint") or "").strip()

    # semantic_rerank: agent_profile > config.yaml global default
    _agent_rerank = agent_cfg.get("semantic_rerank")
    if _agent_rerank is None:
        semantic_rerank = settings.SCRAPER_SEMANTIC_RERANK
    else:
        semantic_rerank = bool(_agent_rerank)
    if context_hint:
        query_str = f"{context_hint} {query_str}"
        logger.info("Investigador context hint: '%s'", context_hint[:80])
        log(f"💡 Context hint aplicado: \"{context_hint[:80]}\"")

    sources: List[Dict[str, Any]] = []
    research_chunks: List[str] = []

    # Resolve RAG collection
    rag_collection = (agent_cfg.get("rag_collection") or "").strip() or settings.QDRANT_COLLECTION
    rag_top_k = int(agent_cfg.get("rag_top_k") or 0) or settings.RAG_TOP_K
    rag_chunk_size = int(agent_cfg.get("rag_chunk_size") or 0) or settings.RAG_CHUNK_SIZE
    rag_doc_ids = agent_cfg.get("rag_doc_ids") or None
    if isinstance(rag_doc_ids, list) and len(rag_doc_ids) == 0:
        rag_doc_ids = None

    # ── Stage 1: Local RAG ───────────────────────────────────────────────────
    log(f"🔎 Etapa 1/2 — Buscando en base de conocimiento local (colección: {rag_collection})...")
    try:
        rag_context = await semantic_search_context(
            query=query_str,
            qdrant_url=settings.QDRANT_URL,
            collection=rag_collection,
            agent_name="investigador",
            ollama_base_url=settings.OLLAMA_BASE_URL,
            embedding_model=settings.OLLAMA_EMBED_MODEL,
            limit=rag_top_k,
            api_key=settings.QDRANT_API_KEY,
            doc_ids=rag_doc_ids,
        )
        if rag_context:
            rag_parts = [p for p in rag_context.split("\n\n---\n\n") if p]
            for index, text in enumerate(rag_parts):
                research_chunks.append(f"[RAG Source: local-{index}] {text}")
                sources.append({
                    "title": f"Local Document Chunk ({index + 1})",
                    "authors": "Biblioteca Local",
                    "journal": "Base de Conocimiento",
                    "year": "N/A",
                    "doi": "",
                    "url": f"local://investigador/{index + 1}",
                    "snippet": text[:200],
                })
            log(f"✅ RAG local: {len(rag_parts)} fragmento(s) encontrado(s).")
        else:
            log("ℹ️ RAG local sin resultados para esta consulta.")
    except Exception as exc:
        logger.warning("Could not search Qdrant: %s", exc)
        log(f"⚠️ RAG local no disponible: {exc}", "warning")

    # ── Stage 2: LLM synthesis ────────────────────────────────────────────────
    # Always run synthesis — with or without external sources.
    # If no external content was found, the LLM uses its parametric knowledge.
    try:
        from app.shared.llm import call_llm, get_default_model
        model = (agent_cfg.get("model") or "").strip() or get_default_model()

        # When there are no external sources, use a lightweight model for
        # parametric synthesis to avoid OOM when the next agent loads.
        # The investigador model (often mistral:7b) would stay in VRAM
        # and crash the redactor's KV-cache allocation.
        _SYNTHESIS_FALLBACK_MODEL = "llama3.2:1b"

        if research_chunks:
            log(f"🧠 Etapa 2/2 — Síntesis con LLM ({model}) de {len(research_chunks)} fragmento(s)...")
            synthesis_model = model
            combined = "\n\n---\n\n".join(research_chunks[:8])
            synthesis_prompt = (
                "Eres un investigador científico. Lee el siguiente material de investigación y "
                "elabora un resumen estructurado en español con los hallazgos más relevantes, "
                "incluyendo fuentes cuando estén disponibles. Sé conciso pero completo.\n\n"
                f"MATERIAL RECOPILADO:\n{combined[:6000]}\n\n"
                "RESUMEN DE INVESTIGACIÓN:"
            )
        else:
            synthesis_model = _SYNTHESIS_FALLBACK_MODEL
            log(f"🧠 Etapa 2/2 — Sin fuentes locales. Síntesis desde conocimiento paramétrico ({synthesis_model})...")
            kw_str = ", ".join(keywords[:8]) if keywords else query_str
            synthesis_prompt = (
                f"Eres un investigador científico experto. Escribe un resumen de investigación "
                f"en español sobre el siguiente tema: '{query_str}'.\n\n"
                f"Palabras clave: {kw_str}\n\n"
                f"Estructura el resumen con:\n"
                f"- Estado del arte\n- Conceptos fundamentales\n- Aplicaciones y relevancia\n"
                f"- Líneas de investigación actuales\n\n"
                f"RESUMEN DE INVESTIGACIÓN:"
            )

        synthesis = await call_llm(
            synthesis_prompt,
            model=synthesis_model,
            timeout=600.0 if research_chunks else 120.0,
            keep_alive=0,   # unload after synthesis — frees VRAM before redactor loads its model
            num_ctx=8192 if research_chunks else 2048,   # more context for multi-source synthesis
        )
        if synthesis and len(synthesis.split()) > 30:
            research_chunks.append(f"[Síntesis] {synthesis}")
            sources.append({
                "title": f"Síntesis sobre: {query_str[:80]}",
                "url": "synthesis://investigador",
                "snippet": synthesis[:200],
            })
            log(f"✅ Síntesis generada — {len(synthesis.split())} palabras.")
        else:
            log("⚠️ Síntesis LLM vacía o muy corta.", "warning")
    except Exception as exc:
        logger.warning("LLM synthesis failed (non-critical): %s", exc)
        log(f"⚠️ Síntesis LLM no disponible: {exc}", "warning")

    # ── Fallback de último recurso ────────────────────────────────────────────
    if not research_chunks:
        log("⚠️ Sin ningún contenido de investigación generado. Usando contexto mínimo.", "warning")
        research_chunks.append(
            f"[Contexto base] Tema: {query_str}\nPalabras clave: {', '.join(keywords[:8])}\n"
            "No se encontró información en la colección local para este tema. "
            "El redactor debe usar su conocimiento propio para generar el artículo."
        )

    research_data = "\n\n---\n\n".join(research_chunks)
    log(f"📦 Investigación completada: {len(sources)} fuente(s), {len(research_chunks)} fragmento(s).")
    return {"research_data": research_data, "sources": sources}

