import datetime
import logging
from typing import Dict, Any

from sqlalchemy import select

from app.shared.database import AsyncSessionLocal
from app.models import ArticleModel, ArticleStatus

logger = logging.getLogger(__name__)


# Generated by GitHub Copilot
async def run_publicador(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Publicador Agent.
    Persists the final formatted text to the database, marks the article as
    PUBLISHED, and returns indexing metadata with the published URL.
    """
    article_id = state.get("article_id")
    final_text = state.get("formatted_text") or state.get("draft_text") or ""
    log = state.get("_log") or (lambda msg, level="info": None)

    logger.info(f"Running Publicador for article: {article_id}")
    log(f"🚀 Publicando artículo en la base de datos...")

    word_count = len(final_text.split())
    metadata = {
        "indexed": True,
        "publisher": "AlexandrIA Magazine Editorial",
        "license": "CC-BY-4.0",
        "word_count": word_count,
        "reading_time_minutes": max(1, word_count // 200),
        "indexing_timestamp": datetime.datetime.utcnow().isoformat(),
    }

    published_url = f"http://localhost:8080/articles/{article_id}/view"

    try:
        async with AsyncSessionLocal() as session:
            stmt = select(ArticleModel).where(ArticleModel.id == article_id)
            result = await session.execute(stmt)
            article = result.scalars().first()
            if article:
                article.body = final_text
                article.status = ArticleStatus.PUBLISHED
                article.published_at = datetime.datetime.utcnow()
                fmt = state.get("scientific_format")
                if fmt and fmt != "none":
                    article.scientific_format = fmt
                session.add(article)
                await session.commit()
                logger.info(f"Article {article_id} successfully marked as PUBLISHED in DB")
                log(f"✅ Artículo publicado — {metadata['word_count']} palabras, {metadata['reading_time_minutes']} min de lectura.")
            else:
                logger.error(f"Article {article_id} not found in DB during publishing")
                log("⚠️ Artículo no encontrado en la base de datos.", "error")
    except Exception as e:
        logger.error(f"Error updating article to PUBLISHED in DB: {str(e)}")

    return {"published_url": published_url, "metadata": metadata}
