import asyncio
import logging
from typing import Dict, Any

from app.core.config import settings
from app.modules.agents.adapters.rag import semantic_search_context
from app.shared.llm import call_llm, call_llm_stream, get_default_model

logger = logging.getLogger(__name__)

# Default prompt templates per language
_DEFAULT_TEMPLATE_ES = (
    "Eres un escritor científico experto. Redacta un borrador de artículo científico en Markdown.\n"
    "{word_count_header}"
    "\nTítulo: {title}\n"
    "Palabras clave: {keywords}\n"
    "{context_section}"
    "### Contexto de investigación (incorpora estos datos y cita apropiadamente):\n"
    "{research_data}\n"
    "{feedback_section}\n"
    "Escribe un manuscrito científico estructurado que contenga:\n"
    "- Resumen (Abstract)\n- Introducción\n- Metodología\n- Resultados y Discusión Preliminares\n\n"
    "Redacta el borrador en español, con lenguaje académico y profesional."
    "{word_count_footer}"
)

_DEFAULT_TEMPLATE_EN = (
    "You are an expert scientific writer. Write a scientific paper draft in Markdown.\n"
    "{word_count_header}"
    "\nTitle: {title}\n"
    "Keywords: {keywords}\n"
    "{context_section}"
    "### Research Context (incorporate this data and cite appropriately):\n"
    "{research_data}\n"
    "{feedback_section}\n"
    "Write a structured scientific manuscript containing:\n"
    "- Abstract\n- Introduction\n- Methodology\n- Preliminary Results and Discussion\n\n"
    "Write the draft in English, in professional, academic language."
    "{word_count_footer}"
)

_FEEDBACK_HEADER_ES = (
    "\n### Feedback del Revisor:\n"
    "El revisor rechazó el borrador anterior con los siguientes comentarios. "
    "DEBES resolver estos problemas en el nuevo borrador:\n"
)

_FEEDBACK_HEADER_EN = (
    "\n### Feedback from Reviewer:\n"
    "The reviewer rejected the previous draft with the following comments. "
    "You MUST address these issues in the new draft:\n"
)

_CORRECTION_TEMPLATE_ES = (
    "Identidad: Eres un Ingeniero Senior de Software Experto en LLMOps y sistemas multi-agente.\n"
    "Stack tecnológico exacto: Python, FastAPI, LangGraph (v2), Qdrant y un motor de inferencia local (como Ollama/vLLM).\n\n"
    "MODO: Edición y Corrección de Manuscrito Científico.\n"
    "Ignora el prompt inicial genérico de creación. Tu única prioridad es revisar el borrador actual "
    "y corregir de forma estricta los puntos críticos señalados por el Revisor.\n\n"
    "Borrador actual:\n{draft_text}\n\n"
    "Feedback del Revisor:\n{feedback_section}\n\n"
    "{context_section}\n"
    "Escribe el borrador científico corregido y mejorado completo en Markdown:"
)

_CORRECTION_TEMPLATE_EN = (
    "Identity: You are a Senior Software Engineer Expert in LLMOps and multi-agent systems.\n"
    "Exact technology stack: Python, FastAPI, LangGraph (v2), Qdrant and a local inference engine (like Ollama/vLLM).\n\n"
    "MODE: Scientific Manuscript Editing and Correction.\n"
    "Ignore the generic initial creation prompt. Your sole priority is to review the current draft "
    "and strictly address the review comments provided by the Reviewer.\n\n"
    "Current draft:\n{draft_text}\n\n"
    "Reviewer Feedback:\n{feedback_section}\n\n"
    "{context_section}\n"
    "Write the complete corrected and improved scientific draft in Markdown:"
)


# Generated by GitHub Copilot
async def run_redactor(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Redactor Agent.
    Generates a scientific draft in Markdown using Ollama. Supports custom
    prompt templates and configurable output language (es/en). Incorporates
    reviewer feedback when in a correction loop.
    """
    title = state.get("title") or "Artículo Científico"
    keywords = state.get("keywords") or []
    research_data = state.get("research_data") or "No se proporcionó contexto de investigación."
    feedback = state.get("feedback") or []
    context_description = (state.get("context_description") or "").strip()
    article_outline = (state.get("article_outline") or "").strip()
    log = state.get("_log") or (lambda msg, level="info": None)

    # Resolve per-agent config: agent_settings overrides → settings default
    agent_cfg = (state.get("agent_settings") or {}).get("redactor", {})
    model = agent_cfg.get("model") or get_default_model()
    language = (agent_cfg.get("output_language") or "es").lower()
    custom_template = (agent_cfg.get("prompt_template") or "").strip()
    target_word_count = int(agent_cfg.get("target_word_count") or 0)

    logger.info(f"Running Redactor — title: '{title}', model: {model}, language: {language}, words: {target_word_count or 'unlimited'}")
    log(f"✍️ Modelo: {model} | idioma: {language} | palabras objetivo: {target_word_count or 'sin límite'}")
    if feedback:
        log(f"🔄 Iteración con feedback del revisor ({len(feedback)} comentario(s))")
        for item in feedback:
            log(f"  → {item}")

    # ── RAG lookup: pull additional context from the knowledge base ───────────
    rag_collection = (agent_cfg.get("rag_collection") or "").strip() or settings.QDRANT_COLLECTION
    rag_doc_ids = agent_cfg.get("rag_doc_ids") or None
    if isinstance(rag_doc_ids, list) and len(rag_doc_ids) == 0:
        rag_doc_ids = None

    log(f"🔎 Consultando base de conocimiento (colección: {rag_collection}, límite: 10)...")
    try:
        rag_query = f"{title} {' '.join(keywords[:6])}"
        extra_rag = await asyncio.wait_for(
            semantic_search_context(
                query=rag_query,
                qdrant_url=settings.QDRANT_URL,
                collection=rag_collection,
                agent_name="investigador",   # queries investigador's indexed data
                ollama_base_url=settings.OLLAMA_BASE_URL,
                embedding_model=settings.OLLAMA_EMBED_MODEL,
                limit=10,
                api_key=settings.QDRANT_API_KEY,
                doc_ids=rag_doc_ids,
            ),
            timeout=25.0,
        )
        if extra_rag:
            extra_words = len(extra_rag.split())
            research_data = (
                research_data
                + "\n\n---\n\n### Contexto adicional desde base de conocimiento:\n"
                + extra_rag
            )
            log(f"✅ RAG: {extra_words} palabras de contexto adicional encontradas.")
        else:
            log("ℹ️ RAG no devolvió contexto adicional para este tema.")
    except asyncio.TimeoutError:
        logger.warning("Redactor RAG lookup timed out after 25s — skipping")
        log("ℹ️ RAG omitido (timeout 25s) — continuando sin contexto adicional.")
    except Exception as exc:
        logger.warning("Redactor RAG lookup failed: %s", exc)
        log(f"⚠️ RAG no disponible: {exc}", "warning")

    # Build context section from user-provided description and outline
    context_parts = []
    if context_description:
        if language == "es":
            context_parts.append(f"### Enfoque / Instrucciones adicionales del autor:\n{context_description}")
        else:
            context_parts.append(f"### Focus / Additional author instructions:\n{context_description}")

    if article_outline:
        if language == "es":
            context_parts.append(
                f"### ESTRUCTURA Y SECCIONES REQUERIDAS DEL ARTÍCULO:\n"
                f"Usa ESTA estructura y nombres de sección creativos provistos por el autor en lugar de los estándar:\n"
                f"{article_outline}"
            )
        else:
            context_parts.append(
                f"### REQUIRED ARTICLE STRUCTURE AND SECTIONS:\n"
                f"Use THIS structure and creative section names provided by the author instead of the default ones:\n"
                f"{article_outline}"
            )

    if context_parts:
        context_section = "\n" + "\n\n".join(context_parts) + "\n\n"
    else:
        context_section = "\n"
    feedback_section = ""
    if feedback:
        items = "\n".join(f"- {f}" for f in feedback)
        header = _FEEDBACK_HEADER_ES if language == "es" else _FEEDBACK_HEADER_EN
        feedback_section = header + items

    # Build word-count guidance blocks
    if target_word_count > 0:
        # Distribute words proportionally across sections
        abstract_w  = max(50,  int(target_word_count * 0.10))
        intro_w     = max(100, int(target_word_count * 0.25))
        method_w    = max(100, int(target_word_count * 0.25))
        results_w   = max(100, int(target_word_count * 0.40))
        if language == "es":
            word_count_header = (
                f"\nREQUISITO DE LONGITUD: El borrador DEBE tener exactamente {target_word_count} palabras en total.\n"
                f"Distribuci\u00f3n obligatoria por secci\u00f3n:\n"
                f"  - Resumen: ~{abstract_w} palabras\n"
                f"  - Introducci\u00f3n: ~{intro_w} palabras\n"
                f"  - Metodolog\u00eda: ~{method_w} palabras\n"
                f"  - Resultados y Discusi\u00f3n: ~{results_w} palabras\n\n"
            )
            word_count_footer = (
                f"\n\nRECORDATORIO FINAL: el manuscrito completo debe tener {target_word_count} palabras. "
                f"Escribe cada secci\u00f3n hasta alcanzar el n\u00famero indicado."
            )
        else:
            word_count_header = (
                f"\nLENGTH REQUIREMENT: The draft MUST be exactly {target_word_count} words total.\n"
                f"Mandatory per-section distribution:\n"
                f"  - Abstract: ~{abstract_w} words\n"
                f"  - Introduction: ~{intro_w} words\n"
                f"  - Methodology: ~{method_w} words\n"
                f"  - Results and Discussion: ~{results_w} words\n\n"
            )
            word_count_footer = (
                f"\n\nFINAL REMINDER: the complete manuscript must be {target_word_count} words. "
                f"Write each section until you reach the word count shown above."
            )
    else:
        word_count_header = "\n"
        word_count_footer = ""

    # Render prompt: custom template takes priority over built-in
    if custom_template:
        prompt = custom_template.format(
            title=title,
            keywords=", ".join(keywords),
            research_data=research_data,
            feedback_section=feedback_section,
            context_section=context_section,
            language=language,
            word_count_header=word_count_header,
            word_count_footer=word_count_footer,
        )
    elif feedback:
        # MODO Edición y Corrección
        base = _CORRECTION_TEMPLATE_ES if language == "es" else _CORRECTION_TEMPLATE_EN
        prompt = base.format(
            draft_text=state.get("draft_text") or "",
            feedback_section=feedback_section,
            context_section=context_section,
        )
    else:
        base = _DEFAULT_TEMPLATE_ES if language == "es" else _DEFAULT_TEMPLATE_EN
        prompt = base.format(
            title=title,
            keywords=", ".join(keywords),
            research_data=research_data,
            feedback_section=feedback_section,
            context_section=context_section,
            word_count_header=word_count_header,
            word_count_footer=word_count_footer,
        )

    # Scale timeout: base 300s + 1.2s per expected word (minimum 1200s for slow local models)
    timeout = max(1200.0, 300.0 + target_word_count * 1.2) if target_word_count > 0 else 1200.0
    logger.info(f"Redactor timeout: {timeout:.0f}s")
    log(f"⏳ Generando borrador (timeout: {timeout:.0f}s)...")

    emit_token = state.get("_emit_token") or (lambda t: None)

    try:
        draft_chunks = []
        async for token in call_llm_stream(prompt, model=model, timeout=timeout, num_ctx=4096, keep_alive=0):
            emit_token(token)
            draft_chunks.append(token)
        draft_text = "".join(draft_chunks)

        if not draft_text:
            raise RuntimeError("LLM devolvió una respuesta vacía al generar el borrador")

        actual_words = len(draft_text.split())
        log(f"✅ Borrador generado — {actual_words} palabras.")

        # ── Word-count enforcement: retry once if significantly below target ──
        if target_word_count > 0 and actual_words < int(target_word_count * 0.85):
            shortfall = target_word_count - actual_words
            log(
                f"⚠️ Borrador corto ({actual_words}/{target_word_count} palabras). "
                f"Expandiendo {shortfall} palabras...",
                "warning",
            )
            if language == "es":
                expand_prompt = (
                    f"El siguiente borrador científico tiene solo {actual_words} palabras, "
                    f"pero DEBE tener exactamente {target_word_count} palabras.\n\n"
                    f"INSTRUCCIÓN OBLIGATORIA: Reescribe y expande el borrador añadiendo "
                    f"al menos {shortfall} palabras más. Amplía TODAS las secciones "
                    f"(Resumen, Introducción, Metodología, Resultados y Discusión). "
                    f"Añade más detalles técnicos, ejemplos concretos, análisis y referencias. "
                    f"Mantén el formato Markdown y el estilo académico.\n\n"
                    f"BORRADOR ACTUAL:\n{draft_text}\n\n"
                    f"BORRADOR EXPANDIDO ({target_word_count} palabras):"
                )
            else:
                expand_prompt = (
                    f"The following scientific draft has only {actual_words} words, "
                    f"but MUST have exactly {target_word_count} words.\n\n"
                    f"MANDATORY INSTRUCTION: Rewrite and expand the draft by adding at least "
                    f"{shortfall} more words. Expand ALL sections (Abstract, Introduction, "
                    f"Methodology, Results and Discussion). Add more technical details, "
                    f"concrete examples, analysis and references. "
                    f"Maintain Markdown format and academic style.\n\n"
                    f"CURRENT DRAFT:\n{draft_text}\n\n"
                    f"EXPANDED DRAFT ({target_word_count} words):"
                )
            try:
                expanded_chunks = []
                async for token in call_llm_stream(expand_prompt, model=model, timeout=timeout, num_ctx=4096, keep_alive=0):
                    emit_token(token)
                    expanded_chunks.append(token)
                expanded = "".join(expanded_chunks)
                if expanded:
                    expanded_words = len(expanded.split())
                    if expanded_words > actual_words:
                        draft_text = expanded
                        log(f"✅ Borrador expandido — {expanded_words} palabras.")
                    else:
                        log("ℹ️ La expansión no incrementó el conteo; usando borrador original.")
            except Exception as expand_err:
                logger.warning("Word-count expansion attempt failed: %s", expand_err)
                log(f"⚠️ No se pudo expandir: {expand_err}", "warning")

        return {"draft_text": draft_text}
    except RuntimeError:
        raise
    except Exception as e:
        logger.exception("Error calling LLM in Redactor")
        raise RuntimeError(f"Failed to call LLM: {type(e).__name__}: {e}") from e
