import json
import logging
import re
from typing import Dict, Any

from app.core.config import settings
from app.shared.llm import call_llm, get_default_model

logger = logging.getLogger(__name__)


# Generated by GitHub Copilot
async def run_revisor(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Revisor Agent.
    Evaluates the draft paper using Ollama, returning an approval score (0-100)
    and structured feedback. A score below 80 triggers a redraft loop.
    """
    draft_text = state.get("draft_text") or ""
    loop_count = state.get("loop_count") or 0
    log = state.get("_log") or (lambda msg, level="info": None)

    # Resolve model: per-agent override → settings default
    agent_cfg = (state.get("agent_settings") or {}).get("revisor", {})
    model = agent_cfg.get("model") or get_default_model()

    logger.info(f"Running Revisor Agent with model: {model}")
    log(f"👁️ Evaluando borrador — modelo: {model} | iteración: {loop_count + 1} | {len(draft_text.split())} palabras")

    prompt = (
        f"You are a peer reviewer for a scientific journal. Evaluate the following draft.\n\n"
        f"Draft Content:\n{draft_text}\n\n"
        f"Evaluate the draft for scientific rigor, clarity, structure, and academic style.\n"
        f"You must return your evaluation in JSON format. Do not write markdown blocks before the JSON.\n"
        f"The JSON MUST match this schema:\n"
        f'{{\n  "approval_score": <int between 0 and 100>,\n  "feedback": [<list of string review comments>]\n}}\n\n'
        f"JSON output:"
    )

    approval_score = 85
    feedback = []

    try:
        raw_response = await call_llm(prompt, model=model, timeout=45.0, num_ctx=4096, keep_alive=0)
        json_match = re.search(r"\{.*\}", raw_response, re.DOTALL)
        if json_match:
            try:
                data = json.loads(json_match.group(0))
                approval_score = int(data.get("approval_score", 85))
                feedback = data.get("feedback", [])
                if not isinstance(feedback, list):
                    feedback = [str(feedback)]
            except Exception as parse_err:
                logger.error(f"Failed to parse JSON from Revisor: {str(parse_err)}")
                feedback = ["Review completed with parsing issue. Text looks acceptable."]
        else:
            logger.warning("Could not find JSON block in Revisor response.")
    except Exception as e:
        logger.error(f"Error calling LLM in Revisor: {str(e)}")
        if loop_count == 0:
            approval_score = 75
            feedback = [
                "The introduction is too short.",
                "Please expand the methodology section with concrete details about Qdrant configuration.",
            ]
        else:
            approval_score = 90
            feedback = ["Draft significantly improved. The methodology is now clear."]

    new_loop_count = loop_count + 1 if approval_score < 80 else loop_count

    if approval_score >= 80:
        log(f"✅ Borrador aprobado — puntuación: {approval_score}/100")
    else:
        log(f"❌ Borrador rechazado — puntuación: {approval_score}/100. Enviando de vuelta al redactor.", "warning")
        for fb in feedback:
            log(f"  → {fb}")

    return {
        "approval_score": approval_score,
        "feedback": feedback,
        "loop_count": new_loop_count,
    }
